<?php

namespace App\Support\Presentation\Blueprints;

final class CashBankPageBlueprint
{
    public static function cashPaymentPage(): array
    {
        return [
            'subtab' => [
                'id' => 'cash-payment-create',
                'label' => 'Data Baru',
            ],
            'viewModes' => [
                'form' => 'Form',
                'table' => 'Tabel',
            ],
            'cashPayment' => [
                'topActions' => [
                    [
                        'id' => 'settings',
                        'label' => 'Pengaturan',
                        'icon' => 'settings',
                        'tone' => 'outline',
                    ],
                ],
                'labels' => [
                    'cashBank' => 'Kas/Bank',
                    'documentNumber' => 'No Bukti #',
                    'entryDate' => 'Tanggal',
                    'checkNumber' => 'No Cek #',
                    'recipient' => 'Penerima',
                    'voided' => 'V O I D',
                    'branch' => 'Cabang',
                    'notes' => 'Catatan',
                    'reconcileStatus' => 'Terekonsiliasi',
                    'printStatus' => 'Dicetak/email',
                    'kapKjs' => 'No KAP - No KJS',
                    'ntpn' => 'NTPN',
                ],
                'cashBankPlaceholder' => 'Cari/Pilih...',
                'branchPlaceholder' => 'Cari/Pilih...',
                'numberingOptions' => [
                    'Bank BCA IDR Jakarta (069-773-3993)',
                    'Bank Mandiri IDR Surabaya',
                    'Kas Besar Kantor Jakarta',
                ],
                'takeButtonLabel' => 'Ambil',
                'lineSearchPlaceholder' => 'Cari/Pilih Akun Perkiraan...',
                'lineSectionTitle' => 'Rincian Pembayaran',
                'infoTitle' => 'Info lainnya',
                'additionalInfoTitle' => 'Info Tambahan',
                'totalCardLabel' => 'Nilai',
                'sectionTabs' => [
                    ['id' => 'details', 'label' => 'Rincian Pembayaran', 'icon' => 'document'],
                    ['id' => 'additional-info', 'label' => 'Info lainnya', 'icon' => 'info'],
                ],
                'dockActions' => [
                    [
                        'id' => 'save',
                        'label' => 'Simpan',
                        'icon' => 'save',
                        'tone' => 'primary',
                        'items' => [
                            ['id' => 'save-now', 'label' => 'Simpan'],
                            ['id' => 'save-new', 'label' => 'Simpan dan buat baru'],
                        ],
                    ],
                    [
                        'id' => 'document',
                        'label' => 'Form lain',
                        'icon' => 'document',
                        'tone' => 'secondary',
                        'items' => [
                            ['id' => 'open-document', 'label' => 'Buka dokumen terkait'],
                            ['id' => 'preview-document', 'label' => 'Preview dokumen'],
                        ],
                    ],
                    [
                        'id' => 'attachment',
                        'label' => 'Lampiran',
                        'icon' => 'paperclip',
                        'tone' => 'secondary',
                        'items' => [
                            ['id' => 'add-attachment', 'label' => 'Tambah lampiran'],
                            ['id' => 'manage-attachment', 'label' => 'Kelola lampiran'],
                        ],
                    ],
                    [
                        'id' => 'more',
                        'label' => 'Lainnya',
                        'icon' => 'kebab',
                        'tone' => 'success',
                        'items' => [
                            ['id' => 'duplicate-transaction', 'label' => 'Duplikasi transaksi'],
                            ['id' => 'mark-review', 'label' => 'Tandai untuk review'],
                        ],
                    ],
                    [
                        'id' => 'delete',
                        'label' => 'Hapus',
                        'icon' => 'trash',
                        'tone' => 'danger',
                    ],
                ],
                'draft' => [
                    'bankAccounts' => [],
                    'entryDate' => '25/04/2026',
                    'autoNumber' => true,
                    'numberingType' => 'Bank BCA IDR Jakarta (069-773-3993)',
                    'documentNumber' => '',
                    'checkNumber' => '',
                    'recipient' => '',
                    'voided' => false,
                    'branches' => ['JAKARTA'],
                    'notes' => '',
                    'lineItems' => [],
                    'totalValue' => '0',
                    'saveTone' => 'primary',
                    'kapNumber' => '',
                    'kjsNumber' => '',
                    'ntpn' => '',
                    'reconcileStatus' => '',
                    'printStatus' => '',
                ],
                'lineTable' => [
                    'columns' => [
                        ['id' => 'spacer', 'label' => '', 'kind' => 'spacer', 'widthClassName' => 'w-[40px]', 'align' => 'center'],
                        ['id' => 'accountCode', 'label' => 'Akun', 'widthClassName' => 'w-[130px]', 'align' => 'left'],
                        ['id' => 'accountName', 'label' => 'Nama Akun', 'align' => 'left'],
                        ['id' => 'amount', 'label' => 'Nilai', 'widthClassName' => 'w-[150px]', 'align' => 'right'],
                    ],
                    'emptyLabel' => 'Belum ada data',
                ],
                'table' => [
                    'createLabel' => 'Tambah Pembayaran',
                    'refreshLabel' => 'Sinkron pembayaran',
                    'downloadLabel' => 'Unduh data pembayaran',
                    'printLabel' => 'Cetak pembayaran',
                    'settingsLabel' => 'Pengaturan tabel pembayaran',
                    'filterButtonLabel' => 'Filter lanjutan',
                    'searchPlaceholder' => 'Cari...',
                    'pageValue' => '32',
                    'downloadItems' => [
                        ['id' => 'download-excel', 'label' => 'Unduh Excel'],
                        ['id' => 'download-pdf', 'label' => 'Unduh PDF'],
                    ],
                    'settingsItems' => [
                        ['id' => 'arrange-columns', 'label' => 'Atur kolom'],
                        ['id' => 'export-payment', 'label' => 'Ekspor pembayaran'],
                    ],
                    'filters' => [
                        [
                            'id' => 'date',
                            'rowKey' => 'dateFilter',
                            'options' => [
                                ['value' => 'all', 'label' => 'Tanggal: Semua'],
                                ['value' => '2017', 'label' => 'Tanggal: 2017'],
                                ['value' => '2016', 'label' => 'Tanggal: 2016'],
                            ],
                        ],
                        [
                            'id' => 'bank',
                            'rowKey' => 'bankFilter',
                            'options' => [
                                ['value' => 'all', 'label' => 'Kas/Bank: Semua'],
                                ['value' => 'cash-jkt', 'label' => 'Kas/Bank: Kas Jakarta'],
                                ['value' => 'cash-sby', 'label' => 'Kas/Bank: Kas Surabaya'],
                                ['value' => 'bank-bca', 'label' => 'Kas/Bank: Bank BCA'],
                                ['value' => 'bank-mandiri', 'label' => 'Kas/Bank: Bank Mandiri'],
                            ],
                        ],
                    ],
                    'columns' => [
                        ['id' => 'number', 'label' => 'Nomor #', 'widthClassName' => 'w-[210px]'],
                        ['id' => 'date', 'label' => 'Tanggal', 'widthClassName' => 'w-[120px]'],
                        ['id' => 'cashBank', 'label' => 'Kas/Bank', 'widthClassName' => 'w-[200px]'],
                        ['id' => 'checkNumber', 'label' => 'No Cek #', 'widthClassName' => 'w-[150px]'],
                        ['id' => 'description', 'label' => 'Keterangan'],
                        ['id' => 'amount', 'label' => 'Nilai', 'widthClassName' => 'w-[160px]', 'align' => 'right'],
                    ],
                    'rows' => [
                        ['id' => '111.201-02.2017.02.00001', 'number' => '111.201-02.2017.02.00001', 'date' => '10/02/2017', 'cashBank' => 'Kas Besar Kantor Surab...', 'cashBankFull' => 'Kas Besar Kantor Surabaya', 'checkNumber' => '', 'description' => 'Pembayaran Hutang Pajak PPh Ps 21', 'amount' => '1,447,298', 'dateFilter' => '2017', 'bankFilter' => 'cash-sby', 'branch' => 'SURABAYA', 'accountCode' => '215.000-02', 'accountName' => 'Hutang Pajak PPh Ps 21', 'voided' => true, 'reconcileStatus' => 'Belum', 'printStatus' => 'Belum cetak/email'],
                        ['id' => '111.101-02.2017.02.00002', 'number' => '111.101-02.2017.02.00002', 'date' => '10/02/2017', 'cashBank' => 'Kas Besar Kantor Jakarta', 'cashBankFull' => 'Kas Besar Kantor Jakarta', 'checkNumber' => '', 'description' => 'Pembayaran atas hutang Pajak PPh Ps 21', 'amount' => '1,897,540', 'dateFilter' => '2017', 'bankFilter' => 'cash-jkt', 'branch' => 'JAKARTA'],
                        ['id' => '111.202-04.2017.01.00008', 'number' => '111.202-04.2017.01.00008', 'date' => '26/01/2017', 'cashBank' => 'Bank Mandiri IDR Surab...', 'cashBankFull' => 'Bank Mandiri IDR Surabaya', 'checkNumber' => '', 'description' => 'Pembayaran Beban Gaji', 'amount' => '35,059,002', 'dateFilter' => '2017', 'bankFilter' => 'bank-mandiri', 'branch' => 'SURABAYA'],
                        ['id' => '111.102-01.2017.01.00009', 'number' => '111.102-01.2017.01.00009', 'date' => '26/01/2017', 'cashBank' => 'Bank BCA IDR Jakarta (0...', 'cashBankFull' => 'Bank BCA IDR Jakarta (069-773-3993)', 'checkNumber' => '', 'description' => 'Pembayaran Gaji Bulan', 'amount' => '49,136,660', 'dateFilter' => '2017', 'bankFilter' => 'bank-bca', 'branch' => 'JAKARTA'],
                        ['id' => '111.202-04.2017.01.00007', 'number' => '111.202-04.2017.01.00007', 'date' => '11/01/2017', 'cashBank' => 'Bank Mandiri IDR Surab...', 'cashBankFull' => 'Bank Mandiri IDR Surabaya', 'checkNumber' => '', 'description' => 'Pembayaran beban Iklan dan Komisi Penjualan', 'amount' => '117,814,000', 'dateFilter' => '2017', 'bankFilter' => 'bank-mandiri', 'branch' => 'SURABAYA'],
                        ['id' => '111.202-04.2017.01.00006', 'number' => '111.202-04.2017.01.00006', 'date' => '11/01/2017', 'cashBank' => 'Bank Mandiri IDR Surab...', 'cashBankFull' => 'Bank Mandiri IDR Surabaya', 'checkNumber' => '', 'description' => 'Pembayaran BPJS Ketenaga Kerjaan dan Kesehatan - Surabaya', 'amount' => '3,706,824', 'dateFilter' => '2017', 'bankFilter' => 'bank-mandiri', 'branch' => 'SURABAYA'],
                        ['id' => '111.102-04.2017.01.00005', 'number' => '111.102-04.2017.01.00005', 'date' => '10/01/2017', 'cashBank' => 'Bank Mandiri IDR Jakart...', 'cashBankFull' => 'Bank Mandiri IDR Jakarta', 'checkNumber' => '', 'description' => 'Pembayaran BPJS Ketenaga Kerjaan dan Kesehatan - Jakarta', 'amount' => '4,984,096', 'dateFilter' => '2017', 'bankFilter' => 'bank-mandiri', 'branch' => 'JAKARTA'],
                        ['id' => '111.202-01.2016.12.00007', 'number' => '111.202-01.2016.12.00007', 'date' => '26/12/2016', 'cashBank' => 'Bank BCA IDR Surabaya...', 'cashBankFull' => 'Bank BCA IDR Surabaya', 'checkNumber' => '', 'description' => 'Pembayaran Gaji - Surabaya', 'amount' => '36,506,300', 'dateFilter' => '2016', 'bankFilter' => 'bank-bca', 'branch' => 'SURABAYA'],
                        ['id' => '111.102-01.2016.12.00006', 'number' => '111.102-01.2016.12.00006', 'date' => '26/12/2016', 'cashBank' => 'Bank BCA IDR Jakarta (0...', 'cashBankFull' => 'Bank BCA IDR Jakarta (069-773-3993)', 'checkNumber' => '', 'description' => 'Pembayaran Gaji - Jakarta', 'amount' => '51,034,200', 'dateFilter' => '2016', 'bankFilter' => 'bank-bca', 'branch' => 'JAKARTA'],
                        ['id' => '111.101-01.2016.12.00005', 'number' => '111.101-01.2016.12.00005', 'date' => '21/12/2016', 'cashBank' => 'Kas Kecil Kantor Jakarta', 'cashBankFull' => 'Kas Kecil Kantor Jakarta', 'checkNumber' => '', 'description' => 'Pembayaran Sumbangan', 'amount' => '20,000,000', 'dateFilter' => '2016', 'bankFilter' => 'cash-jkt', 'branch' => 'JAKARTA'],
                        ['id' => '111.201-01.2016.12.00004', 'number' => '111.201-01.2016.12.00004', 'date' => '16/12/2016', 'cashBank' => 'Kas Kecil Kantor Suraba...', 'cashBankFull' => 'Kas Kecil Kantor Surabaya', 'checkNumber' => '', 'description' => 'Pembayaran Biaya Iklan - (Banner)', 'amount' => '345,000', 'dateFilter' => '2016', 'bankFilter' => 'cash-sby', 'branch' => 'SURABAYA'],
                        ['id' => '111.101-01.2016.12.00004', 'number' => '111.101-01.2016.12.00004', 'date' => '16/12/2016', 'cashBank' => 'Kas Kecil Kantor Jakarta', 'cashBankFull' => 'Kas Kecil Kantor Jakarta', 'checkNumber' => '', 'description' => 'Pembelian Alat Tulis Kantor', 'amount' => '550,000', 'dateFilter' => '2016', 'bankFilter' => 'cash-jkt', 'branch' => 'JAKARTA'],
                        ['id' => '111.201-02.2016.12.00003', 'number' => '111.201-02.2016.12.00003', 'date' => '16/12/2016', 'cashBank' => 'Kas Besar Kantor Surab...', 'cashBankFull' => 'Kas Besar Kantor Surabaya', 'checkNumber' => '', 'description' => 'Pembayaran Biaya Asuran - Surabaya', 'amount' => '3,700,000', 'dateFilter' => '2016', 'bankFilter' => 'cash-sby', 'branch' => 'SURABAYA'],
                        ['id' => '111.101-02.2016.12.00003', 'number' => '111.101-02.2016.12.00003', 'date' => '16/12/2016', 'cashBank' => 'Kas Besar Kantor Jakarta', 'cashBankFull' => 'Kas Besar Kantor Jakarta', 'checkNumber' => '', 'description' => 'Pembayaran Biaya sewa Kantor - Jakarta', 'amount' => '25,000,000', 'dateFilter' => '2016', 'bankFilter' => 'cash-jkt', 'branch' => 'JAKARTA'],
                        ['id' => '111.101-01.2016.12.00002', 'number' => '111.101-01.2016.12.00002', 'date' => '16/12/2016', 'cashBank' => 'Kas Kecil Kantor Jakarta', 'cashBankFull' => 'Kas Kecil Kantor Jakarta', 'checkNumber' => '', 'description' => 'Pembayaran Listrik dan Air - Jakarta', 'amount' => '3,350,000', 'dateFilter' => '2016', 'bankFilter' => 'cash-jkt', 'branch' => 'JAKARTA'],
                        ['id' => '111.102-01.2016.12.00002', 'number' => '111.102-01.2016.12.00002', 'date' => '09/12/2016', 'cashBank' => 'Bank BCA IDR Jakarta (0...', 'cashBankFull' => 'Bank BCA IDR Jakarta (069-773-3993)', 'checkNumber' => '', 'description' => 'Pembayaran Hutang Bunga', 'amount' => '86,250,000', 'dateFilter' => '2016', 'bankFilter' => 'bank-bca', 'branch' => 'JAKARTA'],
                        ['id' => '111.102-01.2016.12.00001', 'number' => '111.102-01.2016.12.00001', 'date' => '08/12/2016', 'cashBank' => 'Bank BCA IDR Jakarta (0...', 'cashBankFull' => 'Bank BCA IDR Jakarta (069-773-3993)', 'checkNumber' => '', 'description' => 'Pembayaran Hutang Bunga - Surabaya', 'amount' => '52,500,000', 'dateFilter' => '2016', 'bankFilter' => 'bank-bca', 'branch' => 'SURABAYA'],
                        ['id' => '111.201-01.2016.12.00001', 'number' => '111.201-01.2016.12.00001', 'date' => '01/12/2016', 'cashBank' => 'Kas Kecil Kantor Suraba...', 'cashBankFull' => 'Kas Kecil Kantor Surabaya', 'checkNumber' => '', 'description' => 'Pembayaran Beban Listrik dan Air - Surabaya', 'amount' => '2,750,000', 'dateFilter' => '2016', 'bankFilter' => 'cash-sby', 'branch' => 'SURABAYA'],
                        ['id' => '111.101-02.2016.11.00002', 'number' => '111.101-02.2016.11.00002', 'date' => '25/11/2016', 'cashBank' => 'Kas Besar Kantor Jakarta', 'cashBankFull' => 'Kas Besar Kantor Jakarta', 'checkNumber' => '', 'description' => 'Pembayaran BPJS Ketenaga Kerjaan dan Kesehatan - Jakarta', 'amount' => '4,984,096', 'dateFilter' => '2016', 'bankFilter' => 'cash-jkt', 'branch' => 'JAKARTA'],
                    ],
                ],
                'detailRecords' => [
                    '111.201-02.2017.02.00001' => [
                        'bankAccounts' => ['Kas Besar Kantor Surabaya'],
                        'entryDate' => '10/02/2017',
                        'autoNumber' => false,
                        'numberingType' => 'Bank BCA IDR Jakarta (069-773-3993)',
                        'documentNumber' => '111.201-02.2017.02.00001',
                        'checkNumber' => '',
                        'recipient' => '',
                        'voided' => true,
                        'branches' => ['SURABAYA'],
                        'notes' => 'Pembayaran Hutang Pajak PPh Ps 21',
                        'lineItems' => [
                            [
                                'id' => 'cash-payment-line-1',
                                'accountCode' => '215.000-02',
                                'accountName' => 'Hutang Pajak PPh Ps 21',
                                'amount' => '1,447,298',
                            ],
                        ],
                        'totalValue' => 'Rp 1,447,298',
                        'saveTone' => 'muted',
                        'kapNumber' => '',
                        'kjsNumber' => '',
                        'ntpn' => '',
                        'reconcileStatus' => 'Belum',
                        'printStatus' => 'Belum cetak/email',
                    ],
                ],
            ],
        ];
    }

    public static function cashReceiptPage(): array
    {
        return [
            'subtab' => [
                'id' => 'cash-receipt-create',
                'label' => 'Data Baru',
            ],
            'viewModes' => [
                'form' => 'Form',
                'table' => 'Tabel',
            ],
            'cashReceipt' => [
                'topActions' => [
                    [
                        'id' => 'settings',
                        'label' => 'Pengaturan',
                        'icon' => 'settings',
                        'tone' => 'outline',
                    ],
                ],
                'labels' => [
                    'cashBank' => 'Kas/Bank',
                    'documentNumber' => 'No Bukti #',
                    'entryDate' => 'Tanggal',
                    'checkNumber' => 'No Cek #',
                    'payer' => 'Pemberi',
                    'voided' => 'V O I D',
                    'branch' => 'Cabang',
                    'notes' => 'Catatan',
                    'reconcileStatus' => 'Terekonsiliasi',
                    'printStatus' => 'Dicetak/email',
                ],
                'cashBankPlaceholder' => 'Cari/Pilih...',
                'branchPlaceholder' => 'Cari/Pilih...',
                'numberingOptions' => [
                    'Bank BCA IDR Jakarta (069-773-3993)',
                    'Bank Mandiri IDR Surabaya (276-129-4178)',
                    'Bank BCA IDR Surabaya (388-308-3993)',
                ],
                'lineSearchPlaceholder' => 'Cari/Pilih Akun Perkiraan...',
                'lineSectionTitle' => 'Rincian Penerimaan',
                'infoTitle' => 'Info lainnya',
                'totalCardLabel' => 'Nilai',
                'sectionTabs' => [
                    ['id' => 'details', 'label' => 'Rincian Penerimaan', 'icon' => 'document'],
                    ['id' => 'additional-info', 'label' => 'Info lainnya', 'icon' => 'info'],
                ],
                'dockActions' => [
                    [
                        'id' => 'save',
                        'label' => 'Simpan',
                        'icon' => 'save',
                        'tone' => 'primary',
                        'items' => [
                            ['id' => 'save-now', 'label' => 'Simpan'],
                            ['id' => 'save-new', 'label' => 'Simpan dan buat baru'],
                        ],
                    ],
                    [
                        'id' => 'document',
                        'label' => 'Form lain',
                        'icon' => 'document',
                        'tone' => 'secondary',
                        'items' => [
                            ['id' => 'open-document', 'label' => 'Buka dokumen terkait'],
                            ['id' => 'preview-document', 'label' => 'Preview dokumen'],
                        ],
                    ],
                    [
                        'id' => 'attachment',
                        'label' => 'Lampiran',
                        'icon' => 'paperclip',
                        'tone' => 'secondary',
                        'items' => [
                            ['id' => 'add-attachment', 'label' => 'Tambah lampiran'],
                            ['id' => 'manage-attachment', 'label' => 'Kelola lampiran'],
                        ],
                    ],
                    [
                        'id' => 'more',
                        'label' => 'Lainnya',
                        'icon' => 'kebab',
                        'tone' => 'success',
                        'items' => [
                            ['id' => 'duplicate-transaction', 'label' => 'Duplikasi transaksi'],
                            ['id' => 'mark-review', 'label' => 'Tandai untuk review'],
                        ],
                    ],
                    [
                        'id' => 'delete',
                        'label' => 'Hapus',
                        'icon' => 'trash',
                        'tone' => 'danger',
                    ],
                ],
                'draft' => [
                    'bankAccounts' => [],
                    'entryDate' => '25/04/2026',
                    'autoNumber' => true,
                    'numberingType' => 'Bank BCA IDR Jakarta (069-773-3993)',
                    'documentNumber' => '',
                    'checkNumber' => '',
                    'payer' => '',
                    'voided' => false,
                    'branches' => ['JAKARTA'],
                    'notes' => '',
                    'lineItems' => [],
                    'totalValue' => '0',
                    'saveTone' => 'primary',
                    'reconcileStatus' => '',
                    'reconcileDate' => '',
                    'printStatus' => '',
                ],
                'lineTable' => [
                    'columns' => [
                        ['id' => 'accountCode', 'label' => 'Akun', 'widthClassName' => 'w-[130px]', 'align' => 'left'],
                        ['id' => 'accountName', 'label' => 'Nama Akun', 'align' => 'left'],
                        ['id' => 'amount', 'label' => 'Nilai', 'widthClassName' => 'w-[150px]', 'align' => 'right'],
                    ],
                    'emptyLabel' => 'Belum ada data',
                ],
                'table' => [
                    'createLabel' => 'Tambah Penerimaan',
                    'refreshLabel' => 'Sinkron penerimaan',
                    'downloadLabel' => 'Unduh data penerimaan',
                    'printLabel' => 'Cetak penerimaan',
                    'settingsLabel' => 'Pengaturan tabel penerimaan',
                    'filterButtonLabel' => 'Filter lanjutan',
                    'searchPlaceholder' => 'Cari...',
                    'pageValue' => '6',
                    'downloadItems' => [
                        ['id' => 'download-excel', 'label' => 'Unduh Excel'],
                        ['id' => 'download-pdf', 'label' => 'Unduh PDF'],
                    ],
                    'settingsItems' => [
                        ['id' => 'arrange-columns', 'label' => 'Atur kolom'],
                        ['id' => 'export-receipt', 'label' => 'Ekspor penerimaan'],
                    ],
                    'filters' => [
                        [
                            'id' => 'date',
                            'rowKey' => 'dateFilter',
                            'options' => [
                                ['value' => 'all', 'label' => 'Tanggal: Semua'],
                                ['value' => '2016', 'label' => 'Tanggal: 2016'],
                            ],
                        ],
                        [
                            'id' => 'bank',
                            'rowKey' => 'bankFilter',
                            'options' => [
                                ['value' => 'all', 'label' => 'Kas/Bank: Semua'],
                                ['value' => 'bank-bca', 'label' => 'Kas/Bank: Bank BCA'],
                                ['value' => 'bank-mandiri', 'label' => 'Kas/Bank: Bank Mandiri'],
                            ],
                        ],
                    ],
                    'columns' => [
                        ['id' => 'number', 'label' => 'Nomor #', 'widthClassName' => 'w-[210px]'],
                        ['id' => 'date', 'label' => 'Tanggal', 'widthClassName' => 'w-[120px]'],
                        ['id' => 'cashBank', 'label' => 'Kas/Bank', 'widthClassName' => 'w-[200px]'],
                        ['id' => 'checkNumber', 'label' => 'No Cek #', 'widthClassName' => 'w-[150px]'],
                        ['id' => 'description', 'label' => 'Keterangan'],
                        ['id' => 'amount', 'label' => 'Nilai', 'widthClassName' => 'w-[160px]', 'align' => 'right'],
                    ],
                    'rows' => [
                        ['id' => '111.202-04.2016.12.00001', 'number' => '111.202-04.2016.12.00001', 'date' => '31/12/2016', 'cashBank' => 'Bank Mandiri IDR Surab...', 'cashBankFull' => 'Bank Mandiri IDR Surabaya (276-129-4178)', 'checkNumber' => '', 'description' => '', 'amount' => '4,346,346', 'dateFilter' => '2016', 'bankFilter' => 'bank-mandiri', 'branch' => 'JAKARTA', 'accountCode' => '811.000-01', 'accountName' => 'Pendapatan Bunga Bank', 'reconcileStatus' => 'Ya', 'reconcileDate' => '(11/02/2017)', 'printStatus' => 'Belum cetak/email'],
                        ['id' => '111.202-02.2016.12.00002', 'number' => '111.202-02.2016.12.00002', 'date' => '16/12/2016', 'cashBank' => 'Bank BCA USD Surabay...', 'cashBankFull' => 'Bank BCA USD Surabaya (247-878-6241)', 'checkNumber' => '', 'description' => '', 'amount' => '307', 'dateFilter' => '2016', 'bankFilter' => 'bank-bca', 'branch' => 'JAKARTA'],
                        ['id' => '111.102-02.2016.12.00004', 'number' => '111.102-02.2016.12.00004', 'date' => '16/12/2016', 'cashBank' => 'Bank BCA USD Jakarta (...', 'cashBankFull' => 'Bank BCA USD Jakarta (247-878-6241)', 'checkNumber' => '', 'description' => '', 'amount' => '1,023', 'dateFilter' => '2016', 'bankFilter' => 'bank-bca', 'branch' => 'JAKARTA'],
                        ['id' => '111.202-01.2016.12.00003', 'number' => '111.202-01.2016.12.00003', 'date' => '16/12/2016', 'cashBank' => 'Bank BCA IDR Surabaya...', 'cashBankFull' => 'Bank BCA IDR Surabaya (388-308-3993)', 'checkNumber' => '', 'description' => '', 'amount' => '8,765,000', 'dateFilter' => '2016', 'bankFilter' => 'bank-bca', 'branch' => 'JAKARTA'],
                        ['id' => '111.102-01.2016.12.00003', 'number' => '111.102-01.2016.12.00003', 'date' => '16/12/2016', 'cashBank' => 'Bank BCA IDR Jakarta (0...', 'cashBankFull' => 'Bank BCA IDR Jakarta (069-773-3993)', 'checkNumber' => '', 'description' => '', 'amount' => '10,340,000', 'dateFilter' => '2016', 'bankFilter' => 'bank-bca', 'branch' => 'JAKARTA'],
                        ['id' => '111.102-04.2016.11.00001', 'number' => '111.102-04.2016.11.00001', 'date' => '30/11/2016', 'cashBank' => 'Bank Mandiri IDR Jakart...', 'cashBankFull' => 'Bank Mandiri IDR Jakarta', 'checkNumber' => '', 'description' => '', 'amount' => '6,004,500', 'dateFilter' => '2016', 'bankFilter' => 'bank-mandiri', 'branch' => 'JAKARTA'],
                    ],
                ],
                'detailRecords' => [
                    '111.202-04.2016.12.00001' => [
                        'bankAccounts' => ['Bank Mandiri IDR Surabaya (276-129-4178)'],
                        'entryDate' => '31/12/2016',
                        'autoNumber' => false,
                        'numberingType' => 'Bank BCA IDR Jakarta (069-773-3993)',
                        'documentNumber' => '111.202-04.2016.12.00001',
                        'checkNumber' => '',
                        'payer' => '',
                        'voided' => false,
                        'branches' => ['JAKARTA'],
                        'notes' => '',
                        'lineItems' => [
                            [
                                'id' => 'cash-receipt-line-1',
                                'accountCode' => '811.000-01',
                                'accountName' => 'Pendapatan Bunga Bank',
                                'amount' => '4,346,346',
                            ],
                        ],
                        'totalValue' => 'Rp 4,346,346',
                        'saveTone' => 'muted',
                        'reconcileStatus' => 'Ya',
                        'reconcileDate' => '(11/02/2017)',
                        'printStatus' => 'Belum cetak/email',
                    ],
                ],
            ],
        ];
    }

    public static function bankTransferPage(): array
    {
        return [
            'subtab' => [
                'id' => 'bank-transfer-create',
                'label' => 'Data Baru',
            ],
            'viewModes' => [
                'form' => 'Form',
                'table' => 'Tabel',
            ],
            'bankTransfer' => [
                'topActions' => [
                    [
                        'id' => 'settings',
                        'label' => 'Pengaturan',
                        'icon' => 'settings',
                        'tone' => 'outline',
                    ],
                ],
                'labels' => [
                    'entryDate' => 'Tanggal',
                    'documentNumber' => 'Nomor #',
                    'fromBank' => 'Dari Kas/Bank',
                    'fromBranch' => 'Cabang',
                    'exchangeRate' => 'Kurs',
                    'transferValue' => 'Nilai Transfer',
                    'toBank' => 'Ke Kas/Bank',
                    'toBranch' => 'Ke Cabang',
                    'resultValue' => 'Hasil Transfer',
                    'notes' => 'Catatan',
                    'reconcileStatus' => 'Terekonsiliasi',
                ],
                'bankPlaceholder' => 'Cari/Pilih...',
                'branchPlaceholder' => 'Cari/Pilih...',
                'feeLookupPlaceholder' => 'Cari/Pilih Akun Perkiraan...',
                'numberingOptions' => ['Transfer Bank'],
                'transferTitle' => 'Transfer Uang',
                'feeTitle' => 'Biaya Transfer',
                'infoTitle' => 'Info lainnya',
                'sectionTabs' => [
                    ['id' => 'details', 'label' => 'Transfer Uang', 'icon' => 'document'],
                    ['id' => 'fee', 'label' => 'Biaya Transfer', 'icon' => 'payment'],
                    ['id' => 'additional-info', 'label' => 'Info lainnya', 'icon' => 'info'],
                ],
                'dockActions' => [
                    [
                        'id' => 'save',
                        'label' => 'Simpan',
                        'icon' => 'save',
                        'tone' => 'primary',
                        'items' => [
                            ['id' => 'save-now', 'label' => 'Simpan'],
                            ['id' => 'save-new', 'label' => 'Simpan dan buat baru'],
                        ],
                    ],
                    [
                        'id' => 'document',
                        'label' => 'Form lain',
                        'icon' => 'document',
                        'tone' => 'secondary',
                        'items' => [
                            ['id' => 'open-document', 'label' => 'Buka dokumen terkait'],
                            ['id' => 'preview-document', 'label' => 'Preview dokumen'],
                        ],
                    ],
                    [
                        'id' => 'attachment',
                        'label' => 'Lampiran',
                        'icon' => 'paperclip',
                        'tone' => 'secondary',
                        'items' => [
                            ['id' => 'add-attachment', 'label' => 'Tambah lampiran'],
                            ['id' => 'manage-attachment', 'label' => 'Kelola lampiran'],
                        ],
                    ],
                    [
                        'id' => 'more',
                        'label' => 'Lainnya',
                        'icon' => 'kebab',
                        'tone' => 'success',
                        'items' => [
                            ['id' => 'duplicate-transaction', 'label' => 'Duplikasi transaksi'],
                            ['id' => 'mark-review', 'label' => 'Tandai untuk review'],
                        ],
                    ],
                    [
                        'id' => 'delete',
                        'label' => 'Hapus',
                        'icon' => 'trash',
                        'tone' => 'danger',
                    ],
                ],
                'draft' => [
                    'entryDate' => '25/04/2026',
                    'autoNumber' => true,
                    'numberingType' => 'Transfer Bank',
                    'documentNumber' => '',
                    'fromBankAccounts' => [],
                    'fromBranches' => ['JAKARTA'],
                    'exchangeRate' => '',
                    'exchangeRateLabel' => '',
                    'transferValue' => '',
                    'transferPrefix' => '',
                    'transferWords' => '',
                    'toBankAccounts' => [],
                    'toBranches' => ['JAKARTA'],
                    'resultValue' => '',
                    'resultPrefix' => '',
                    'resultWords' => '',
                    'notes' => '',
                    'feeRows' => [],
                    'fromTotalLabel' => 'Total',
                    'fromTotalValue' => '0',
                    'toTotalLabel' => 'Total',
                    'toTotalValue' => '0',
                    'saveTone' => 'primary',
                    'reconciliations' => [],
                ],
                'feeTable' => [
                    'columns' => [
                        ['id' => 'accountCode', 'label' => 'Akun', 'widthClassName' => 'w-[25%]'],
                        ['id' => 'accountName', 'label' => 'Nama Akun', 'widthClassName' => 'w-[25%]'],
                        ['id' => 'amount', 'label' => 'Nilai', 'widthClassName' => 'w-[25%]', 'align' => 'right'],
                        ['id' => 'chargedTo', 'label' => 'Dibebankan ke', 'widthClassName' => 'w-[25%]'],
                    ],
                    'emptyLabel' => 'Belum ada data',
                ],
                'table' => [
                    'createLabel' => 'Tambah Transfer Bank',
                    'refreshLabel' => 'Sinkron transfer bank',
                    'downloadLabel' => 'Unduh data transfer bank',
                    'printLabel' => 'Cetak transfer bank',
                    'settingsLabel' => 'Pengaturan tabel transfer bank',
                    'filterButtonLabel' => 'Filter lanjutan',
                    'searchPlaceholder' => 'Cari...',
                    'pageValue' => '6',
                    'downloadItems' => [
                        ['id' => 'download-excel', 'label' => 'Unduh Excel'],
                        ['id' => 'download-pdf', 'label' => 'Unduh PDF'],
                    ],
                    'settingsItems' => [
                        ['id' => 'arrange-columns', 'label' => 'Atur kolom'],
                        ['id' => 'export-transfer', 'label' => 'Ekspor transfer bank'],
                    ],
                    'filters' => [
                        [
                            'id' => 'date',
                            'rowKey' => 'dateFilter',
                            'options' => [
                                ['value' => 'all', 'label' => 'Tanggal: Semua'],
                                ['value' => '2016', 'label' => 'Tanggal: 2016'],
                            ],
                        ],
                        [
                            'id' => 'from-bank',
                            'rowKey' => 'fromBankFilter',
                            'options' => [
                                ['value' => 'all', 'label' => 'Dari Kas/Bank: Semua'],
                                ['value' => 'cash', 'label' => 'Dari Kas/Bank: Kas'],
                                ['value' => 'bank-bca', 'label' => 'Dari Kas/Bank: Bank BCA'],
                            ],
                        ],
                        [
                            'id' => 'to-bank',
                            'rowKey' => 'toBankFilter',
                            'options' => [
                                ['value' => 'all', 'label' => 'Ke Kas/Bank: Semua'],
                                ['value' => 'cash', 'label' => 'Ke Kas/Bank: Kas'],
                                ['value' => 'bank-bca', 'label' => 'Ke Kas/Bank: Bank BCA'],
                            ],
                        ],
                    ],
                    'columns' => [
                        ['id' => 'number', 'label' => 'Nomor #', 'widthClassName' => 'w-[190px]'],
                        ['id' => 'date', 'label' => 'Tanggal', 'widthClassName' => 'w-[120px]'],
                        ['id' => 'fromBank', 'label' => 'Bank (Keluar)', 'widthClassName' => 'w-[150px]'],
                        ['id' => 'toBank', 'label' => 'Bank (Masuk)', 'widthClassName' => 'w-[150px]'],
                        ['id' => 'description', 'label' => 'Keterangan', 'widthClassName' => 'w-[32%]'],
                        ['id' => 'transferTotal', 'label' => 'Total', 'widthClassName' => 'w-[150px]', 'align' => 'right'],
                        ['id' => 'purchasePayment', 'label' => 'Pembayaran Pembelian', 'widthClassName' => 'w-[220px]'],
                        ['id' => 'feeTotal', 'label' => 'Total', 'widthClassName' => 'w-[150px]', 'align' => 'right'],
                    ],
                    'rows' => [
                        ['id' => 'BT.2016.12.00006', 'number' => 'BT.2016.12.00006', 'date' => '16/12/2016', 'fromBank' => 'Bank BCA USD S...', 'fromBankFull' => 'Bank BCA USD Surabaya (247-878-6241)', 'toBank' => 'Bank BCA IDR Su...', 'toBankFull' => 'Bank BCA IDR Surabaya (388-308-3993)', 'description' => '', 'transferTotal' => '29,491,200', 'purchasePayment' => '', 'feeTotal' => '2,304', 'dateFilter' => '2016', 'fromBankFilter' => 'bank-bca', 'toBankFilter' => 'bank-bca', 'fromBranch' => 'JAKARTA', 'toBranch' => 'JAKARTA', 'exchangeRateLabel' => '1 USD=XXX IDR', 'exchangeRate' => '12,800', 'transferValue' => '2,304', 'transferPrefix' => 'USD', 'transferWords' => '# Dua ribu tiga ratus empat #', 'resultValue' => '29,491,200', 'resultPrefix' => 'IDR', 'resultWords' => '# Dua puluh sembilan juta empat ratus sembilan puluh satu ribu dua ratus #', 'fromTotalLabel' => 'Total Bank BCA USD Surabaya (24...', 'fromTotalValue' => '$ 2,304', 'toTotalLabel' => 'Total Bank BCA IDR Surabaya (388...', 'toTotalValue' => 'Rp 29,491,200', 'reconciliations' => [['id' => 'recon-a', 'bank' => 'Bank BCA USD Surabaya (247-878-6241)', 'status' => 'Belum', 'date' => ''], ['id' => 'recon-b', 'bank' => 'Bank BCA IDR Surabaya (388-308-3993)', 'status' => 'Ya', 'date' => '(11/02/2017)']]],
                        ['id' => 'BT.2016.12.00005', 'number' => 'BT.2016.12.00005', 'date' => '16/12/2016', 'fromBank' => 'Bank BCA USD J...', 'fromBankFull' => 'Bank BCA USD Jakarta', 'toBank' => 'Bank BCA IDR Ja...', 'toBankFull' => 'Bank BCA IDR Jakarta', 'description' => '', 'transferTotal' => '71,120,000', 'purchasePayment' => '', 'feeTotal' => '5,600', 'dateFilter' => '2016', 'fromBankFilter' => 'bank-bca', 'toBankFilter' => 'bank-bca', 'fromBranch' => 'JAKARTA', 'toBranch' => 'JAKARTA'],
                        ['id' => 'BT.2016.12.00004', 'number' => 'BT.2016.12.00004', 'date' => '16/12/2016', 'fromBank' => 'Kas Besar Kantor...', 'fromBankFull' => 'Kas Besar Kantor Jakarta', 'toBank' => 'Kas Kecil Kantor ...', 'toBankFull' => 'Kas Kecil Kantor Jakarta', 'description' => '', 'transferTotal' => '8,750,000', 'purchasePayment' => '', 'feeTotal' => '8,750,000', 'dateFilter' => '2016', 'fromBankFilter' => 'cash', 'toBankFilter' => 'cash', 'fromBranch' => 'JAKARTA', 'toBranch' => 'JAKARTA'],
                        ['id' => 'BT.2016.12.00003', 'number' => 'BT.2016.12.00003', 'date' => '16/12/2016', 'fromBank' => 'Bank BCA IDR Su...', 'fromBankFull' => 'Bank BCA IDR Surabaya', 'toBank' => 'Kas Besar Kantor...', 'toBankFull' => 'Kas Besar Kantor Surabaya', 'description' => '', 'transferTotal' => '11,200,000', 'purchasePayment' => '', 'feeTotal' => '11,200,000', 'dateFilter' => '2016', 'fromBankFilter' => 'bank-bca', 'toBankFilter' => 'cash', 'fromBranch' => 'JAKARTA', 'toBranch' => 'JAKARTA'],
                        ['id' => 'BT.2016.12.00002', 'number' => 'BT.2016.12.00002', 'date' => '16/12/2016', 'fromBank' => 'Kas Besar Kantor...', 'fromBankFull' => 'Kas Besar Kantor Jakarta', 'toBank' => 'Kas Kecil Kantor ...', 'toBankFull' => 'Kas Kecil Kantor Jakarta', 'description' => 'Transfer Uang', 'transferTotal' => '12,700,000', 'purchasePayment' => '', 'feeTotal' => '12,700,000', 'dateFilter' => '2016', 'fromBankFilter' => 'cash', 'toBankFilter' => 'cash', 'fromBranch' => 'JAKARTA', 'toBranch' => 'JAKARTA'],
                        ['id' => 'BT.2016.12.00001', 'number' => 'BT.2016.12.00001', 'date' => '16/12/2016', 'fromBank' => 'Bank BCA IDR Ja...', 'fromBankFull' => 'Bank BCA IDR Jakarta', 'toBank' => 'Kas Besar Kantor...', 'toBankFull' => 'Kas Besar Kantor Surabaya', 'description' => 'Transfer Untuk Gaji Nov 2016', 'transferTotal' => '127,500,000', 'purchasePayment' => '', 'feeTotal' => '127,500,000', 'dateFilter' => '2016', 'fromBankFilter' => 'bank-bca', 'toBankFilter' => 'cash', 'fromBranch' => 'JAKARTA', 'toBranch' => 'JAKARTA'],
                    ],
                ],
                'detailRecords' => [
                    'BT.2016.12.00006' => [
                        'entryDate' => '16/12/2016',
                        'autoNumber' => false,
                        'numberingType' => 'Transfer Bank',
                        'documentNumber' => 'BT.2016.12.00006',
                        'fromBankAccounts' => ['Bank BCA USD Surabaya (247-878-6241)'],
                        'fromBranches' => ['JAKARTA'],
                        'exchangeRateLabel' => '1 USD=XXX IDR',
                        'exchangeRate' => '12,800',
                        'transferValue' => '2,304',
                        'transferPrefix' => 'USD',
                        'transferWords' => '# Dua ribu tiga ratus empat #',
                        'toBankAccounts' => ['Bank BCA IDR Surabaya (388-308-3993)'],
                        'toBranches' => ['JAKARTA'],
                        'resultValue' => '29,491,200',
                        'resultPrefix' => 'IDR',
                        'resultWords' => '# Dua puluh sembilan juta empat ratus sembilan puluh satu ribu dua ratus #',
                        'notes' => '',
                        'feeRows' => [],
                        'fromTotalLabel' => 'Total Bank BCA USD Surabaya (24...',
                        'fromTotalValue' => '$ 2,304',
                        'toTotalLabel' => 'Total Bank BCA IDR Surabaya (388...',
                        'toTotalValue' => 'Rp 29,491,200',
                        'saveTone' => 'muted',
                        'reconciliations' => [
                            ['id' => 'transfer-recon-a', 'bank' => 'Bank BCA USD Surabaya (247-878-6241)', 'status' => 'Belum', 'date' => ''],
                            ['id' => 'transfer-recon-b', 'bank' => 'Bank BCA IDR Surabaya (388-308-3993)', 'status' => 'Ya', 'date' => '(11/02/2017)'],
                        ],
                    ],
                ],
            ],
        ];
    }
}
