<?php

namespace App\Support\Presentation\Blueprints;

class PageBlueprintRegistry
{
    public static function all(array $navigationPages, array $transactionTypeOptions = []): array
    {
        return [
            'users' => Pages\UsersPage::get(),
            'group-access' => Pages\GroupAccessPage::get(),
            'department' => Pages\DepartmentPage::get(),
            'currency-master' => Pages\CurrencyMasterPage::get(),
            'payment-terms' => Pages\PaymentTermsPage::get(),
            'period-end' => Pages\PeriodEndPage::get(),
            'budget-transfer' => Pages\BudgetTransferPage::get(),
            'budget' => Pages\BudgetPage::get(),
            'company-tax' => Pages\CompanyTaxPage::get(),
            'branch' => Pages\BranchPage::get(),
            'employees' => Pages\EmployeesPage::get(),
            'fob-master' => Pages\FobMasterPage::get(),
            'shipping-master' => Pages\ShippingMasterPage::get(),
            'contacts' => Pages\ContactsPage::get(),
            'favorite-transactions' => Pages\FavoriteTransactionsPage::get(),
            'recurring-transactions' => Pages\RecurringTransactionsPage::get(),
            'numbering' => Pages\NumberingPage::get(),
            'print-design' => Pages\PrintDesignPage::get(),
            'transaction-approval' => Pages\TransactionApprovalPage::get($transactionTypeOptions),
            'activity-log' => Pages\ActivityLogPage::get(),
            'preferences' => Pages\PreferencesPage::get(),
            'expense-entry' => Pages\ExpenseEntryPage::get($navigationPages),
            'accounts' => Pages\AccountsPage::get($navigationPages),
            'customers' => Pages\CustomersPage::get($navigationPages),
            'suppliers' => Pages\SuppliersPage::get($navigationPages),
            'sales-quote' => Pages\SalesQuotePage::get($navigationPages),
            'sales-deposit' => Pages\SalesDepositPage::get($navigationPages),
            'sales-receipt' => Pages\SalesReceiptPage::get($navigationPages),
            'sales-delivery' => Pages\SalesDeliveryPage::get($navigationPages),
            'sales-invoice' => Pages\SalesInvoicePage::get($navigationPages),
            'sales-order' => Pages\SalesOrderPage::get($navigationPages),
            'purchase-order' => Pages\PurchaseOrderPage::get($navigationPages),
            'purchase-deposit' => Pages\PurchaseDepositPage::get($navigationPages),
            'purchase-invoice' => Pages\PurchaseInvoicePage::get($navigationPages),
            'purchase-payment' => Pages\PurchasePaymentPage::get($navigationPages),
            'purchase-return' => Pages\PurchaseReturnPage::get($navigationPages),
            'supplier-price' => Pages\SupplierPricePage::get($navigationPages),
            'supplier-category' => Pages\SupplierCategoryPage::get($navigationPages),
            'payment-order' => Pages\PaymentOrderPage::get($navigationPages),
            'goods-receipt' => Pages\GoodsReceiptPage::get($navigationPages),
            'stock-transfer' => Pages\StockTransferPage::get($navigationPages),
            'work-order' => Pages\WorkOrderPage::get($navigationPages),
            'material-addition' => Pages\MaterialAdditionPage::get($navigationPages),
            'stock-opname-order' => Pages\StockOpnameOrderPage::get($navigationPages),
            'stock-opname-result' => Pages\StockOpnameResultPage::get($navigationPages),
            'item-request' => Pages\ItemRequestPage::get($navigationPages),
            'work-completion' => Pages\WorkCompletionPage::get($navigationPages),
            'order-fulfillment' => Pages\OrderFulfillmentPage::get($navigationPages),
            'fixed-assets' => Pages\FixedAssetsPage::get($navigationPages),
            'asset-category' => Pages\AssetCategoryPage::get($navigationPages),
            'asset-tax-category' => Pages\AssetTaxCategoryPage::get($navigationPages),
            'asset-disposal' => Pages\AssetDisposalPage::get($navigationPages),
            'asset-move' => Pages\AssetMovePage::get($navigationPages),
            'warehouse-master' => Pages\WarehouseMasterPage::get($navigationPages),
            'items-services' => Pages\ItemsServicesPage::get($navigationPages),
            'item-unit' => Pages\ItemUnitPage::get($navigationPages),
            'item-category' => Pages\ItemCategoryPage::get($navigationPages),
            'item-location' => Pages\ItemLocationPage::get($navigationPages),
            'minimum-stock' => Pages\MinimumStockPage::get($navigationPages),
            'customer-category' => Pages\CustomerCategoryPage::get($navigationPages),
            'sales-category' => Pages\SalesCategoryPage::get($navigationPages),
            'inventory-adjustment' => Pages\InventoryAdjustmentPage::get($navigationPages),
            'price-adjustment' => Pages\PriceAdjustmentPage::get($navigationPages),
            'sales-commission' => Pages\SalesCommissionPage::get($navigationPages),
            'sales-target' => Pages\SalesTargetPage::get($navigationPages),
            'sales-checkin' => Pages\SalesCheckinPage::get($navigationPages),
            'general-journal' => Pages\GeneralJournalPage::get($navigationPages),
            'cash-payment' => Pages\CashPaymentPage::get($navigationPages),
            'cash-receipt' => Pages\CashReceiptPage::get($navigationPages),
            'bank-transfer' => Pages\BankTransferPage::get($navigationPages),
            'budget-monitor' => Pages\BudgetMonitorPage::get($navigationPages),
            'journal-activity-log' => Pages\JournalActivityLogPage::get($navigationPages),
            'payroll-entry' => Pages\PayrollEntryPage::get(),
            'salary-allowance' => Pages\SalaryAllowancePage::get(),
        ];
    }
}
