export const filenameMapper = {
    'expense-entries': 'pencatatan-beban',
    'expense-entry': 'pencatatan-beban',
    'bank-transfers': 'transfer-bank',
    'bank-transfer': 'transfer-bank',
    'cash-payments': 'pembayaran-tunai',
    'cash-payment': 'pembayaran-tunai',
    'cash-receipts': 'penerimaan-tunai',
    'cash-receipt': 'penerimaan-tunai',
    'general-journals': 'jurnal-umum',
    'general-journal': 'jurnal-umum',
    'goods-receipts': 'penerimaan-barang',
    'goods-receipt': 'penerimaan-barang',
    'journal-activity-log': 'log-aktivitas',
    'journal-activity-logs': 'log-aktivitas',
    'payment-orders': 'permintaan-pembayaran',
    'payment-order': 'permintaan-pembayaran',
    'payroll-entries': 'pencatatan-gaji',
    'payroll-entry': 'pencatatan-gaji',
    'price-adjustments': 'penyesuaian-harga',
    'price-adjustment': 'penyesuaian-harga',
    'purchase-orders': 'pesanan-pembelian',
    'purchase-order': 'pesanan-pembelian',
    'sales-checkins': 'checkin-sales',
    'sales-checkin': 'checkin-sales',
    'supplier-prices': 'harga-pemasok',
    'supplier-price': 'harga-pemasok',
    'accounts': 'daftar-akun',
    'account': 'daftar-akun',
    'activity-log': 'log-aktivitas',
    'activity-logs': 'log-aktivitas',
    'asset-categories': 'kategori-aset',
    'asset-category': 'kategori-aset',
    'asset-disposals': 'disposisi-aset',
    'asset-disposal': 'disposisi-aset',
    'asset-moves': 'pemindahan-aset',
    'asset-move': 'pemindahan-aset',
    'asset-tax-categories': 'kategori-pajak-aset',
    'asset-tax-category': 'kategori-pajak-aset',
    'branches': 'cabang',
    'branch': 'cabang',
    'budget-monitors': 'monitoring-anggaran',
    'budget-monitor': 'monitoring-anggaran',
    'budgets': 'anggaran',
    'budget': 'anggaran',
    'budget-transfers': 'transfer-anggaran',
    'budget-transfer': 'transfer-anggaran',
    'company-taxes': 'pajak-perusahaan',
    'company-tax': 'pajak-perusahaan',
    'contacts': 'kontak',
    'contact': 'kontak',
    'currency-masters': 'mata-uang',
    'currency-master': 'mata-uang',
    'customer-categories': 'kategori-pelanggan',
    'customer-category': 'kategori-pelanggan',
    'customers': 'pelanggan',
    'customer': 'pelanggan',
    'departments': 'departemen',
    'department': 'departemen',
    'employees': 'karyawan',
    'employee': 'karyawan',
    'fixed-assets': 'aset-tetap',
    'fixed-asset': 'aset-tetap',
    'fob-masters': 'fob-master',
    'fob-master': 'fob-master',
    'group-accesses': 'akses-grup',
    'group-access': 'akses-grup',
    'inventory-adjustments': 'penyesuaian-persediaan',
    'inventory-adjustment': 'penyesuaian-persediaan',
    'item-categories': 'kategori-barang',
    'item-category': 'kategori-barang',
    'item-locations': 'lokasi-barang',
    'item-location': 'lokasi-barang',
    'item-requests': 'permintaan-barang',
    'item-request': 'permintaan-barang',
    'items-services': 'barang-dan-jasa',
    'items-service': 'barang-dan-jasa',
    'item-units': 'satuan-barang',
    'item-unit': 'satuan-barang',
    'material-additions': 'penambahan-bahan',
    'material-addition': 'penambahan-bahan',
    'minimum-stocks': 'stok-minimum',
    'minimum-stock': 'stok-minimum',
    'numberings': 'penomoran',
    'numbering': 'penomoran',
    'order-fulfillments': 'pemenuhan-pesanan',
    'order-fulfillment': 'pemenuhan-pesanan',
    'payment-terms': 'syarat-pembayaran',
    'payment-term': 'syarat-pembayaran',
    'period-ends': 'proses-akhir-bulan',
    'period-end': 'proses-akhir-bulan',
    'preferences': 'pengaturan',
    'preference': 'pengaturan',
    'print-designs': 'desain-cetak',
    'print-design': 'desain-cetak',
    'purchase-deposits': 'uang-muka-pembelian',
    'purchase-deposit': 'uang-muka-pembelian',
    'purchase-invoices': 'faktur-pembelian',
    'purchase-invoice': 'faktur-pembelian',
    'purchase-payments': 'pembayaran-pembelian',
    'purchase-payment': 'pembayaran-pembelian',
    'purchase-returns': 'retur-pembelian',
    'purchase-return': 'retur-pembelian',
    'recurring-transactions': 'transaksi-berulang',
    'recurring-transaction': 'transaksi-berulang',
    'salary-allowances': 'tunjangan-gaji',
    'salary-allowance': 'tunjangan-gaji',
    'sales-categories': 'kategori-penjualan',
    'sales-category': 'kategori-penjualan',
    'sales-commissions': 'komisi-penjualan',
    'sales-commission': 'komisi-penjualan',
    'sales-deliveries': 'pengiriman-penjualan',
    'sales-delivery': 'pengiriman-penjualan',
    'sales-deposits': 'uang-muka-penjualan',
    'sales-deposit': 'uang-muka-penjualan',
    'sales-invoices': 'faktur-penjualan',
    'sales-invoice': 'faktur-penjualan',
    'sales-orders': 'pesanan-penjualan',
    'sales-order': 'pesanan-penjualan',
    'sales-quotes': 'penawaran-penjualan',
    'sales-quote': 'penawaran-penjualan',
    'sales-receipts': 'penerimaan-penjualan',
    'sales-receipt': 'penerimaan-penjualan',
    'sales-targets': 'target-penjualan',
    'sales-target': 'target-penjualan',
    'shipping-masters': 'pengiriman',
    'shipping-master': 'pengiriman',
    'stock-opname-orders': 'perintah-stok-opname',
    'stock-opname-order': 'perintah-stok-opname',
    'stock-opname-results': 'hasil-stok-opname',
    'stock-opname-result': 'hasil-stok-opname',
    'stock-transfers': 'transfer-stok',
    'stock-transfer': 'transfer-stok',
    'supplier-categories': 'kategori-pemasok',
    'supplier-category': 'kategori-pemasok',
    'suppliers': 'pemasok',
    'supplier': 'pemasok',
    'transaction-approvals': 'persetujuan-transaksi',
    'transaction-approval': 'persetujuan-transaksi',
    'users': 'pengguna',
    'user': 'pengguna',
    'warehouse-masters': 'gudang',
    'warehouse-master': 'gudang',
    'work-completions': 'penyelesaian-kerja',
    'work-completion': 'penyelesaian-kerja',
    'work-orders': 'perintah-kerja',
    'work-order': 'perintah-kerja',
};

export const titleMapper = {
    'expense-entries': 'Pencatatan Beban',
    'expense-entry': 'Pencatatan Beban',
    'bank-transfers': 'Transfer Bank',
    'bank-transfer': 'Transfer Bank',
    'cash-payments': 'Pembayaran',
    'cash-payment': 'Pembayaran',
    'cash-receipts': 'Penerimaan Tunai',
    'cash-receipt': 'Penerimaan Tunai',
    'general-journals': 'Jurnal Umum',
    'general-journal': 'Jurnal Umum',
    'goods-receipts': 'Penerimaan Barang',
    'goods-receipt': 'Penerimaan Barang',
    'journal-activity-log': 'Log Aktivitas',
    'journal-activity-logs': 'Log Aktivitas',
    'payment-orders': 'Permintaan Pembayaran',
    'payment-order': 'Permintaan Pembayaran',
    'payroll-entries': 'Pencatatan Gaji',
    'payroll-entry': 'Pencatatan Gaji',
    'price-adjustments': 'Penyesuaian Harga',
    'price-adjustment': 'Penyesuaian Harga',
    'purchase-orders': 'Pesanan Pembelian',
    'purchase-order': 'Pesanan Pembelian',
    'sales-checkins': 'Check-in Sales',
    'sales-checkin': 'Check-in Sales',
    'supplier-prices': 'Harga Pemasok',
    'supplier-price': 'Harga Pemasok',
    'accounts': 'Daftar Akun',
    'account': 'Daftar Akun',
    'activity-log': 'Log Aktivitas',
    'activity-logs': 'Log Aktivitas',
    'asset-categories': 'Kategori Aset',
    'asset-category': 'Kategori Aset',
    'asset-disposals': 'Disposisi Aset',
    'asset-disposal': 'Disposisi Aset',
    'asset-moves': 'Pemindahan Aset',
    'asset-move': 'Pemindahan Aset',
    'asset-tax-categories': 'Kategori Pajak Aset',
    'asset-tax-category': 'Kategori Pajak Aset',
    'branches': 'Cabang',
    'branch': 'Cabang',
    'budget-monitors': 'Monitoring Anggaran',
    'budget-monitor': 'Monitoring Anggaran',
    'budgets': 'Anggaran',
    'budget': 'Anggaran',
    'budget-transfers': 'Transfer Anggaran',
    'budget-transfer': 'Transfer Anggaran',
    'company-taxes': 'Pajak',
    'company-tax': 'Pajak',
    'contacts': 'Kontak',
    'contact': 'Kontak',
    'currency-masters': 'Mata Oang',
    'currency-master': 'Mata Uang',
    'customer-categories': 'Kategori Pelanggan',
    'customer-category': 'Kategori Pelanggan',
    'customers': 'Pelanggan',
    'customer': 'Pelanggan',
    'departments': 'Departemen',
    'department': 'Departemen',
    'employees': 'Karyawan',
    'employee': 'Karyawan',
    'fixed-assets': 'Aset Tetap',
    'fixed-asset': 'Aset Tetap',
    'fob-masters': 'FOB Master',
    'fob-master': 'FOB Master',
    'group-accesses': 'Akses Grup',
    'group-access': 'Akses Grup',
    'inventory-adjustments': 'Penyesuaian Persediaan',
    'inventory-adjustment': 'Penyesuaian Persediaan',
    'item-categories': 'Kategori Barang',
    'item-category': 'Kategori Barang',
    'item-locations': 'Lokasi Barang',
    'item-location': 'Lokasi Barang',
    'item-requests': 'Permintaan Barang',
    'item-request': 'Permintaan Barang',
    'items-services': 'Barang dan Jasa',
    'items-service': 'Barang dan Jasa',
    'item-units': 'Satuan Barang',
    'item-unit': 'Satuan Barang',
    'material-additions': 'Penambahan Bahan',
    'material-addition': 'Penambahan Bahan',
    'minimum-stocks': 'Stok Minimum',
    'minimum-stock': 'Stok Minimum',
    'numberings': 'Penomoran',
    'numbering': 'Penomoran',
    'order-fulfillments': 'Pemenuhan Pesanan',
    'order-fulfillment': 'Pemenuhan Pesanan',
    'payment-terms': 'Syarat Pembayaran',
    'payment-term': 'Syarat Pembayaran',
    'period-ends': 'Proses Akhir Bulan',
    'period-end': 'Proses Akhir Bulan',
    'preferences': 'Pengaturan',
    'preference': 'Pengaturan',
    'print-designs': 'Desain Cetak',
    'print-design': 'Desain Cetak',
    'purchase-deposits': 'Uang Muka Pembelian',
    'purchase-deposit': 'Uang Muka Pembelian',
    'purchase-invoices': 'Faktur Pembelian',
    'purchase-invoice': 'Faktur Pembelian',
    'purchase-payments': 'Pembayaran Pembelian',
    'purchase-payment': 'Pembayaran Pembelian',
    'purchase-returns': 'Retur Pembelian',
    'purchase-return': 'Retur Pembelian',
    'recurring-transactions': 'Transaksi Berulang',
    'recurring-transaction': 'Transaksi Berulang',
    'salary-allowances': 'Tunjangan Gaji',
    'salary-allowance': 'Tunjangan Gaji',
    'sales-categories': 'Kategori Penjualan',
    'sales-category': 'Kategori Penjualan',
    'sales-commissions': 'Komisi Penjualan',
    'sales-commission': 'Komisi Penjualan',
    'sales-deliveries': 'Pengiriman Penjualan',
    'sales-delivery': 'Pengiriman Penjualan',
    'sales-deposits': 'Uang Muka Penjualan',
    'sales-deposit': 'Uang Muka Penjualan',
    'sales-invoices': 'Faktur Penjualan',
    'sales-invoice': 'Faktur Penjualan',
    'sales-orders': 'Pesanan Penjualan',
    'sales-order': 'Pesanan Penjualan',
    'sales-quotes': 'Penawaran Penjualan',
    'sales-quote': 'Penawaran Penjualan',
    'sales-receipts': 'Penerimaan Penjualan',
    'sales-receipt': 'Penerimaan Penjualan',
    'sales-targets': 'Target Penjualan',
    'sales-target': 'Target Penjualan',
    'shipping-masters': 'Pengiriman',
    'shipping-master': 'Pengiriman',
    'stock-opname-orders': 'Perintah Stok Opname',
    'stock-opname-order': 'Perintah Stok Opname',
    'stock-opname-results': 'Hasil Stok Opname',
    'stock-opname-result': 'Hasil Stok Opname',
    'stock-transfers': 'Transfer Stok',
    'stock-transfer': 'Transfer Stok',
    'supplier-categories': 'Kategori Pemasok',
    'supplier-category': 'Kategori Pemasok',
    'suppliers': 'Pemasok',
    'supplier': 'Pemasok',
    'transaction-approvals': 'Persetujuan Transaksi',
    'transaction-approval': 'Persetujuan Transaksi',
    'users': 'Pengguna',
    'user': 'Pengguna',
    'warehouse-masters': 'Gudang',
    'warehouse-master': 'Gudang',
    'work-completions': 'Penyelesaian Kerja',
    'work-completion': 'Penyelesaian Kerja',
    'work-orders': 'Perintah Kerja',
    'work-order': 'Perintah Kerja',
};
