const implementedWorkspacePageIds = new Set([
    'group-access',
    'accounts',
    'expense-entry',
    'general-journal',
    'activity-log',
    'currency-master',
    'bank-transfer',
    'bank-statement',
    'bank-history',
    'bank-reconciliation',
    'cash-payment',
    'cash-receipt',
    'department',
    'item-unit',
    'item-brand',
    'employees',
    'journal-activity-log',
    'salary-allowance',
    'sales-invoice',
    'sales-deposit',
    'sales-receipt',
    'sales-return',
    'inventory-adjustment',
    'price-adjustment',
    'sales-checkin',
    'purchase-invoice',
    'purchase-payment',
    'purchase-return',
    'item-request',
    'item-location',
    'minimum-stock',
    'delivery-order',
  // Modul aktif baru

    'payroll-entry',
    'items-services',
    'warehouse-master',
    'item-category',
    'supplier-price',
    'suppliers',
    'customers',
    'users',
    'preferences',
    'sales-commission',
]);

export default implementedWorkspacePageIds;
