export const currencyReferenceOptions = [
    { id: 'idr', name: 'Indonesian Rupiah', currencyCode: 'IDR', symbol: 'Rp', countryCode: 'ID' },
    { id: 'usd', name: 'US Dollar', currencyCode: 'USD', symbol: '$', countryCode: 'US' },
    { id: 'sgd', name: 'Singapore Dollar', currencyCode: 'SGD', symbol: '$', countryCode: 'SG' },
    { id: 'eur', name: 'Euro', currencyCode: 'EUR', symbol: 'EUR', countryCode: 'EU' },
    { id: 'gbp', name: 'British Pound Sterling', currencyCode: 'GBP', symbol: 'GBP', countryCode: 'GB' },
    { id: 'jpy', name: 'Japanese Yen', currencyCode: 'JPY', symbol: 'JPY', countryCode: 'JP' },
    { id: 'cny', name: 'Chinese Yuan', currencyCode: 'CNY', symbol: 'CNY', countryCode: 'CN' },
    { id: 'myr', name: 'Malaysian Ringgit', currencyCode: 'MYR', symbol: 'RM', countryCode: 'MY' },
    { id: 'thb', name: 'Thai Baht', currencyCode: 'THB', symbol: 'THB', countryCode: 'TH' },
    { id: 'vnd', name: 'Vietnamese Dong', currencyCode: 'VND', symbol: 'VND', countryCode: 'VN' },
    { id: 'php', name: 'Philippine Peso', currencyCode: 'PHP', symbol: '₱', countryCode: 'PH' },
    { id: 'aud', name: 'Australian Dollar', currencyCode: 'AUD', symbol: 'AUD', countryCode: 'AU' },
    { id: 'cad', name: 'Canadian Dollar', currencyCode: 'CAD', symbol: 'CAD', countryCode: 'CA' },
    { id: 'nzd', name: 'New Zealand Dollar', currencyCode: 'NZD', symbol: 'NZD', countryCode: 'NZ' },
    { id: 'chf', name: 'Swiss Franc', currencyCode: 'CHF', symbol: 'CHF', countryCode: 'CH' },
    { id: 'hkd', name: 'Hong Kong Dollar', currencyCode: 'HKD', symbol: 'HKD', countryCode: 'HK' },
    { id: 'krw', name: 'South Korean Won', currencyCode: 'KRW', symbol: 'KRW', countryCode: 'KR' },
    { id: 'inr', name: 'India Rupee', currencyCode: 'INR', symbol: '₹', countryCode: 'IN' },
    { id: 'npr', name: 'Nepal Rupee', currencyCode: 'NPR', symbol: 'रु', countryCode: 'NP' },
    { id: 'pkr', name: 'Pakistan Rupee', currencyCode: 'PKR', symbol: 'Rs', countryCode: 'PK' },
    { id: 'lkr', name: 'Sri Lanka Rupee', currencyCode: 'LKR', symbol: 'Rs', countryCode: 'LK' },
    { id: 'bdt', name: 'Bangladesh Taka', currencyCode: 'BDT', symbol: '৳', countryCode: 'BD' },
    { id: 'aed', name: 'UAE Dirham', currencyCode: 'AED', symbol: 'AED', countryCode: 'AE' },
    { id: 'sar', name: 'Saudi Riyal', currencyCode: 'SAR', symbol: 'SAR', countryCode: 'SA' },
];

export const countryReferenceOptions = [
    { id: 'id', name: 'Indonesia', countryCode: 'ID' },
    { id: 'sg', name: 'Singapore', countryCode: 'SG' },
    { id: 'my', name: 'Malaysia', countryCode: 'MY' },
    { id: 'th', name: 'Thailand', countryCode: 'TH' },
    { id: 'vn', name: 'Vietnam', countryCode: 'VN' },
    { id: 'ph', name: 'Philippines', countryCode: 'PH' },
    { id: 'cn', name: 'China', countryCode: 'CN' },
    { id: 'jp', name: 'Japan', countryCode: 'JP' },
    { id: 'kr', name: 'South Korea', countryCode: 'KR' },
    { id: 'in', name: 'India', countryCode: 'IN' },
    { id: 'np', name: 'Nepal', countryCode: 'NP' },
    { id: 'pk', name: 'Pakistan', countryCode: 'PK' },
    { id: 'lk', name: 'Sri Lanka', countryCode: 'LK' },
    { id: 'bd', name: 'Bangladesh', countryCode: 'BD' },
    { id: 'ae', name: 'United Arab Emirates', countryCode: 'AE' },
    { id: 'sa', name: 'Saudi Arabia', countryCode: 'SA' },
    { id: 'au', name: 'Australia', countryCode: 'AU' },
    { id: 'nz', name: 'New Zealand', countryCode: 'NZ' },
    { id: 'us', name: 'United States', countryCode: 'US' },
    { id: 'ca', name: 'Canada', countryCode: 'CA' },
    { id: 'gb', name: 'United Kingdom', countryCode: 'GB' },
    { id: 'de', name: 'Germany', countryCode: 'DE' },
    { id: 'fr', name: 'France', countryCode: 'FR' },
    { id: 'nl', name: 'Netherlands', countryCode: 'NL' },
    { id: 'ch', name: 'Switzerland', countryCode: 'CH' },
];
