export const currencyReferenceOptions = [
    { id: 'idr', name: 'Indonesian Rupiah', currencyCode: 'IDR', symbol: 'Rp', countryCode: 'ID' },
    { id: 'usd', name: 'US Dollar', currencyCode: 'USD', symbol: '$', countryCode: 'US' },
    { id: 'sgd', name: 'Singapore Dollar', currencyCode: 'SGD', symbol: '$', countryCode: 'SG' },
    { id: 'eur', name: 'Euro', currencyCode: 'EUR', symbol: 'EUR', countryCode: 'EU' },
    { id: 'gbp', name: 'British Pound Sterling', currencyCode: 'GBP', symbol: 'GBP', countryCode: 'GB' },
    { id: 'jpy', name: 'Japanese Yen', currencyCode: 'JPY', symbol: 'JPY', countryCode: 'JP' },
    { id: 'cny', name: 'Chinese Yuan', currencyCode: 'CNY', symbol: 'CNY', countryCode: 'CN' },
    { id: 'myr', name: 'Malaysian Ringgit', currencyCode: 'MYR', symbol: 'RM', countryCode: 'MY' },
    { id: 'thb', name: 'Thai Baht', currencyCode: 'THB', symbol: 'THB', countryCode: 'TH' },
    { id: 'vnd', name: 'Vietnamese Dong', currencyCode: 'VND', symbol: 'VND', countryCode: 'VN' },
    { id: 'php', name: 'Philippine Peso', currencyCode: 'PHP', symbol: '₱', countryCode: 'PH' },
    { id: 'aud', name: 'Australian Dollar', currencyCode: 'AUD', symbol: 'AUD', countryCode: 'AU' },
    { id: 'cad', name: 'Canadian Dollar', currencyCode: 'CAD', symbol: 'CAD', countryCode: 'CA' },
    { id: 'nzd', name: 'New Zealand Dollar', currencyCode: 'NZD', symbol: 'NZD', countryCode: 'NZ' },
    { id: 'chf', name: 'Swiss Franc', currencyCode: 'CHF', symbol: 'CHF', countryCode: 'CH' },
    { id: 'hkd', name: 'Hong Kong Dollar', currencyCode: 'HKD', symbol: 'HKD', countryCode: 'HK' },
    { id: 'krw', name: 'South Korean Won', currencyCode: 'KRW', symbol: 'KRW', countryCode: 'KR' },
    { id: 'inr', name: 'India Rupee', currencyCode: 'INR', symbol: '₹', countryCode: 'IN' },
    { id: 'npr', name: 'Nepal Rupee', currencyCode: 'NPR', symbol: 'रु', countryCode: 'NP' },
    { id: 'pkr', name: 'Pakistan Rupee', currencyCode: 'PKR', symbol: 'Rs', countryCode: 'PK' },
    { id: 'lkr', name: 'Sri Lanka Rupee', currencyCode: 'LKR', symbol: 'Rs', countryCode: 'LK' },
    { id: 'bdt', name: 'Bangladesh Taka', currencyCode: 'BDT', symbol: '৳', countryCode: 'BD' },
    { id: 'aed', name: 'UAE Dirham', currencyCode: 'AED', symbol: 'AED', countryCode: 'AE' },
    { id: 'sar', name: 'Saudi Riyal', currencyCode: 'SAR', symbol: 'SAR', countryCode: 'SA' },
];

export const countryReferenceOptions = [
    { id: 'id', name: 'Indonesia', countryCode: 'ID' },
    { id: 'sg', name: 'Singapore', countryCode: 'SG' },
    { id: 'my', name: 'Malaysia', countryCode: 'MY' },
    { id: 'th', name: 'Thailand', countryCode: 'TH' },
    { id: 'vn', name: 'Vietnam', countryCode: 'VN' },
    { id: 'ph', name: 'Philippines', countryCode: 'PH' },
    { id: 'cn', name: 'China', countryCode: 'CN' },
    { id: 'jp', name: 'Japan', countryCode: 'JP' },
    { id: 'kr', name: 'South Korea', countryCode: 'KR' },
    { id: 'in', name: 'India', countryCode: 'IN' },
    { id: 'np', name: 'Nepal', countryCode: 'NP' },
    { id: 'pk', name: 'Pakistan', countryCode: 'PK' },
    { id: 'lk', name: 'Sri Lanka', countryCode: 'LK' },
    { id: 'bd', name: 'Bangladesh', countryCode: 'BD' },
    { id: 'ae', name: 'United Arab Emirates', countryCode: 'AE' },
    { id: 'sa', name: 'Saudi Arabia', countryCode: 'SA' },
    { id: 'au', name: 'Australia', countryCode: 'AU' },
    { id: 'nz', name: 'New Zealand', countryCode: 'NZ' },
    { id: 'us', name: 'United States', countryCode: 'US' },
    { id: 'ca', name: 'Canada', countryCode: 'CA' },
    { id: 'gb', name: 'United Kingdom', countryCode: 'GB' },
    { id: 'de', name: 'Germany', countryCode: 'DE' },
    { id: 'fr', name: 'France', countryCode: 'FR' },
    { id: 'nl', name: 'Netherlands', countryCode: 'NL' },
    { id: 'ch', name: 'Switzerland', countryCode: 'CH' },
];

export const taxUnitReferenceOptions = [
    { id: 'UM.0001', code: 'UM.0001', label: 'Metrik Ton' },
    { id: 'UM.0002', code: 'UM.0002', label: 'Wet Ton' },
    { id: 'UM.0003', code: 'UM.0003', label: 'Kilogram' },
    { id: 'UM.0004', code: 'UM.0004', label: 'Gram' },
    { id: 'UM.0005', code: 'UM.0005', label: 'Karat' },
    { id: 'UM.0006', code: 'UM.0006', label: 'Kiloliter' },
    { id: 'UM.0007', code: 'UM.0007', label: 'Liter' },
    { id: 'UM.0008', code: 'UM.0008', label: 'Barrel' },
    { id: 'UM.0009', code: 'UM.0009', label: 'MMBTU' },
    { id: 'UM.0010', code: 'UM.0010', label: 'Ampere' },
    { id: 'UM.0011', code: 'UM.0011', label: 'Sentimeter Kubik' },
    { id: 'UM.0012', code: 'UM.0012', label: 'Meter Persegi' },
    { id: 'UM.0013', code: 'UM.0013', label: 'Meter' },
    { id: 'UM.0014', code: 'UM.0014', label: 'Inches' },
    { id: 'UM.0015', code: 'UM.0015', label: 'Sentimeter' },
    { id: 'UM.0016', code: 'UM.0016', label: 'Yard' },
    { id: 'UM.0017', code: 'UM.0017', label: 'Lusin' },
    { id: 'UM.0018', code: 'UM.0018', label: 'Unit' },
    { id: 'UM.0019', code: 'UM.0019', label: 'Set' },
    { id: 'UM.0020', code: 'UM.0020', label: 'Lembar' },
    { id: 'UM.0021', code: 'UM.0021', label: 'Piece' },
    { id: 'UM.0022', code: 'UM.0022', label: 'Boks' },
    { id: 'UM.0023', code: 'UM.0023', label: 'Tahun' },
    { id: 'UM.0024', code: 'UM.0024', label: 'Bulan' },
    { id: 'UM.0025', code: 'UM.0025', label: 'Minggu' },
    { id: 'UM.0026', code: 'UM.0026', label: 'Hari' },
    { id: 'UM.0027', code: 'UM.0027', label: 'Jam' },
    { id: 'UM.0028', code: 'UM.0028', label: 'Menit' },
    { id: 'UM.0029', code: 'UM.0029', label: 'Persen' },
    { id: 'UM.0030', code: 'UM.0030', label: 'Kegiatan' },
    { id: 'UM.0031', code: 'UM.0031', label: 'Laporan' },
    { id: 'UM.0032', code: 'UM.0032', label: 'Bahan' },
    { id: 'UM.0033', code: 'UM.0033', label: 'Other' },
    { id: 'UM.0034', code: 'UM.0034', label: 'Meter Kubik' },
    { id: 'UM.0035', code: 'UM.0035', label: 'Sentimeter Persegi' },
    { id: 'UM.0036', code: 'UM.0036', label: 'Drum' },
    { id: 'UM.0037', code: 'UM.0037', label: 'Karton' },
    { id: 'UM.0038', code: 'UM.0038', label: 'Kwh' },
    { id: 'UM.0039', code: 'UM.0039', label: 'Roll' }
];
