import {
    ArrowRightLeft,
    BadgeDollarSign,
    BarChart3,
    BookUser,
    Bot,
    Boxes,
    BoxIcon,
    Building2,
    CalendarDays,
    CircleAlert,
    ContactRound,
    EllipsisVertical,
    FileText,
    FileCheck,
    Info,
    FormInput,
    GitBranch,
    Hash,
    History,
    Landmark,
    LayoutGrid,
    Lightbulb,
    Link2,
    ListMinus,
    MapPin,
    MapPinCheckInside,
    NotebookText,
    Package,
    Package2,
    Printer,
    Receipt,
    ReceiptText,
    Repeat,
    Save,
    Settings,
    ShoppingCart,
    Star,
    Store,
    Tags,
    TriangleAlert,
    Trash2,
    Truck,
    UserRound,
    UsersRound,
    Wallet,
} from 'lucide-react';

const iconMap = {
    settings: Settings,
    building: Building2,
    ledger: NotebookText,
    bank: Landmark,
    sales: Store,
    purchase: ShoppingCart,
    inventory: BoxIcon,
    asset: Boxes,
    tax: ReceiptText,
    reports: BarChart3,
    group: UsersRound,
    users: UserRound,
    numbering: Hash,
    printer: Printer,
    store: Store,
    currency: BadgeDollarSign,
    branch: GitBranch,
    department: Building2,
    terms: FileCheck,
    truck: Truck,
    salary: Wallet,
    employee: UserRound,
    recurring: Repeat,
    calendar: CalendarDays,
    contact: ContactRound,
    favorite: Star,
    activity: History,
    account: NotebookText,
    expense: ListMinus,
    journal: NotebookText,
    budget: BarChart3,
    transfer: ArrowRightLeft,
    payment: BadgeDollarSign,
    receipt: Receipt,
    invoice: FileText,
    category: Tags,
    smartlink: Link2,
    checkin: MapPinCheckInside,
    warehouse: Boxes,
    unit: Package2,
    brand: BookUser,
    stock: Package,
    box: BoxIcon,
    location: MapPin,
    ai: Bot,
    format: LayoutGrid,
    form: FormInput,
    restriction: CircleAlert,
    alert: TriangleAlert,
    supplier: ContactRound,
    customer: ContactRound,
    retail: Store,
    trade: ShoppingCart,
    manufacture: Boxes,
    save: Save,
    kebab: EllipsisVertical,
    trash: Trash2,
    delete: Trash2,
    document: FileText,
    info: Info,
    idea: Lightbulb,
    link: Link2,
};

export default function NavigationIcon({ type, className = 'h-6 w-6', strokeWidth = 1.45 }) {
    const Icon = iconMap[type] ?? FormInput;

    return <Icon aria-hidden="true" className={className} strokeWidth={strokeWidth} absoluteStrokeWidth />;
}
