import {
    ArrowRightLeft,
    BadgeDollarSign,
    BarChart3,
    BookUser,
    Bot,
    Boxes,
    BoxIcon,
    Building2,
    CalendarDays,
    CircleAlert,
    ContactRound,
    EllipsisVertical,
    FileText,
    FileCheck,
    Info,
    FormInput,
    GitBranch,
    Hash,
    History,
    Landmark,
    LayoutGrid,
    Lightbulb,
    Link2,
    ListMinus,
    MapPin,
    MapPinCheckInside,
    NotebookText,
    Package,
    Package2,
    Printer,
    Receipt,
    ReceiptText,
    Repeat,
    Save,
    Settings,
    ShoppingCart,
    Star,
    Store,
    Tags,
    TriangleAlert,
    Trash2,
    Truck,
    UserRound,
    UsersRound,
    Wallet,
} from 'lucide-react';

import {
    AccountsModuleIcon,
    ActivityLogModuleIcon,
    CashBankModuleIcon,
    CustomersModuleIcon,
    EmployeesModuleIcon,
    GeneralJournalModuleIcon,
    GeneralLedgerModuleIcon,
    GroupAccessModuleIcon,
    InventoryAdjustmentModuleIcon,
    InventoryModuleIcon,
    ItemCategoryModuleIcon,
    ItemLocationModuleIcon,
    ItemsServicesModuleIcon,
    ItemUnitModuleIcon,
    JournalActivityLogModuleIcon,
    MinimumStockModuleIcon,
    PayrollModuleIcon,
    PurchaseDepositModuleIcon,
    PurchaseInvoiceModuleIcon,
    PurchasePaymentModuleIcon,
    PurchaseReturnModuleIcon,
    PurchasesModuleIcon,
    SalaryAllowanceModuleIcon,
    SalesDepositModuleIcon,
    SalesInvoiceModuleIcon,
    SalesModuleIcon,
    SalesReceiptModuleIcon,
    SalesReturnModuleIcon,
    StoreModuleIcon,
    SuppliersModuleIcon,
    WarehouseMasterModuleIcon,
} from '@/features/workspace/navigation/ModuleCustomIcons';

const iconMap = {
    settings: Settings,
    company: StoreModuleIcon,
    store: StoreModuleIcon,
    building: StoreModuleIcon,
    toko: StoreModuleIcon,
    'general-ledger': GeneralLedgerModuleIcon,
    ledger: GeneralLedgerModuleIcon,
    'buku-besar': GeneralLedgerModuleIcon,
    bank: CashBankModuleIcon,
    'cash-bank': CashBankModuleIcon,
    sales: SalesModuleIcon,
    penjualan: SalesModuleIcon,
    purchases: PurchasesModuleIcon,
    purchase: PurchasesModuleIcon,
    pembelian: PurchasesModuleIcon,
    inventory: InventoryModuleIcon,
    persediaan: InventoryModuleIcon,
    asset: Boxes,
    tax: ReceiptText,
    reports: BarChart3,
    group: GroupAccessModuleIcon,
    'group-access': GroupAccessModuleIcon,
    users: UserRound,
    numbering: Hash,
    printer: Printer,
    currency: BadgeDollarSign,
    branch: GitBranch,
    department: Building2,
    terms: FileCheck,
    truck: Truck,
    salary: PayrollModuleIcon,
    payroll: PayrollModuleIcon,
    'payroll-entry': PayrollModuleIcon,
    'salary-allowance': SalaryAllowanceModuleIcon,
    employee: EmployeesModuleIcon,
    employees: EmployeesModuleIcon,
    recurring: Repeat,
    calendar: CalendarDays,
    contact: ContactRound,
    favorite: Star,
    activity: ActivityLogModuleIcon,
    'activity-log': ActivityLogModuleIcon,
    'journal-activity-log': JournalActivityLogModuleIcon,
    'journal-activity': JournalActivityLogModuleIcon,
    account: AccountsModuleIcon,
    accounts: AccountsModuleIcon,
    expense: ListMinus,
    journal: GeneralJournalModuleIcon,
    'general-journal': GeneralJournalModuleIcon,
    budget: BarChart3,
    transfer: ArrowRightLeft,
    payment: BadgeDollarSign,
    receipt: Receipt,
    invoice: FileText,
    'sales-deposit': SalesDepositModuleIcon,
    'sales-invoice': SalesInvoiceModuleIcon,
    'sales-receipt': SalesReceiptModuleIcon,
    'sales-return': SalesReturnModuleIcon,
    'purchase-deposit': PurchaseDepositModuleIcon,
    'purchase-invoice': PurchaseInvoiceModuleIcon,
    'purchase-payment': PurchasePaymentModuleIcon,
    'purchase-return': PurchaseReturnModuleIcon,
    category: ItemCategoryModuleIcon,
    'item-category': ItemCategoryModuleIcon,
    smartlink: Link2,
    checkin: MapPinCheckInside,
    warehouse: WarehouseMasterModuleIcon,
    'warehouse-master': WarehouseMasterModuleIcon,
    unit: ItemUnitModuleIcon,
    'item-unit': ItemUnitModuleIcon,
    brand: BookUser,
    stock: InventoryAdjustmentModuleIcon,
    'inventory-adjustment': InventoryAdjustmentModuleIcon,
    box: ItemsServicesModuleIcon,
    item: ItemsServicesModuleIcon,
    'items-services': ItemsServicesModuleIcon,
    location: ItemLocationModuleIcon,
    'item-location': ItemLocationModuleIcon,
    'minimum-stock': MinimumStockModuleIcon,
    ai: Bot,
    format: LayoutGrid,
    form: FormInput,
    restriction: CircleAlert,
    alert: TriangleAlert,
    supplier: SuppliersModuleIcon,
    suppliers: SuppliersModuleIcon,
    customer: CustomersModuleIcon,
    customers: CustomersModuleIcon,
    retail: Store,
    trade: ShoppingCart,
    manufacture: Boxes,
    save: Save,
    kebab: EllipsisVertical,
    trash: Trash2,
    delete: Trash2,
    document: FileText,
    info: Info,
    idea: Lightbulb,
    link: Link2,
};

export default function NavigationIcon({ type, className = 'h-6 w-6', strokeWidth = 1.45 }) {
    const Icon = iconMap[type] ?? FormInput;

    return <Icon aria-hidden="true" className={className} strokeWidth={strokeWidth} absoluteStrokeWidth />;
}
