export function buildDetailRecordFromRow(row = {}, config) {
    return {
        entryDate: row.date ?? '',
        autoNumber: false,
        numberingType: config.numberingOptions?.[0] ?? '',
        documentNumber: row.number ?? '',
        fromBankAccounts: row.fromBankFull ? [row.fromBankFull] : [],
        fromBranches: row.fromBranch ? [row.fromBranch] : ['JAKARTA'],
        exchangeRate: row.exchangeRate ?? '',
        exchangeRateLabel: row.exchangeRateLabel ?? '',
        transferValue: row.transferValue ?? '',
        transferPrefix: row.transferPrefix ?? '',
        transferWords: row.transferWords ?? '',
        toBankAccounts: row.toBankFull ? [row.toBankFull] : [],
        toBranches: row.toBranch ? [row.toBranch] : ['JAKARTA'],
        resultValue: row.resultValue ?? '',
        resultPrefix: row.resultPrefix ?? '',
        resultWords: row.resultWords ?? '',
        notes: row.description ?? '',
        feeLookup: '',
        feeRows: row.feeRows ?? [],
        fromTotalLabel: row.fromTotalLabel ?? config.draft?.fromTotalLabel ?? 'Total',
        fromTotalValue: row.fromTotalValue ?? '0',
        toTotalLabel: row.toTotalLabel ?? config.draft?.toTotalLabel ?? 'Total',
        toTotalValue: row.toTotalValue ?? '0',
        saveTone: 'muted',
        reconciliations: row.reconciliations ?? [],
    };
}

export function buildFormState(source = {}, config) {
    return {
        entryDate: source.entryDate ?? config.draft?.entryDate ?? '',
        autoNumber: source.autoNumber ?? config.draft?.autoNumber ?? true,
        numberingType: source.numberingType ?? config.draft?.numberingType ?? '',
        documentNumber: source.documentNumber ?? config.draft?.documentNumber ?? '',
        fromBankAccounts: [...(source.fromBankAccounts ?? config.draft?.fromBankAccounts ?? [])],
        fromBranches: [...(source.fromBranches ?? config.draft?.fromBranches ?? [])],
        exchangeRate: source.exchangeRate ?? config.draft?.exchangeRate ?? '',
        exchangeRateLabel: source.exchangeRateLabel ?? config.draft?.exchangeRateLabel ?? '',
        transferValue: source.transferValue ?? config.draft?.transferValue ?? '',
        transferPrefix: source.transferPrefix ?? config.draft?.transferPrefix ?? '',
        transferWords: source.transferWords ?? config.draft?.transferWords ?? '',
        toBankAccounts: [...(source.toBankAccounts ?? config.draft?.toBankAccounts ?? [])],
        toBranches: [...(source.toBranches ?? config.draft?.toBranches ?? [])],
        resultValue: source.resultValue ?? config.draft?.resultValue ?? '',
        resultPrefix: source.resultPrefix ?? config.draft?.resultPrefix ?? '',
        resultWords: source.resultWords ?? config.draft?.resultWords ?? '',
        notes: source.notes ?? config.draft?.notes ?? '',
        feeLookup: source.feeLookup ?? '',
        feeRows: [...(source.feeRows ?? config.draft?.feeRows ?? [])],
        fromTotalLabel: source.fromTotalLabel ?? config.draft?.fromTotalLabel ?? 'Total',
        fromTotalValue: source.fromTotalValue ?? config.draft?.fromTotalValue ?? '0',
        toTotalLabel: source.toTotalLabel ?? config.draft?.toTotalLabel ?? 'Total',
        toTotalValue: source.toTotalValue ?? config.draft?.toTotalValue ?? '0',
        saveTone: source.saveTone ?? config.draft?.saveTone ?? 'primary',
        reconciliations: [...(source.reconciliations ?? config.draft?.reconciliations ?? [])],
    };
}
