<?php

namespace App\Support\Backend;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;

class BackendResourceWriter
{
    public function __construct(
        protected BackendActivityLogger $activityLogger,
    ) {
    }

    /**
     * @param  array<string, mixed>  $payload
     */
    public function create(BackendResourceBlueprint $blueprint, array $payload): Model
    {
        $modelClass = $blueprint->modelClass();

        /** @var Model $record */
        $record = new $modelClass();

        return $this->persist($blueprint, $record, $payload);
    }

    /**
     * @param  array<string, mixed>  $payload
     */
    public function update(BackendResourceBlueprint $blueprint, Model $record, array $payload): Model
    {
        return $this->persist($blueprint, $record, $payload);
    }

    public function delete(BackendResourceBlueprint $blueprint, Model $record): void
    {
        DB::transaction(function () use ($blueprint, $record): void {
            if ($blueprint->key !== 'period-ends' && $record instanceof \App\Domain\Support\Models\OperationDocument) {
                if ($record->entry_date && $this->isPeriodClosed($record->entry_date)) {
                    $formattedDate = \Carbon\Carbon::parse($record->entry_date)->format('d/m/Y');
                    throw \Illuminate\Validation\ValidationException::withMessages([
                        'entry_date' => ["Transaksi tidak dapat dihapus karena periode tanggal tersebut ({$formattedDate}) sudah ditutup oleh Proses Akhir Bulan."]
                    ]);
                }
            }

            $costingKeys = [
                'goods-receipts',
                'sales-deliveries',
                'sales-returns',
                'purchase-returns',
                'inventory-adjustments',
                'work-completions',
                'material-additions',
                'stock-transfers',
                'stock-opname-results',
            ];
            if (in_array($blueprint->key, $costingKeys)) {
                $this->revertCosting($record);
            }

            $before = $this->activityLogger->snapshot($record);

            if ($blueprint->key === 'cash-payments' && $record->related_document_id) {
                $relatedDoc = \App\Domain\Support\Models\OperationDocument::find($record->related_document_id);
                if ($relatedDoc) {
                    $relatedDoc->update([
                        'status' => 'Sedang diproses',
                        'paid_amount' => 0.00,
                    ]);
                }
            }

            // Hapus jurnal otomatis terkait jika ada
            \App\Domain\Support\Models\OperationDocument::where('document_type', 'general_journal')
                ->where('related_document_id', $record->id)
                ->delete();

            $oldDocs = [];
            if (in_array($blueprint->key, ['sales-receipts', 'purchase-payments']) && method_exists($record, 'lines')) {
                $oldDocs = $record->lines()->pluck('reference_code')->filter()->unique()->toArray();
            }

            $oldDepositIds = [];
            if ($blueprint->key === 'sales-invoices' && $record->metadata && isset($record->metadata['advance_payments'])) {
                foreach ($record->metadata['advance_payments'] as $adv) {
                    if (isset($adv['__depositId'])) {
                        $oldDepositIds[] = (int) $adv['__depositId'];
                    }
                }
            }

            $record->delete();

            if ($blueprint->key === 'sales-invoices' && !empty($oldDepositIds)) {
                $this->reconcileSalesDeposits($record, $oldDepositIds);
            }

            $this->activityLogger->logMutation(
                $blueprint,
                'delete',
                $record,
                $before,
                null,
            );

            // Invalidate dashboard caches on mutation
            $this->invalidateDashboardCache();

            // Reconcile payment status on delete
            $this->reconcilePayments($blueprint, $record, $oldDocs);
        });
    }

    protected function persist(BackendResourceBlueprint $blueprint, Model $record, array $payload): Model
    {
        return DB::transaction(function () use ($blueprint, $record, $payload): Model {
            // 0. Auto-numbering sequential generation
            if (!$record->exists && is_subclass_of($blueprint->modelClass(), \App\Domain\Support\Models\OperationDocument::class)) {
                $docNumber = $payload['document_number'] ?? '';
                if (empty($docNumber) || $this->isAutoGeneratedNumber($docNumber, $blueprint->key)) {
                    $payload['document_number'] = $this->generateNextSequentialNumber($blueprint->key, $payload['entry_date'] ?? null);
                }
            }

            // 1. Validasi Periode Ditutup (Period Lock)
            if ($blueprint->key !== 'period-ends' && is_subclass_of($blueprint->modelClass(), \App\Domain\Support\Models\OperationDocument::class)) {
                $targetDate = $payload['entry_date'] ?? ($record->exists ? $record->entry_date : null);
                if ($targetDate && $this->isPeriodClosed($targetDate)) {
                    $formattedDate = \Carbon\Carbon::parse($targetDate)->format('d/m/Y');
                    throw \Illuminate\Validation\ValidationException::withMessages([
                        'entry_date' => ["Transaksi tidak dapat disimpan karena periode untuk tanggal tersebut ({$formattedDate}) sudah ditutup oleh Proses Akhir Bulan."]
                    ]);
                }
            }

            // 2. Rekalkulasi & Validasi Total di Sisi Backend (Price/Total Manipulation Protection)
            if ($blueprint->key !== 'period-ends' && is_subclass_of($blueprint->modelClass(), \App\Domain\Support\Models\OperationDocument::class)) {
                $itemKeys = [
                    'sales-invoices', 'sales-orders', 'sales-quotes', 'sales-deliveries', 'sales-returns',
                    'purchase-invoices', 'purchase-orders', 'purchase-returns', 'goods-receipts',
                    'inventory-adjustments', 'work-orders', 'material-additions', 'work-completions',
                    'stock-transfers', 'delivery-orders', 'asset-changes', 'asset-disposals', 'asset-moves',
                    'item-requests', 'price-adjustments',
                ];
                if (in_array($blueprint->key, $itemKeys) && isset($payload['lines']) && is_array($payload['lines'])) {
                    $subtotal = 0.0;
                    $discountTotal = 0.0;
                    $taxTotal = 0.0;

                    foreach ($payload['lines'] as &$line) {
                        $qty = (float)($line['quantity'] ?? 0.0);
                        $price = (float)($line['unit_price'] ?? 0.0);
                        $discount = (float)($line['discount_amount'] ?? 0.0);

                        $lineTotal = max(0.0, ($qty * $price) - $discount);
                        $line['total_amount'] = $lineTotal;

                        $subtotal += $lineTotal;
                        $discountTotal += $discount;
                    }
                    unset($line);

                    $taxId = $payload['tax_id'] ?? null;
                    if ($taxId) {
                        $taxTotal = max(0.0, ($subtotal - $discountTotal) * 0.1);
                    }

                    $totalAmount = max(0.0, $subtotal - $discountTotal + $taxTotal);

                    $payload['subtotal'] = $subtotal;
                    $payload['discount_total'] = $discountTotal;
                    $payload['tax_total'] = $taxTotal;
                    $payload['total_amount'] = $totalAmount;
                }
            }

            // Validasi logika bisnis
            if ($blueprint->key === 'general-journals') {
                $lines = $payload['lines'] ?? [];
                $totalDebit = 0;
                $totalCredit = 0;
                foreach ($lines as $line) {
                    $totalDebit += (float) ($line['debit_amount'] ?? 0);
                    $totalCredit += (float) ($line['credit_amount'] ?? 0);
                }
                if (abs($totalDebit - $totalCredit) > 0.001) {
                    throw \Illuminate\Validation\ValidationException::withMessages([
                        'lines' => ['Total Debet harus sama dengan Total Kredit (Jurnal Umum harus seimbang / balance).']
                    ]);
                }
            }

            if ($blueprint->key === 'sales-invoices') {
                $advancePayments = $payload['metadata']['advance_payments'] ?? [];
                $totalAdvance = 0.0;
                foreach ($advancePayments as $adv) {
                    $amt = $adv['amount'] ?? 0;
                    if (is_string($amt)) {
                        $amt = (float) preg_replace('/[^\d]/', '', $amt);
                    }
                    $totalAdvance += (float) $amt;
                }

                $totalInvoice = (float) ($payload['total_amount'] ?? 0.0);
                if ($totalAdvance > $totalInvoice) {
                    throw \Illuminate\Validation\ValidationException::withMessages([
                        'advance_payments' => ["Total alokasi Uang Muka tidak boleh melebihi Total Faktur Penjualan (Total Uang Muka: Rp " . number_format($totalAdvance, 0, ',', '.') . ", Total Faktur: Rp " . number_format($totalInvoice, 0, ',', '.') . ")."]
                    ]);
                }

                $invoiceTaxId = $payload['tax_id'] ?? null;
                foreach ($advancePayments as $adv) {
                    $depositId = $adv['__depositId'] ?? null;
                    if ($depositId) {
                        $deposit = DB::table('operation_documents')->where('id', $depositId)->first();
                        if ($deposit && $deposit->tax_id && !$invoiceTaxId) {
                            throw \Illuminate\Validation\ValidationException::withMessages([
                                'tax_id' => ["Uang Muka [{$deposit->document_number}] menggunakan Pajak (PPN). Faktur Penjualan ini juga wajib mengenakan Pajak (PPN) agar dapat menggunakan uang muka tersebut."]
                            ]);
                        }
                    }
                }

                $ignoreStockWarning = filter_var($payload['metadata']['ignore_stock_warning'] ?? false, FILTER_VALIDATE_BOOLEAN);

                if (!$ignoreStockWarning) {
                    $warehouseId = $payload['warehouse_id'] ?? null;
                    if ($warehouseId) {
                        $lines = $payload['lines'] ?? [];
                        foreach ($lines as $index => $line) {
                            $productId = $line['product_id'] ?? null;
                            $qtyRequested = (float) ($line['quantity'] ?? 0);
                            if ($productId && $qtyRequested > 0) {
                                $stockMap = app(\App\Support\Backend\Queries\InventoryInquiryQueryService::class)->paginateItemLocations([
                                    'product_id' => $productId,
                                    'warehouse_id' => $warehouseId,
                                    'per_page' => 1,
                                ]);
                                
                                $qtyAvailable = 0.0;
                                if (count($stockMap->items()) > 0) {
                                    $item = $stockMap->items()[0];
                                    $qtyAvailable = (float) ($item['saleable_stock'] ?? 0.0);
                                }
                                
                                if ($qtyRequested > $qtyAvailable) {
                                    $productName = DB::table('products')->where('id', $productId)->value('name') ?? 'Barang';
                                    $warehouseName = DB::table('warehouses')->where('id', $warehouseId)->value('name') ?? 'Utama';
                                    throw \Illuminate\Validation\ValidationException::withMessages([
                                        'stock_warning' => [
                                            'product_name' => $productName,
                                            'warehouse_name' => $warehouseName,
                                        ]
                                    ]);
                                }
                            }
                        }
                    }
                }
            }

            // Validasi lampiran wajib
            $blueprintToPreferenceMap = [
                'sales-quotes' => 'attachments-sales-quote',
                'sales-orders' => 'attachments-sales-order',
                'sales-deliveries' => 'attachments-sales-delivery',
                'sales-invoices' => 'attachments-sales-invoice',
                'sales-receipts' => 'attachments-sales-receipt',
                'sales-returns' => 'attachments-sales-return',
                'price-adjustments' => 'attachments-sales-discount',
                'purchase-orders' => 'attachments-purchase-order',
                'goods-receipts' => 'attachments-purchase-receipt',
                'purchase-invoices' => 'attachments-purchase-invoice',
                'purchase-payments' => 'attachments-purchase-payment',
                'purchase-returns' => 'attachments-purchase-return',
                'supplier-prices' => 'attachments-purchase-price',
                'item-requests' => 'attachments-inventory-request',
                'stock-transfers' => 'attachments-inventory-transfer',
                'inventory-adjustments' => 'attachments-inventory-adjustment',
                'work-orders' => 'attachments-inventory-job-order',
                'material-additions' => 'attachments-inventory-material-addition',
                'work-completions' => 'attachments-inventory-job-completion',
                'stock-opname-orders' => 'attachments-inventory-stock-opname-request',
                'stock-opname-results' => 'attachments-inventory-stock-opname-result',
                'expense-entries' => 'attachments-other-expense-record',
                'payroll-entries' => 'attachments-other-salary-record',
                'general-journals' => 'attachments-other-general-journal',
                'cash-payments' => 'attachments-other-payment',
                'cash-receipts' => 'attachments-other-receipt',
                'bank-transfers' => 'attachments-other-bank-transfer',
                'fixed-assets' => 'attachments-other-fixed-asset',
                'asset-changes' => 'attachments-other-fixed-asset-change',
                'asset-disposals' => 'attachments-other-fixed-asset-disposal',
                'asset-moves' => 'attachments-other-fixed-asset-transfer',
            ];

            $prefKey = $blueprintToPreferenceMap[$blueprint->key] ?? null;
            if ($prefKey && \Illuminate\Support\Facades\Schema::hasTable('preference_settings')) {
                $setting = DB::table('preference_settings')
                    ->where('setting_key', $prefKey)
                    ->first();

                $isEnabled = false;
                if ($setting !== null) {
                    $decoded = json_decode($setting->value, true);
                    $isEnabled = $decoded === 'true' || $decoded === true || $decoded === '1' || $decoded === 1;
                }

                if ($isEnabled) {
                    $hasAttachmentsInPayload = !empty($payload['attachment_ids']);
                    $hasExistingAttachments = false;
                    if ($record->exists) {
                        $hasExistingAttachments = DB::table('attachments')
                            ->where('attachable_type', get_class($record))
                            ->where('attachable_id', $record->getKey())
                            ->exists();
                    }
                    if (!$hasAttachmentsInPayload && !$hasExistingAttachments) {
                        throw \Illuminate\Validation\ValidationException::withMessages([
                            'attachments' => ["Lampiran wajib disertakan untuk transaksi {$blueprint->label} sesuai pengaturan preferensi."]
                        ]);
                    }
                }
            }

            $before = $record->exists ? $this->activityLogger->snapshot($record) : null;

            // Kembalikan costing lama
            $costingKeys = [
                'goods-receipts',
                'sales-deliveries',
                'sales-returns',
                'purchase-returns',
                'inventory-adjustments',
                'work-completions',
                'material-additions',
                'stock-transfers',
                'stock-opname-results',
            ];
            $wasExisting = $record->exists;
            if ($wasExisting && in_array($blueprint->key, $costingKeys)) {
                $this->revertCosting($record);
            }

            if ($blueprint->key === 'accounts') {
                $autoCode = filter_var($payload['auto_code'] ?? true, FILTER_VALIDATE_BOOLEAN);
                $payload['auto_code'] = $autoCode;
                if ($autoCode) {
                    if (!empty($payload['parent_id'])) {
                        $parent = \App\Domain\Finance\Models\Account::find($payload['parent_id']);
                        if ($parent) {
                            $parentCode = (string) preg_replace('/[^0-9]/', '', $parent->code);
                            $needsGeneration = !$record->exists 
                                || $record->parent_id != $payload['parent_id'] 
                                || empty($record->code);

                            if ($needsGeneration) {
                                $existingChildren = \App\Domain\Finance\Models\Account::where('parent_id', $parent->id)->get();
                                $index = count($existingChildren) + 1;
                                do {
                                    $suffix = str_pad($index, 2, '0', STR_PAD_LEFT);
                                    $generatedCode = $parentCode . $suffix;
                                    $index++;
                                } while (\App\Domain\Finance\Models\Account::where('code', $generatedCode)->exists());

                                $payload['code'] = $generatedCode;
                            } else {
                                $payload['code'] = $record->code;
                            }
                        }
                    } else {
                        $needsGeneration = !$record->exists 
                            || empty($record->code)
                            || (isset($payload['account_type']) && $record->account_type != $payload['account_type']);

                        if ($needsGeneration) {
                            $type = $payload['account_type'] ?? 'Cash/Bank';
                             $typePrefixMap = [
                                'Cash/Bank' => '11',
                                'Receivable' => '11',
                                'Inventory' => '11',
                                'Other Current Asset' => '11',
                                'Fixed Asset' => '12',
                                'Accumulated Depreciation' => '12',
                                'Other Asset' => '13',
                                'Payable' => '21',
                                'Other Current Liability' => '21',
                                'Long Term Liability' => '22',
                                'Equity' => '31',
                                'Revenue' => '41',
                                'Cost of Sales' => '51',
                                'Expense' => '61',
                                'Other Expense' => '71',
                                'Other Revenue' => '81',
                            ];
                            $prefix = $typePrefixMap[$type] ?? '99';
                            
                            $index = 1;
                            do {
                                $seqNum = str_pad($index, 2, '0', STR_PAD_LEFT);
                                $generatedCode = "{$prefix}{$seqNum}";
                                $index++;
                            } while (\App\Domain\Finance\Models\Account::where('code', $generatedCode)->exists());

                            $payload['code'] = $generatedCode;
                        } else {
                            $payload['code'] = $record->code;
                        }
                    }
                }
            }

            $record->fill(Arr::only($payload, $record->getFillable()));
            $record->save();

            $oldDocs = [];
            if ($record->exists && in_array($blueprint->key, ['sales-receipts', 'purchase-payments']) && method_exists($record, 'lines')) {
                $oldDocs = $record->lines()->pluck('reference_code')->filter()->unique()->toArray();
            }

            $blueprint->sync($record, $payload);

            if ($blueprint->key === 'sales-invoices') {
                $oldMetadata = json_decode($record->getOriginal('metadata') ?? '{}', true);
                $oldDepositIds = [];
                if (isset($oldMetadata['advance_payments'])) {
                    foreach ($oldMetadata['advance_payments'] as $adv) {
                        if (isset($adv['__depositId'])) {
                            $oldDepositIds[] = (int) $adv['__depositId'];
                        }
                    }
                }
                $this->reconcileSalesDeposits($record, $oldDepositIds);
            }

            if ($blueprint->key === 'cash-payments') {
                if ($wasExisting) {
                    $originalRelatedId = $record->getOriginal('related_document_id');
                    $currentRelatedId = $record->related_document_id;
                    if ($originalRelatedId && $originalRelatedId != $currentRelatedId) {
                        $oldDoc = \App\Domain\Support\Models\OperationDocument::find($originalRelatedId);
                        if ($oldDoc) {
                            $oldDoc->update([
                                'status' => 'Sedang diproses',
                                'paid_amount' => 0.00,
                            ]);
                        }
                    }
                }

                if ($record->related_document_id) {
                    $relatedDoc = \App\Domain\Support\Models\OperationDocument::find($record->related_document_id);
                    if ($relatedDoc) {
                        $relatedDoc->update([
                            'status' => 'Terbayar',
                            'paid_amount' => $relatedDoc->total_amount,
                        ]);
                    }
                }
            }

            // Terapkan costing baru
            if (in_array($blueprint->key, $costingKeys)) {
                $this->applyCosting($record);
            }

            if (array_key_exists('attachment_ids', $payload) && method_exists($record, 'attachments')) {
                $attachmentIds = $payload['attachment_ids'] ?? [];

                \App\Domain\Support\Models\Attachment::whereIn('id', $attachmentIds)
                    ->update([
                        'attachable_type' => get_class($record),
                        'attachable_id' => $record->getKey(),
                    ]);

                $record->attachments()
                    ->whereNotIn('id', $attachmentIds)
                    ->get()
                    ->each(function ($attachment): void {
                        if (\Illuminate\Support\Facades\Storage::disk('public')->exists($attachment->file_path)) {
                            \Illuminate\Support\Facades\Storage::disk('public')->delete($attachment->file_path);
                        }
                        $attachment->delete();
                    });
            }

            $freshRecord = $record->fresh($blueprint->with) ?? $record;

            $this->activityLogger->logMutation(
                $blueprint,
                $record->wasRecentlyCreated ? 'create' : 'update',
                $freshRecord,
                $before,
                $this->activityLogger->snapshot($freshRecord),
            );

            // Invalidate dashboard caches on mutation
            $this->invalidateDashboardCache();

            // Post to Jurnal Umum
            $this->postToGeneralJournal($freshRecord);

            // Reconcile payment status
            $this->reconcilePayments($blueprint, $freshRecord, $oldDocs);

            return $freshRecord;
        });
    }

    /**
     * Batalkan costing dokumen.
     */
    protected function revertCosting(Model $record): void
    {
        $costingService = app(\App\Domain\Inventory\Services\InventoryCostingService::class);

        if (!method_exists($record, 'lines')) {
            return;
        }

        $lines = $record->lines()->get();

        foreach ($lines as $line) {
            $sourceType = get_class($record);
            $sourceLineId = $line->id;

            // Kembalikan batch masuk jika ada
            $costingService->revertStockEntry($sourceType, $sourceLineId);

            // Kembalikan konsumsi keluar jika ada
            $attributes = is_string($line->attributes) ? json_decode($line->attributes, true) : ($line->attributes ?? []);
            if (!empty($attributes['consumed_batches'])) {
                $costingService->revertStockConsumption($attributes['consumed_batches']);
            }
        }
    }

    /**
     * Terapkan costing untuk baris dokumen.
     */
    protected function applyCosting(Model $record): void
    {
        $status = strtolower((string) ($record->status ?? ''));
        if (in_array($status, ['void', 'cancelled'])) {
            return;
        }

        if (!method_exists($record, 'lines')) {
            return;
        }

        $costingService = app(\App\Domain\Inventory\Services\InventoryCostingService::class);
        $sourceType = get_class($record);
        $sourceId = $record->id;

        $docType = $record->document_type ?? null;
        if (isset($record->entry_date)) {
            $entryDate = \Carbon\Carbon::parse($record->entry_date);
        } elseif (isset($record->document_date)) {
            $entryDate = \Carbon\Carbon::parse($record->document_date);
        } else {
            $entryDate = now();
        }

        $lines = $record->lines()->get();

        foreach ($lines as $line) {
            $productId = $line->product_id;
            if (!$productId) {
                continue;
            }

            $sourceLineId = $line->id;

            // Cari gudang
            $warehouseId = null;
            if (isset($line->warehouse_id) && $line->warehouse_id) {
                $warehouseId = $line->warehouse_id;
            } elseif (isset($record->warehouse_id) && $record->warehouse_id) {
                $warehouseId = $record->warehouse_id;
            }

            if ($record instanceof \App\Domain\Support\Models\OperationDocument) {
                if ($docType === 'goods_receipt' || $docType === 'sales_return' || $docType === 'work_completion') {
                    if ($warehouseId) {
                        $this->recordEntryHelper(
                            $costingService,
                            $sourceType,
                            $sourceId,
                            $sourceLineId,
                            $productId,
                            $warehouseId,
                            (float) $line->quantity,
                            (float) ($line->unit_price ?? 0),
                            $entryDate
                        );
                    }
                } elseif ($docType === 'sales_delivery' || $docType === 'purchase_return' || $docType === 'material_addition') {
                    if ($warehouseId) {
                        $this->consumeStockHelper(
                            $costingService,
                            $line,
                            $productId,
                            $warehouseId,
                            (float) $line->quantity,
                            $entryDate
                        );
                    }
                } elseif ($docType === 'inventory_adjustment') {
                    if ($warehouseId) {
                        $qty = (float) $line->quantity;
                        if ($qty > 0) {
                            $this->recordEntryHelper(
                                $costingService,
                                $sourceType,
                                $sourceId,
                                $sourceLineId,
                                $productId,
                                $warehouseId,
                                $qty,
                                (float) ($line->unit_price ?? 0),
                                $entryDate
                            );
                        } elseif ($qty < 0) {
                            $this->consumeStockHelper(
                                $costingService,
                                $line,
                                $productId,
                                $warehouseId,
                                abs($qty),
                                $entryDate
                            );
                        }
                    }
                }
            } elseif ($record instanceof \App\Domain\Inventory\Models\InventoryDocument) {
                if ($docType === 'stock_transfer') {
                    $fromWarehouseId = $record->warehouse_id;
                    $toWarehouseId = $record->counterpart_warehouse_id;
                    $qty = (float) $line->quantity;

                    if ($fromWarehouseId && $toWarehouseId && $qty > 0) {
                        $consumeResult = $this->consumeStockHelper(
                            $costingService,
                            $line,
                            $productId,
                            $fromWarehouseId,
                            $qty,
                            $entryDate
                        );

                        $unitCost = 0.0;
                        if ($qty > 0) {
                            $unitCost = $consumeResult['total_cost'] / $qty;
                        }
                        $this->recordEntryHelper(
                            $costingService,
                            $sourceType,
                            $sourceId,
                            $sourceLineId,
                            $productId,
                            $toWarehouseId,
                            $qty,
                            $unitCost,
                            $entryDate
                        );
                    }
                } elseif ($docType === 'stock_opname_result') {
                    $qtyDiff = (float) ($line->counted_quantity ?? 0) - (float) ($line->system_quantity ?? 0);
                    if ($qtyDiff > 0) {
                        $this->recordEntryHelper(
                            $costingService,
                            $sourceType,
                            $sourceId,
                            $sourceLineId,
                            $productId,
                            $warehouseId,
                            $qtyDiff,
                            0.0,
                            $entryDate
                        );
                    } elseif ($qtyDiff < 0) {
                        $this->consumeStockHelper(
                            $costingService,
                            $line,
                            $productId,
                            $warehouseId,
                            abs($qtyDiff),
                            $entryDate
                        );
                    }
                }
            }
        }
    }

    /**
     * Catat penambahan stok.
     */
    protected function recordEntryHelper(
        \App\Domain\Inventory\Services\InventoryCostingService $costingService,
        string $sourceType,
        int $sourceId,
        int $sourceLineId,
        int $productId,
        int $warehouseId,
        float $qty,
        float $unitCost,
        \Carbon\Carbon $entryDate
    ): void {
        if ($unitCost <= 0) {
            $unitCost = $this->resolveProductCost($productId);
        }
        $costingService->recordStockEntry(
            $sourceType,
            $sourceId,
            $sourceLineId,
            $productId,
            $warehouseId,
            $qty,
            $unitCost,
            $entryDate
        );
    }

    /**
     * Catat konsumsi stok.
     */
    protected function consumeStockHelper(
        \App\Domain\Inventory\Services\InventoryCostingService $costingService,
        Model $line,
        int $productId,
        int $warehouseId,
        float $qty,
        \Carbon\Carbon $entryDate
    ): array {
        $result = $costingService->consumeStock($productId, $warehouseId, $qty, $entryDate);

        $attributes = is_string($line->attributes) ? json_decode($line->attributes, true) : ($line->attributes ?? []);
        $attributes['consumed_batches'] = $result['consumptions'];
        $attributes['cogs'] = $result['total_cost'];
        $line->attributes = $attributes;
        $line->saveQuietly();

        return $result;
    }

    /**
     * Ambil fallback harga produk.
     */
    protected function resolveProductCost(int $productId): float
    {
        $product = \App\Domain\Catalog\Models\Product::find($productId);
        return $product ? (float) ($product->default_purchase_price ?? 0) : 0.0;
    }

    /**
     * Memeriksa apakah periode tanggal yang diberikan sudah ditutup.
     */
    protected function isPeriodClosed(mixed $date): bool
    {
        if (empty($date)) {
            return false;
        }

        try {
            $dt = \Carbon\Carbon::parse($date);
            $year = (string) $dt->format('Y');
            $monthNum = (int) $dt->format('n');

            $monthsMap = [
                1 => 'Januari',
                2 => 'Februari',
                3 => 'Maret',
                4 => 'April',
                5 => 'Mei',
                6 => 'Juni',
                7 => 'Juli',
                8 => 'Agustus',
                9 => 'September',
                10 => 'Oktober',
                11 => 'November',
                12 => 'Desember',
            ];

            $monthName = $monthsMap[$monthNum] ?? '';
            if (empty($monthName)) {
                return false;
            }

            return DB::table('operation_documents')
                ->where('document_type', 'period_end')
                ->where('metadata->month', $monthName)
                ->where('metadata->year', $year)
                ->exists();
        } catch (\Throwable $e) {
            return false;
        }
    }

    /**
     * Hapus seluruh cache widget dashboard.
     */
    protected function invalidateDashboardCache(): void
    {
        \Illuminate\Support\Facades\Cache::forget('dashboard_widgets_retail');
        \Illuminate\Support\Facades\Cache::forget('dashboard_widgets_trade-portal');
        \Illuminate\Support\Facades\Cache::forget('dashboard_widgets_manufacture');
    }

    /**
     * Cek apakah nomor dokumen adalah nomor otomatis (generated).
     */
    protected function isAutoGeneratedNumber(string $number, string $resourceKey): bool
    {
        $number = trim($number);
        if ($number === '') {
            return true;
        }

        // Format titik lama: PREFIX.YYYY.MM.DD.HHMMSS
        if (preg_match('/^[A-Z]+(\.[A-Z]+)?\.\d{4}\.\d{2}\.\d{2}\.\d{6}$/', $number)) {
            return true;
        }

        // Format strip baru: PREFIX-YYYYMMDD-HHMMSS
        if (preg_match('/^[A-Z]+(\.[A-Z]+)?-\d{8}-\d{6}$/', $number)) {
            return true;
        }

        return false;
    }

    /**
     * Generate nomor dokumen sekuensial urut ala Accurate.
     */
    protected function generateNextSequentialNumber(string $resourceKey, ?string $entryDate): string
    {
        $prefixes = [
            'sales-quotes' => 'SQ',
            'sales-orders' => 'SO',
            'sales-deliveries' => 'SD',
            'sales-invoices' => 'SI',
            'sales-returns' => 'SR',
            'purchase-orders' => 'PO',
            'goods-receipts' => 'GR',
            'purchase-invoices' => 'PI',
            'purchase-returns' => 'PR',
            'payroll-entries' => 'EPY',
            'expense-entries' => 'EXP',
            'general-journals' => 'JV',
            'cash-payments' => 'CP',
            'cash-receipts' => 'CR',
            'bank-transfers' => 'BT',
            'sales-deposits' => 'DP',
            'purchase-payments' => 'PP',
            'sales-receipts' => 'SR',
            'item-requests' => 'IR',
        ];

        $prefix = $prefixes[$resourceKey] ?? 'DOC';
        
        $date = $entryDate ? \Carbon\Carbon::parse($entryDate) : now();
        $year = $date->format('Y');
        $month = $date->format('m');
        
        // Cari nomor terakhir di bulan dan tahun yang sama: e.g. PREFIX.YYYY.MM.%
        $latest = DB::table('operation_documents')
            ->where('document_type', $this->getDocumentTypeFromResource($resourceKey))
            ->where('document_number', 'like', "{$prefix}.{$year}.{$month}.%")
            ->orderBy('id', 'desc')
            ->get()
            ->first(function ($doc) {
                // Hanya ambil yang berformat PREFIX.YYYY.MM.00001 (4 bagian)
                $parts = explode('.', $doc->document_number);
                return count($parts) === 4 && is_numeric(end($parts)) && strlen(end($parts)) === 5;
            });

        $nextSeq = 1;
        if ($latest) {
            $parts = explode('.', $latest->document_number);
            $lastPart = end($parts);
            if (is_numeric($lastPart)) {
                $nextSeq = ((int) $lastPart) + 1;
            }
        }

        $seqString = str_pad($nextSeq, 5, '0', STR_PAD_LEFT);
        return "{$prefix}.{$year}.{$month}.{$seqString}";
    }

    /**
     * Dapatkan tipe dokumen berdasarkan key resource.
     */
    protected function getDocumentTypeFromResource(string $resourceKey): string
    {
        $map = [
            'sales-quotes' => 'sales_quote',
            'sales-orders' => 'sales_order',
            'sales-deliveries' => 'sales_delivery',
            'sales-invoices' => 'sales_invoice',
            'sales-returns' => 'sales_return',
            'purchase-orders' => 'purchase_order',
            'goods-receipts' => 'goods_receipt',
            'purchase-invoices' => 'purchase_invoice',
            'purchase-returns' => 'purchase_return',
            'payroll-entries' => 'payroll_entry',
            'expense-entries' => 'expense_entry',
            'general-journals' => 'general_journal',
            'cash-payments' => 'cash_payment',
            'cash-receipts' => 'cash_receipt',
            'bank-transfers' => 'bank_transfer',
            'sales-deposits' => 'sales_deposit',
            'purchase-payments' => 'purchase_payment',
            'sales-receipts' => 'sales_receipt',
            'item-requests' => 'item_request',
        ];
        return $map[$resourceKey] ?? str_replace('-', '_', rtrim($resourceKey, 's'));
    }

    /**
     * Posting otomatis transaksi ke Jurnal Umum.
     */
    protected function postToGeneralJournal(Model $record): void
    {
        if (!($record instanceof \App\Domain\Support\Models\OperationDocument)) {
            return;
        }

        $postableTypes = ['expense_entry', 'payroll_entry', 'cash_payment', 'cash_receipt', 'bank_transfer', 'sales_invoice', 'purchase_invoice'];
        if (!in_array($record->document_type, $postableTypes)) {
            return;
        }

        $journal = \App\Domain\Support\Models\OperationDocument::where('document_type', 'general_journal')
            ->where('related_document_id', $record->id)
            ->first();

        if (!$journal) {
            $journal = new \App\Domain\Support\Models\OperationDocument();
            $journal->document_type = 'general_journal';
            $journal->related_document_id = $record->id;
        }

        $prefixes = [
            'expense_entry'    => 'JV-EXP-',
            'payroll_entry'    => 'JV-EPY-',
            'cash_payment'     => 'JV-CP-',
            'cash_receipt'     => 'JV-CR-',
            'bank_transfer'    => 'JV-BT-',
            'sales_invoice'    => 'JV-SI-',
            'purchase_invoice' => 'JV-PI-',
        ];

        $journal->branch_id       = $record->branch_id;
        $journal->department_id   = $record->department_id;
        $journal->document_number = ($prefixes[$record->document_type] ?? 'JV-') . $record->document_number;
        $journal->entry_date      = $record->entry_date;
        $journal->status          = 'Posted';
        $journal->notes           = 'Posting otomatis dari ' . $record->document_number . ($record->notes ? ' - ' . $record->notes : '');
        $journal->total_amount    = $record->total_amount;
        $journal->save();

        $lines      = [];
        $sortOrder  = 0;
        $docType    = $record->document_type;
        $recordLines = $record->lines ?? collect();

        if ($docType === 'expense_entry' || $docType === 'payroll_entry') {
            foreach ($recordLines as $line) {
                if ($line->account_id && $line->total_amount > 0) {
                    $lines[] = ['account_id' => $line->account_id, 'description' => $line->description ?? 'Beban', 'debit_amount' => $line->total_amount, 'credit_amount' => 0.00, 'total_amount' => $line->total_amount, 'sort_order' => $sortOrder++];
                }
            }
            if ($record->primary_account_id) {
                $lines[] = ['account_id' => $record->primary_account_id, 'description' => 'Utang / Kewajiban', 'debit_amount' => 0.00, 'credit_amount' => $record->total_amount, 'total_amount' => $record->total_amount, 'sort_order' => $sortOrder++];
            }
        } elseif ($docType === 'cash_payment') {
            foreach ($recordLines as $line) {
                if ($line->account_id && $line->total_amount > 0) {
                    $lines[] = ['account_id' => $line->account_id, 'description' => $line->description ?? 'Pembayaran', 'debit_amount' => $line->total_amount, 'credit_amount' => 0.00, 'total_amount' => $line->total_amount, 'sort_order' => $sortOrder++];
                }
            }
            if ($record->primary_account_id) {
                $lines[] = ['account_id' => $record->primary_account_id, 'description' => 'Kas / Bank', 'debit_amount' => 0.00, 'credit_amount' => $record->total_amount, 'total_amount' => $record->total_amount, 'sort_order' => $sortOrder++];
            }
        } elseif ($docType === 'cash_receipt') {
            if ($record->primary_account_id) {
                $lines[] = ['account_id' => $record->primary_account_id, 'description' => 'Kas / Bank', 'debit_amount' => $record->total_amount, 'credit_amount' => 0.00, 'total_amount' => $record->total_amount, 'sort_order' => $sortOrder++];
            }
            foreach ($recordLines as $line) {
                if ($line->account_id && $line->total_amount > 0) {
                    $lines[] = ['account_id' => $line->account_id, 'description' => $line->description ?? 'Penerimaan', 'debit_amount' => 0.00, 'credit_amount' => $line->total_amount, 'total_amount' => $line->total_amount, 'sort_order' => $sortOrder++];
                }
            }
        } elseif ($docType === 'bank_transfer') {
            if ($record->secondary_account_id) {
                $lines[] = ['account_id' => $record->secondary_account_id, 'description' => 'Kas/Bank Penerima', 'debit_amount' => $record->total_amount, 'credit_amount' => 0.00, 'total_amount' => $record->total_amount, 'sort_order' => $sortOrder++];
            }
            if ($record->primary_account_id) {
                $lines[] = ['account_id' => $record->primary_account_id, 'description' => 'Kas/Bank Pengirim', 'debit_amount' => 0.00, 'credit_amount' => $record->total_amount, 'total_amount' => $record->total_amount, 'sort_order' => $sortOrder++];
            }
        } elseif ($docType === 'sales_invoice') {
            if ($record->primary_account_id) {
                $lines[] = ['account_id' => $record->primary_account_id, 'description' => 'Piutang Penjualan', 'debit_amount' => $record->total_amount, 'credit_amount' => 0.00, 'total_amount' => $record->total_amount, 'sort_order' => $sortOrder++];
            }
            foreach ($recordLines as $line) {
                if ($line->total_amount > 0) {
                    $accId = optional($line->product)->sales_account_id
                        ?? DB::table('accounts')->where('code', 'like', '41%')->value('id');
                    if ($accId) {
                        $lines[] = ['account_id' => $accId, 'description' => 'Pendapatan - ' . (optional($line->product)->name ?? 'Barang'), 'debit_amount' => 0.00, 'credit_amount' => $line->total_amount, 'total_amount' => $line->total_amount, 'sort_order' => $sortOrder++];
                    }
                }
            }
        } elseif ($docType === 'purchase_invoice') {
            if ($record->primary_account_id) {
                $lines[] = ['account_id' => $record->primary_account_id, 'description' => 'Hutang Usaha', 'debit_amount' => 0.00, 'credit_amount' => $record->total_amount, 'total_amount' => $record->total_amount, 'sort_order' => $sortOrder++];
            }
            foreach ($recordLines as $line) {
                if ($line->total_amount > 0) {
                    $accId = optional($line->product)->inventory_account_id
                        ?? DB::table('accounts')->where('code', 'like', '11%')->value('id');
                    if ($accId) {
                        $lines[] = ['account_id' => $accId, 'description' => 'Persediaan - ' . (optional($line->product)->name ?? 'Barang'), 'debit_amount' => $line->total_amount, 'credit_amount' => 0.00, 'total_amount' => $line->total_amount, 'sort_order' => $sortOrder++];
                    }
                }
            }
        }

        $journal->lines()->delete();
        foreach ($lines as $line) {
            $journal->lines()->create($line);
        }
    }

    /**
     * Reconcile payment statuses of source documents.
     */
    protected function reconcilePayments(BackendResourceBlueprint $blueprint, Model $record, ?array $oldDocs = null): void
    {
        if (!in_array($blueprint->key, ['sales-receipts', 'purchase-payments'], true)) {
            return;
        }

        $currentDocs = [];
        if (method_exists($record, 'lines')) {
            $currentDocs = $record->lines()->pluck('reference_code')->filter()->unique()->toArray();
        }

        $allDocs = array_unique(array_merge($currentDocs, $oldDocs ?? []));
        if (empty($allDocs)) {
            return;
        }

        foreach ($allDocs as $docNum) {
            $sourceDoc = \App\Domain\Support\Models\OperationDocument::where('document_number', $docNum)->first();
            if (!$sourceDoc) {
                continue;
            }

            // Sum up active payments for this document number
            $totalPaid = (float) DB::table('operation_document_lines')
                ->join('operation_documents', 'operation_document_lines.operation_document_id', '=', 'operation_documents.id')
                ->where('operation_document_lines.reference_code', $docNum)
                ->whereNotIn('operation_documents.status', ['Void', 'Cancelled'])
                ->sum('operation_document_lines.total_amount');

            $totalAmount = (float) $sourceDoc->total_amount;
            $outstanding = max(0.00, $totalAmount - $totalPaid);
            
            // For safety and floats comparison, round to 2 decimals
            $outstanding = round($outstanding, 2);

            $status = $outstanding <= 0.01 ? 'Lunas' : 'Belum Lunas';

            $sourceDoc->update([
                'paid_amount' => $totalPaid,
                'outstanding_amount' => $outstanding,
                'status' => $status,
            ]);
        }
    }

    /**
     * Reconcile outstanding amount of used sales deposits.
     */
    protected function reconcileSalesDeposits(Model $record, ?array $oldDepositIds = null): void
    {
        $currentIds = [];
        if ($record->metadata && isset($record->metadata['advance_payments'])) {
            foreach ($record->metadata['advance_payments'] as $adv) {
                if (isset($adv['__depositId'])) {
                    $currentIds[] = (int) $adv['__depositId'];
                }
            }
        }
        
        $allIds = array_unique(array_merge($currentIds, $oldDepositIds ?? []));
        if (empty($allIds)) {
            return;
        }

        foreach ($allIds as $depositId) {
            $deposit = \App\Domain\Support\Models\OperationDocument::find($depositId);
            if (!$deposit) {
                continue;
            }

            $totalAllocated = 0.0;
            
            // Search all operation_documents of type 'sales_invoice' that are active
            $invoices = \App\Domain\Support\Models\OperationDocument::where('document_type', 'sales_invoice')
                ->whereNotIn('status', ['Void', 'Cancelled'])
                ->get();

            foreach ($invoices as $invoice) {
                if ($invoice->metadata && isset($invoice->metadata['advance_payments'])) {
                    foreach ($invoice->metadata['advance_payments'] as $adv) {
                        if (isset($adv['__depositId']) && (int) $adv['__depositId'] === (int) $depositId) {
                            $amt = $adv['amount'] ?? 0;
                            if (is_string($amt)) {
                                $amt = (float) preg_replace('/[^\d]/', '', $amt);
                            }
                            $totalAllocated += (float) $amt;
                        }
                    }
                }
            }

            $totalAmount = (float) $deposit->total_amount;
            $outstanding = max(0.00, $totalAmount - $totalAllocated);
            $outstanding = round($outstanding, 2);

            $deposit->update([
                'paid_amount' => $totalAllocated,
                'outstanding_amount' => $outstanding,
            ]);
        }
    }
}

