import {
    createAttachmentDockAction,
    createDeleteDockAction,
    createDocumentDockAction,
    createMoreDockAction,
    createSaveDockAction,
} from '@/features/workspace/modules/shared/workspaceDockActions';
import { buildTodayDisplayDate } from '@/features/workspace/shared/dateDefaults';

const todayDisplayDate = buildTodayDisplayDate();

const purchasePaymentCreateDockActions = [
    createSaveDockAction(),
    createDocumentDockAction(),
    createAttachmentDockAction({ itemId: 'upload', itemLabel: 'Tambah lampiran' }),
];

export const purchasePaymentDetailDockActions = [
    createSaveDockAction({ tone: 'muted', items: [] }),
    createDocumentDockAction(),
    createAttachmentDockAction(),
    createMoreDockAction(),
    createDeleteDockAction(),
];

const purchasePaymentTableRows = [
    { id: '111.102-01.2017.02.00003', number: '111.102-01.2017.02.00003', date: '11/02/2017', checkNumber: '', checkDate: '11/02/2017', supplier: 'PT. SGI', bank: 'Bank Mandiri IDR Jakarta (142-205-9324)', notes: '', paymentAmount: '84,787,200', method: 'Transfer Bank', branch: 'JAKARTA' },
    { id: '111.102-01.2017.02.00001', number: '111.102-01.2017.02.00001', date: '10/02/2017', checkNumber: '', checkDate: '10/02/2017', supplier: 'CV Indra Part', bank: 'Bank BCA IDR Surabaya (388-308-3993)', notes: '', paymentAmount: '41,800,000', method: 'Transfer Bank', branch: 'JAKARTA' },
    { id: '111.102-01.2016.12.00003', number: '111.102-01.2016.12.00003', date: '02/12/2016', checkNumber: 'BCA 23498', checkDate: '02/12/2016', supplier: 'PT Bersih Selalu', bank: 'Bank BCA IDR Jakarta (069-773-3993)', notes: '', paymentAmount: '11,080,800', method: 'Tunai', branch: 'JAKARTA' },
    { id: '111.102-01.2016.11.00002', number: '111.102-01.2016.11.00002', date: '20/11/2016', checkNumber: '', checkDate: '20/11/2016', supplier: 'Mentari Accessories', bank: 'Bank BCA IDR Jakarta (069-773-3993)', notes: '', paymentAmount: '65,000,000', method: 'Tunai', branch: 'JAKARTA' },
    { id: '111.102-01.2016.11.00001', number: '111.102-01.2016.11.00001', date: '15/11/2016', checkNumber: '', checkDate: '15/11/2016', supplier: 'PT. SGI', bank: 'Bank BCA IDR Jakarta (069-773-3993)', notes: '', paymentAmount: '32,160,000', method: 'Tunai', branch: 'JAKARTA' },
    { id: '111.202-04.2016.10.00002', number: '111.202-04.2016.10.00002', date: '21/10/2016', checkNumber: '', checkDate: '21/10/2016', supplier: 'Applus', bank: 'Bank Mandiri IDR Surabaya (276-129-4178)', notes: '', paymentAmount: '19,002,000', method: 'Transfer Bank', branch: 'JAKARTA' },
    { id: '111.201-02.2016.10.00002', number: '111.201-02.2016.10.00002', date: '17/10/2016', checkNumber: '', checkDate: '17/10/2016', supplier: 'Toko Mega Mendung', bank: 'Kas Besar Kantor Surabaya', notes: '', paymentAmount: '8,360,000', method: 'Tunai', branch: 'JAKARTA' },
    { id: '111.202-03.2016.10.00001', number: '111.202-03.2016.10.00001', date: '12/10/2016', checkNumber: '', checkDate: '12/10/2016', supplier: 'SAMSANG', bank: 'Bank BCA SGD Surabaya (102-263-7587)', notes: '', paymentAmount: '3,548', method: 'Transfer Bank', branch: 'JAKARTA' },
    { id: '111.201-02.2016.10.00001', number: '111.201-02.2016.10.00001', date: '11/10/2016', checkNumber: '', checkDate: '11/10/2016', supplier: 'PT Selaras Inti', bank: 'Kas Besar Kantor Surabaya', notes: '', paymentAmount: '55,123,750', method: 'Tunai', branch: 'JAKARTA' },
];

const defaultPurchasePaymentDraft = {
    payee: [],
    bankAccounts: [],
    paymentAmount: '',
    paymentAmountPrefix: '',
    paymentAmountDisplay: '0',
    entryDate: todayDisplayDate,
    autoNumber: true,
    numberingType: 'Bank BCA IDR Jakarta (069-773-3993)',
    documentNumber: '',
    currency: '',
    invoiceSearch: '',
    invoices: [],
    invoiceTitle: 'Faktur',
    paymentMethod: 'Tunai',
    dueDatePph: '',
    notes: '',
    voided: false,
    branches: ['JAKARTA'],
    reconcileStatus: '',
    printStatus: '',
    paidWith: '',
    paidAt: '',
    footerPaymentValue: '0',
    footerInvoiceValue: '0',
    showSecondaryAmountButton: true,
    modal: null,
    dockActions: purchasePaymentCreateDockActions,
};

const purchasePaymentDetailRecords = {
    '111.102-01.2017.02.00003': {
        payee: ['[V.00001] PT. SGI'],
        bankAccounts: ['Bank Mandiri IDR Jakarta (142-205-9324)'],
        paymentAmount: '84,787,200',
        paymentAmountPrefix: 'Rp',
        paymentAmountDisplay: '84,787,200',
        entryDate: '11/02/2017',
        autoNumber: false,
        numberingType: 'Bank BCA IDR Jakarta (069-773-3993)',
        documentNumber: '111.102-01.2017.02.00003',
        currency: 'IDR',
        invoiceSearch: '',
        invoices: [
            {
                id: 'invoice-payment-1',
                number: 'SGI/201765501',
                formNumber: 'PI.2016.12.00001',
                date: '19/12/2016',
                total: 'Rp 88,320,000',
                outstanding: 'Rp 0',
                pay: 'Rp 88,320,000',
                discount: 'Rp 0',
                payment: 'Rp 84,787,200',
                pphChecked: true,
                pphLabel: 'Jasa Freight forwarding',
                pphAmount: 'Rp 3,532,800',
                withholdingProof: 'BP/SGI-01445',
                discountAccount: '',
                discountValue: '',
                discountNotes: '',
                department: '',
            },
        ],
        invoiceTitle: 'Faktur (1)',
        paymentMethod: 'Transfer Bank',
        dueDatePph: '11/02/2017',
        notes: '',
        voided: false,
        branches: ['JAKARTA'],
        reconcileStatus: 'Belum',
        printStatus: 'Belum cetak/email',
        paidWith: 'Transfer Bank',
        paidAt: '-',
        footerPaymentValue: 'Rp 84,787,200',
        footerInvoiceValue: 'Rp 84,787,200',
        showSecondaryAmountButton: false,
        modal: {
            title: 'Faktur',
            tabs: [
                { id: 'invoice', label: 'Faktur' },
                { id: 'discount-info', label: 'Informasi Diskon' },
            ],
            invoice: {
                formNumber: 'PI.2016.12.00001',
                billNumber: 'SGI/201765501',
                outstanding: 'Rp 0',
                pay: '88,320,000',
                payment: 'Rp 84,787,200',
                pphChecked: true,
                pphLabel: 'Jasa Freight forwarding',
                pphAmount: 'Rp 3,532,800',
                withholdingProof: 'BP/SGI-01445',
                notice: 'PPh yang dipotong dibayarkan melalui menu Kas & Bank - Pembayaran - Ambil - PPh Pembelian',
            },
            discountInfo: {
                discountAccount: '',
                discountAmount: '',
                discountNotes: '',
                department: '',
                rows: [],
            },
        },
        dockActions: purchasePaymentDetailDockActions,
    },
};

export const defaultPurchasePaymentConfig = {
    labels: {
        payee: 'Pembayaran ke',
        bank: 'Bank',
        paymentAmount: 'Nilai Pembayaran',
        documentNumber: 'No Bukti #',
        entryDate: 'Tgl Bayar',
        paymentMethod: 'Metode Bayar',
        dueDatePph: 'Jth Tempo PPh',
        notes: 'Keterangan',
        voided: 'V O I D',
        branch: 'Cabang',
        reconcileStatus: 'Terekonsiliasi',
        printStatus: 'Dicetak/email',
    },
    topActions: [],
    numberingOptions: ['Bank BCA IDR Jakarta (069-773-3993)'],
    payeePlaceholder: 'Cari/Pilih Pemasok...',
    bankPlaceholder: 'Cari/Pilih...',
    invoiceSearchPlaceholder: 'Cari/Pilih...',
    table: {
        createLabel: 'Tambah Pembayaran',
        refreshLabel: 'Muat ulang',
        filterButtonLabel: 'Filter lanjutan',
        searchPlaceholder: 'Cari...',
        pageValue: '9',
        columns: [
            { id: 'number', label: 'Nomor #', widthClassName: 'w-[220px]', align: 'left' },
            { id: 'date', label: 'Tanggal', widthClassName: 'w-[130px]', align: 'left' },
            { id: 'checkNumber', label: 'No. Cek', widthClassName: 'w-[160px]', align: 'left' },
            { id: 'checkDate', label: 'Tanggal Cek', widthClassName: 'w-[140px]', align: 'left' },
            { id: 'supplier', label: 'Pemasok', widthClassName: 'w-[26%]', align: 'left' },
            { id: 'bank', label: 'Bank', widthClassName: 'w-[30%]', align: 'left' },
            { id: 'notes', label: 'Keterangan', widthClassName: 'w-[24%]', align: 'left' },
            { id: 'paymentAmount', label: 'Nilai Pembayaran', widthClassName: 'w-[150px]', align: 'right' },
        ],
        rows: purchasePaymentTableRows,
        filters: [
            { id: 'date', rowKey: 'date', options: [{ value: 'all', label: 'Tanggal: Semua' }, { value: '11/02/2017', label: 'Tanggal: 11/02/2017' }] },
            { id: 'checkDate', rowKey: 'checkDate', options: [{ value: 'all', label: 'Tanggal Cek: Semua' }, { value: '11/02/2017', label: 'Tanggal Cek: 11/02/2017' }] },
            { id: 'method', rowKey: 'method', options: [{ value: 'all', label: 'Metode Bayar: Semua' }, { value: 'Tunai', label: 'Metode Bayar: Tunai' }, { value: 'Transfer Bank', label: 'Metode Bayar: Transfer Bank' }] },
            { id: 'bank', rowKey: 'bank', options: [{ value: 'all', label: 'Bank: Semua' }, { value: 'Bank BCA IDR Jakarta (069-773-3993)', label: 'Bank: Bank BCA IDR Jakarta' }, { value: 'Bank Mandiri IDR Jakarta (142-205-9324)', label: 'Bank: Bank Mandiri IDR Jakarta' }] },
            { id: 'supplier', rowKey: 'supplier', options: [{ value: 'all', label: 'Pembayaran ke: Semua' }, { value: 'PT. SGI', label: 'Pembayaran ke: PT. SGI' }, { value: 'Applus', label: 'Pembayaran ke: Applus' }] },
        ],
        downloadItems: [{ id: 'download-excel', label: 'Unduh Excel' }],
        printItems: [{ id: 'print-list', label: 'Cetak daftar pembayaran pembelian' }],
        settingsItems: [{ id: 'arrange-columns', label: 'Atur kolom' }],
    },
    sectionTabs: [
        { id: 'details', label: 'Faktur', icon: 'document' },
        { id: 'additional-info', label: 'Info lainnya', icon: 'info' },
    ],
    detailSectionTabs: [
        { id: 'details', label: 'Faktur', icon: 'document' },
        { id: 'additional-info', label: 'Info lainnya', icon: 'info' },
        { id: 'payment-info', label: 'Info pembayaran', icon: 'payment' },
    ],
    invoiceTable: {
        columns: [
            { id: 'spacer', label: '', kind: 'spacer', widthClassName: 'w-[38px]', align: 'center' },
            { id: 'number', label: 'No. Faktur', widthClassName: 'w-[52%]', align: 'left' },
            { id: 'date', label: 'Tgl Faktur', widthClassName: 'w-[120px]', align: 'left' },
            { id: 'total', label: 'Total Faktur', widthClassName: 'w-[150px]', align: 'right' },
            { id: 'outstanding', label: 'Terhutang', widthClassName: 'w-[150px]', align: 'right' },
            { id: 'pay', label: 'Bayar', widthClassName: 'w-[150px]', align: 'right' },
            { id: 'discount', label: 'Diskon', widthClassName: 'w-[150px]', align: 'right' },
            { id: 'payment', label: 'Pembayaran', widthClassName: 'w-[160px]', align: 'right' },
        ],
        emptyLabel: 'Belum ada data',
        minWidthClassName: 'min-w-[1200px]',
    },
    infoTitle: 'Info lainnya',
    paymentInfoTitle: 'Info Pembayaran',
    takeButtonLabel: 'Ambil',
    draft: defaultPurchasePaymentDraft,
    detailRecords: purchasePaymentDetailRecords,
};
