export function buildFormState(source = {}, config) {
    return {
        payee: [...(source.payee ?? config.draft?.payee ?? [])],
        bankAccounts: [...(source.bankAccounts ?? config.draft?.bankAccounts ?? [])],
        paymentAmount: source.paymentAmount ?? config.draft?.paymentAmount ?? '',
        paymentAmountPrefix: source.paymentAmountPrefix ?? config.draft?.paymentAmountPrefix ?? '',
        paymentAmountDisplay: source.paymentAmountDisplay ?? config.draft?.paymentAmountDisplay ?? '0',
        entryDate: source.entryDate ?? config.draft?.entryDate ?? '',
        autoNumber: source.autoNumber ?? config.draft?.autoNumber ?? true,
        numberingType: source.numberingType ?? config.draft?.numberingType ?? '',
        documentNumber: source.documentNumber ?? config.draft?.documentNumber ?? '',
        currency: source.currency ?? config.draft?.currency ?? '',
        invoiceSearch: source.invoiceSearch ?? config.draft?.invoiceSearch ?? '',
        invoices: [...(source.invoices ?? config.draft?.invoices ?? [])],
        invoiceTitle: source.invoiceTitle ?? config.draft?.invoiceTitle ?? 'Faktur',
        paymentMethod: source.paymentMethod ?? config.draft?.paymentMethod ?? 'Tunai',
        dueDatePph: source.dueDatePph ?? config.draft?.dueDatePph ?? '',
        notes: source.notes ?? config.draft?.notes ?? '',
        voided: source.voided ?? config.draft?.voided ?? false,
        branches: [...(source.branches ?? config.draft?.branches ?? [])],
        reconcileStatus: source.reconcileStatus ?? config.draft?.reconcileStatus ?? '',
        printStatus: source.printStatus ?? config.draft?.printStatus ?? '',
        paidWith: source.paidWith ?? config.draft?.paidWith ?? '',
        paidAt: source.paidAt ?? config.draft?.paidAt ?? '',
        footerPaymentValue: source.footerPaymentValue ?? config.draft?.footerPaymentValue ?? '0',
        footerInvoiceValue: source.footerInvoiceValue ?? config.draft?.footerInvoiceValue ?? '0',
        showSecondaryAmountButton: source.showSecondaryAmountButton ?? config.draft?.showSecondaryAmountButton ?? true,
        modal: source.modal ?? config.draft?.modal ?? null,
        dockActions: source.dockActions ?? config.draft?.dockActions ?? [],
    };
}
