import {
    createTableConfig,
    createTemplate,
    SHARED_LABELS,
} from '@/features/workspace/modules/business-partner/businessPartnerConfigCore';

const CUSTOMER_ROWS = [];

const CUSTOMER_DEFAULTS = {
    autoCode: true,
    codeType: 'Pelanggan',
    name: '',
    code: '',
    category: [],
    businessPhone: '',
    mobilePhone: '',
    whatsapp: '',
    email: '',
    fax: '',
    website: '',
    billingStreet: '',
    billingCity: '',
    billingPostalCode: '',
    billingProvince: '',
    billingCountry: '',
    branchUsage: '[Semua Cabang]',
    currencies: ['Indonesian Rupiah'],
    contacts: [],
    shippingSameAsBilling: true,
    shippingStreet: '',
    shippingCity: '',
    shippingPostalCode: '',
    shippingProvince: '',
    shippingCountry: '',
    additionalAddresses: [],
    priceCategories: ['Umum'],
    discountCategory: [],
    paymentTerms: ['C.O.D'],
    defaultSalesPerson: [],
    defaultDiscountPercent: '',
    defaultDescription: '',
    consignment: false,
    accountReceivable: [],
    accountAdvance: [],
    accountSales: [],
    accountItemDiscount: [],
    accountCostOfSales: [],
    accountSalesReturn: [],
    accountSalesDiscount: [],
    taxIncluded: false,
    taxIdType: 'NIK',
    taxNumber: '',
    taxName: '',
    taxTkuId: '',
    taxCountry: [],
    taxTransactionType: 'Ditanggung',
    taxSameAsBilling: true,
    taxStreet: '',
    taxCity: '',
    taxPostalCode: '',
    taxProvince: '',
    taxCountryName: '',
    receivableRows: [],
    receivableLimitMode: 'per-customer',
    receivableAgeEnabled: false,
    receivableAgeDays: '0',
    receivableAmountEnabled: false,
    receivableAmount: 'Rp-0',
    mergeToParent: false,
    defaultWarehouse: [],
    notes: '',
    detailActionLabel: '',
};

const CUSTOMER_DETAIL_RECORDS = {};

export const customerBusinessPartnerTemplate = createTemplate({
    type: 'customer',
    tabs: [
        { id: 'general', label: 'Umum' },
        { id: 'shipping', label: 'Pengiriman' },
        { id: 'sales', label: 'Penjualan' },
        { id: 'tax', label: 'Pajak' },
    ],
    table: createTableConfig({
        createLabel: 'Tambah Pelanggan',
        columns: [
            { id: 'name', label: 'Nama', widthClassName: 'w-[25%]', align: 'left' },
            { id: 'code', label: 'ID Pelanggan', widthClassName: 'w-[140px]', align: 'left' },
            { id: 'primaryContact', label: 'Kontak Utama', widthClassName: 'w-[130px]', align: 'left', truncate: true },
            { id: 'balance', label: 'Saldo', widthClassName: 'w-[150px]', align: 'right' },
            
            // Kolom-kolom baru (default disembunyikan)
            { id: 'phone', label: 'Telepon Kantor', widthClassName: 'w-[130px]', align: 'left', defaultHidden: true, noWrap: true },
            { id: 'mobilePhone', label: 'Handphone', widthClassName: 'w-[130px]', align: 'left', defaultHidden: true, noWrap: true },
            { id: 'whatsapp', label: 'WhatsApp', widthClassName: 'w-[130px]', align: 'left', defaultHidden: true, noWrap: true },
            { id: 'email', label: 'Email', widthClassName: 'w-[180px]', align: 'left', defaultHidden: true },
            { id: 'taxNumber', label: 'NPWP / NIK', widthClassName: 'w-[150px]', align: 'left', defaultHidden: true },
            { id: 'paymentTermsText', label: 'Syarat Pembayaran', widthClassName: 'w-[150px]', align: 'left', defaultHidden: true },
            { id: 'creditLimitText', label: 'Batas Piutang', widthClassName: 'w-[150px]', align: 'right', defaultHidden: true, noWrap: true },
            { id: 'categoryName', label: 'Kategori', widthClassName: 'w-[130px]', align: 'left', defaultHidden: true },
            { id: 'notes', label: 'Catatan', widthClassName: 'w-[200px]', align: 'left', defaultHidden: true, truncate: true },
            { id: 'isActiveText', label: 'Non Aktif', widthClassName: 'w-[110px]', align: 'center', defaultHidden: true },
        ],
        rows: CUSTOMER_ROWS,
        filters: [
            { id: 'inactive', rowKey: 'inactiveValue', options: [{ value: 'all', label: 'Non Aktif: Semua' }] },
            { id: 'category', rowKey: 'category', options: [{ value: 'all', label: 'Kategori: Semua' }, { value: 'Umum', label: 'Kategori: Umum' }] },
        ],
        pageValue: '23',
    }),
    labels: {
        ...SHARED_LABELS,
        code: 'ID Pelanggan',
        billingAddress: 'Alamat Penagihan',
        priceCategory: 'Kategori Harga',
        discountCategory: 'Kategori Diskon',
        paymentTerms: 'Syarat Pembayaran',
        defaultSalesPerson: 'Default Penjual',
        defaultDiscountPercent: 'Default Diskon (%)',
        defaultDescription: 'Default Deskripsi',
        consignment: 'Konsinyasi',
        receivable: 'Piutang',
        advance: 'Uang muka',
        sales: 'Penjualan',
        itemDiscount: 'Diskon Barang',
        costOfSales: 'Beban Pokok Penjualan',
        salesReturn: 'Retur Penjualan',
        salesDiscount: 'Diskon Penjualan',
        taxCountry: 'Kode Negara',
        defaultWarehouse: 'Gudang Default',
    },
    helperText: {
        salesAccountNote:
            '[Optional] Diisikan jika anda ingin membedakan jurnal akun piutang, uang muka, penjualan, retur penjualan, diskon barang penjualan, beban pokok penjualan dan akun diskon penjualan atas pelanggan ini dari default akunnya. Untuk dapat terpilih ke dalam transaksi, pastikan pengguna memiliki hak akses ke akun-akun ini',
    },
    headingLabels: {
        generalLeft: 'Info Umum',
        generalRight: 'Info lainnya',
        shippingLeft: 'Alamat Utama',
        shippingRight: 'Alamat lainnya',
        salesLeft: 'Penjualan',
        salesRight: 'Kustomisasi Akun Penjualan',
        taxLeft: 'Pajak',
        taxRight: 'Alamat',
        othersLimit: 'Pembatasan Piutang Pelanggan',
        othersOther: 'Lain-lain',
    },
    formDefaults: CUSTOMER_DEFAULTS,
    detailRecords: CUSTOMER_DETAIL_RECORDS,
});
