import {
    createTableConfig,
    createTemplate,
    SHARED_LABELS,
} from '@/features/workspace/modules/business-partner/businessPartnerConfigCore';

const CUSTOMER_ROWS = [
    { id: 'CSBY-0005', name: 'Abadi Phone Center', code: 'CSBY-0005', primaryContact: 'Abadi Phone Center', balance: 'IDR 2,378,730,000', category: 'Umum' },
    { id: 'CJKT-0003', name: 'Cinema Phone Cellular', code: 'CJKT-0003', primaryContact: 'Cinema Phone Cellular', balance: 'IDR 80,030,330; USD 84,480', category: 'Umum' },
    { id: 'CSBY-0011', name: 'Dimas seraya Accessories', code: 'CSBY-0011', primaryContact: 'Dimas seraya Accessories', balance: 'IDR 4,200,000', category: 'Umum' },
    { id: 'CJKT-0006', name: 'Global Phone Jaya', code: 'CJKT-0006', primaryContact: 'Global Phone Jaya', balance: 'IDR 741,700,000; USD 83,700', category: 'Umum' },
    { id: 'CSBY-0003', name: 'Grow up Phone Cellular', code: 'CSBY-0003', primaryContact: 'Grow up Phone Cellular', balance: 'USD 13,580', category: 'Umum' },
    { id: 'CJKT-0007', name: 'Lake West Accessories', code: 'CJKT-0007', primaryContact: 'Lake West Accessories', balance: 'USD 64,350', category: 'Umum' },
    { id: 'CJKT-0004', name: 'Maxsen Assesories', code: 'CJKT-0004', primaryContact: 'Maxsen Assesories', balance: 'SGD 42,100', category: 'Umum' },
    { id: 'CSBY-0006', name: 'Nasional Phone Jaya', code: 'CSBY-0006', primaryContact: 'Nasional Phone Jaya', balance: 'IDR 2,421,140,000', category: 'Umum' },
    { id: 'CSBY-0007', name: 'National Earth Accessories', code: 'CSBY-0007', primaryContact: 'National Earth Accessories', balance: 'USD 13,320', category: 'Umum' },
    { id: 'CSBY-0002', name: 'PT CIRCLE PHONE', code: 'CSBY-0002', primaryContact: 'PT CIRCLE PHONE', balance: 'SGD 62,580', category: 'Umum' },
    { id: 'CSBY-0010', name: 'PT Emas Sentosa', code: 'CSBY-0010', primaryContact: 'PT Emas Sentosa', balance: 'IDR 595,800,000', category: 'Umum' },
    { id: 'CJKT-0002', name: 'PT Galaxy Phone', code: 'CJKT-0002', primaryContact: 'PT Galaxy Phone', balance: 'SGD 140,910', category: 'Umum' },
    { id: 'CSBY-0008', name: 'PT Global Makmur', code: 'CSBY-0008', primaryContact: 'PT Global Makmur', balance: 'IDR 149,600,000', category: 'Umum' },
    { id: 'CSBY-0009', name: 'PT Kapuk Kartika', code: 'CSBY-0009', primaryContact: 'PT Kapuk Kartika', balance: 'IDR 277,465,000', category: 'Umum' },
    { id: 'CSBY-0012', name: 'PT Kassakki Indo Baja', code: 'CSBY-0012', primaryContact: 'PT Kassakki Indo Baja', balance: 'IDR 0', category: 'Umum' },
    { id: 'CJKT-0009', name: 'PT Nusantara Indah', code: 'CJKT-0009', primaryContact: 'PT Nusantara Indah', balance: 'IDR 89,900,000', category: 'Umum' },
    { id: 'CJKT-0008', name: 'PT Sinar Bumi', code: 'CJKT-0008', primaryContact: 'PT Sinar Bumi', balance: 'IDR 423,200,000', category: 'Umum' },
    { id: 'CJKT-0010', name: 'PT Titik Terang', code: 'CJKT-0010', primaryContact: 'PT Titik Terang', balance: 'IDR 376,850,000', category: 'Umum' },
    { id: 'CJKT-0001', name: 'Pelanggan Umum - Jakarta', code: 'CJKT-0001', primaryContact: 'Pelanggan Umum - Jakarta', balance: 'IDR 88,350,000', category: 'Umum' },
];

const CUSTOMER_DEFAULTS = {
    autoCode: true,
    codeType: 'Pelanggan',
    name: '',
    code: '',
    category: [],
    businessPhone: '',
    mobilePhone: '',
    whatsapp: '',
    email: '',
    fax: '',
    website: '',
    billingStreet: '',
    billingCity: '',
    billingPostalCode: '',
    billingProvince: '',
    billingCountry: '',
    branchUsage: '[Semua Cabang]',
    currencies: ['Indonesian Rupiah'],
    contacts: [],
    shippingSameAsBilling: true,
    shippingStreet: '',
    shippingCity: '',
    shippingPostalCode: '',
    shippingProvince: '',
    shippingCountry: '',
    additionalAddresses: [],
    priceCategories: ['Umum'],
    discountCategory: [],
    paymentTerms: ['C.O.D'],
    defaultSalesPerson: [],
    defaultDiscountPercent: '',
    defaultDescription: '',
    consignment: false,
    accountReceivable: [],
    accountAdvance: [],
    accountSales: [],
    accountItemDiscount: [],
    accountCostOfSales: [],
    accountSalesReturn: [],
    accountSalesDiscount: [],
    taxIncluded: false,
    taxIdType: 'NIK',
    taxNumber: '',
    taxName: '',
    taxTkuId: '',
    taxCountry: [],
    taxTransactionType: 'Ditanggung',
    taxSameAsBilling: true,
    taxStreet: '',
    taxCity: '',
    taxPostalCode: '',
    taxProvince: '',
    taxCountryName: '',
    receivableRows: [],
    receivableLimitMode: 'per-customer',
    receivableAgeEnabled: false,
    receivableAgeDays: '0',
    receivableAmountEnabled: false,
    receivableAmount: 'Rp-0',
    mergeToParent: false,
    defaultWarehouse: [],
    notes: '',
    detailActionLabel: '',
};

const CUSTOMER_DETAIL_RECORDS = {
    'CSBY-0005': {
        autoCode: false,
        codeType: 'Pelanggan',
        name: 'Abadi Phone Center',
        code: 'CSBY-0005',
        category: ['Umum'],
        businessPhone: '021-3287663',
        mobilePhone: '',
        whatsapp: '',
        email: 'rikson93@gmail.com',
        fax: '021-3287664',
        website: '',
        billingStreet: 'Jl. Raya Pabean Sedati 79',
        billingCity: '',
        billingPostalCode: '',
        billingProvince: '',
        billingCountry: '',
        branchUsage: 'SURABAYA',
        currencies: ['Indonesian Rupiah'],
        contacts: [],
        shippingSameAsBilling: true,
        shippingStreet: '',
        shippingCity: '',
        shippingPostalCode: '',
        shippingProvince: '',
        shippingCountry: '',
        additionalAddresses: [],
        priceCategories: ['Umum'],
        discountCategory: [],
        paymentTerms: ['C.O.D'],
        defaultSalesPerson: [],
        defaultDiscountPercent: '',
        defaultDescription: '',
        consignment: false,
        accountReceivable: [],
        accountAdvance: [],
        accountSales: [],
        accountItemDiscount: [],
        accountCostOfSales: [],
        accountSalesReturn: [],
        accountSalesDiscount: [],
        taxIncluded: true,
        taxIdType: 'NIK',
        taxNumber: '',
        taxName: '',
        taxTkuId: '',
        taxCountry: [],
        taxTransactionType: 'Ditanggung',
        taxSameAsBilling: true,
        taxStreet: '',
        taxCity: '',
        taxPostalCode: '',
        taxProvince: '',
        taxCountryName: '',
        receivableRows: [],
        receivableLimitMode: 'per-customer',
        receivableAgeEnabled: false,
        receivableAgeDays: '0',
        receivableAmountEnabled: false,
        receivableAmount: 'Rp-0',
        mergeToParent: false,
        defaultWarehouse: [],
        notes: '',
        detailActionLabel: 'Piutang',
    },
};

export const customerBusinessPartnerTemplate = createTemplate({
    type: 'customer',
    tabs: [
        { id: 'general', label: 'Umum' },
        { id: 'contacts', label: 'Kontak' },
        { id: 'shipping', label: 'Pengiriman' },
        { id: 'sales', label: 'Penjualan' },
        { id: 'tax', label: 'Pajak' },
        { id: 'receivable', label: 'Saldo Piutang' },
        { id: 'others', label: 'Lain-lain' },
    ],
    table: createTableConfig({
        createLabel: 'Tambah Pelanggan',
        columns: [
            { id: 'name', label: 'Nama', widthClassName: 'w-[45%]', align: 'left' },
            { id: 'code', label: 'ID Pelanggan', widthClassName: 'w-[170px]', align: 'left' },
            { id: 'primaryContact', label: 'Kontak Utama', widthClassName: 'w-[18%]', align: 'left', truncate: true },
            { id: 'balance', label: 'Saldo', widthClassName: 'w-[22%]', align: 'right' },
        ],
        rows: CUSTOMER_ROWS,
        filters: [
            { id: 'inactive', rowKey: 'inactiveValue', options: [{ value: 'all', label: 'Non Aktif: Semua' }] },
            { id: 'category', rowKey: 'category', options: [{ value: 'all', label: 'Kategori: Semua' }, { value: 'Umum', label: 'Kategori: Umum' }] },
        ],
        pageValue: '23',
    }),
    labels: {
        ...SHARED_LABELS,
        code: 'ID Pelanggan',
        billingAddress: 'Alamat Penagihan',
        priceCategory: 'Kategori Harga',
        discountCategory: 'Kategori Diskon',
        paymentTerms: 'Syarat Pembayaran',
        defaultSalesPerson: 'Default Penjual',
        defaultDiscountPercent: 'Default Diskon (%)',
        defaultDescription: 'Default Deskripsi',
        consignment: 'Konsinyasi',
        receivable: 'Piutang',
        advance: 'Uang muka',
        sales: 'Penjualan',
        itemDiscount: 'Diskon Barang',
        costOfSales: 'Beban Pokok Penjualan',
        salesReturn: 'Retur Penjualan',
        salesDiscount: 'Diskon Penjualan',
        taxCountry: 'Kode Negara',
        defaultWarehouse: 'Gudang Default',
    },
    helperText: {
        salesAccountNote:
            '[Optional] Diisikan jika anda ingin membedakan jurnal akun piutang, uang muka, penjualan, retur penjualan, diskon barang penjualan, beban pokok penjualan dan akun diskon penjualan atas pelanggan ini dari default akunnya. Untuk dapat terpilih ke dalam transaksi, pastikan pengguna memiliki hak akses ke akun-akun ini',
    },
    headingLabels: {
        generalLeft: 'Info Umum',
        generalRight: 'Info lainnya',
        shippingLeft: 'Alamat Utama',
        shippingRight: 'Alamat lainnya',
        salesLeft: 'Penjualan',
        salesRight: 'Kustomisasi Akun Penjualan',
        taxLeft: 'Pajak',
        taxRight: 'Alamat',
        othersLimit: 'Pembatasan Piutang Pelanggan',
        othersOther: 'Lain-lain',
    },
    formDefaults: CUSTOMER_DEFAULTS,
    detailRecords: CUSTOMER_DETAIL_RECORDS,
});
