import {
    createTableConfig,
    createTemplate,
    SHARED_LABELS,
} from '@/features/workspace/modules/business-partner/businessPartnerConfigCore';

const SUPPLIER_ROWS = [];

const SUPPLIER_DEFAULTS = {
    autoCode: true,
    codeType: 'Pemasok',
    name: '',
    code: '',
    category: [],
    businessPhone: '',
    mobilePhone: '',
    whatsapp: '',
    email: '',
    fax: '',
    website: '',
    billingStreet: '',
    billingCity: '',
    billingPostalCode: '',
    billingProvince: '',
    billingCountry: '',
    branchUsage: '[Semua Cabang]',
    currencies: ['Indonesian Rupiah'],
    contacts: [],
    serviceVendor: false,
    supplierType: '- Pilih Tipe Pemasok -',
    paymentTerms: ['C.O.D'],
    defaultDiscountPercent: '',
    defaultDescription: '',
    payableAccount: [],
    advanceAccount: [],
    bankAccounts: [],
    taxIncluded: false,
    taxIdType: 'NIK',
    taxNumber: '',
    taxName: '',
    taxTkuId: '',
    taxTransactionType: 'Ditanggung',
    taxSameAsBilling: true,
    taxStreet: '',
    taxCity: '',
    taxPostalCode: '',
    taxProvince: '',
    taxCountryName: '',
    openingBalanceRows: [],
    invoiceNumberOnBill: true,
    notes: '',
    detailActionLabel: '',
};

const SUPPLIER_DETAIL_RECORDS = {};

export const supplierBusinessPartnerTemplate = createTemplate({
    type: 'supplier',
    tabs: [
        { id: 'general', label: 'Umum' },
        { id: 'purchase', label: 'Pembelian' },
        { id: 'tax', label: 'Pajak' },
    ],
    table: createTableConfig({
        createLabel: 'Tambah Pemasok',
        columns: [
            { id: 'name', label: 'Nama', widthClassName: 'w-[25%]', align: 'left' },
            { id: 'primaryContact', label: 'Kontak Utama', widthClassName: 'w-[130px]', align: 'left', truncate: true },
            { id: 'code', label: 'ID Pemasok', widthClassName: 'w-[140px]', align: 'left' },
            { id: 'balance', label: 'Saldo', widthClassName: 'w-[150px]', align: 'right' },
            
            // Kolom-kolom baru (default disembunyikan)
            { id: 'phone', label: 'Telepon Kantor', widthClassName: 'w-[130px]', align: 'left', defaultHidden: true, noWrap: true },
            { id: 'mobilePhone', label: 'Handphone', widthClassName: 'w-[130px]', align: 'left', defaultHidden: true, noWrap: true },
            { id: 'whatsapp', label: 'WhatsApp', widthClassName: 'w-[130px]', align: 'left', defaultHidden: true, noWrap: true },
            { id: 'email', label: 'Email', widthClassName: 'w-[180px]', align: 'left', defaultHidden: true },
            { id: 'taxNumber', label: 'NPWP / NIK', widthClassName: 'w-[150px]', align: 'left', defaultHidden: true },
            { id: 'paymentTermsText', label: 'Syarat Pembayaran', widthClassName: 'w-[150px]', align: 'left', defaultHidden: true },
            { id: 'creditLimitText', label: 'Batas Piutang', widthClassName: 'w-[150px]', align: 'right', defaultHidden: true, noWrap: true },
            { id: 'categoryName', label: 'Kategori', widthClassName: 'w-[130px]', align: 'left', defaultHidden: true },
            { id: 'notes', label: 'Catatan', widthClassName: 'w-[200px]', align: 'left', defaultHidden: true, truncate: true },
            { id: 'isActiveText', label: 'Non Aktif', widthClassName: 'w-[110px]', align: 'center', defaultHidden: true },
        ],
        rows: SUPPLIER_ROWS,
        filters: [
            { id: 'inactive', rowKey: 'inactiveValue', options: [{ value: 'all', label: 'Non Aktif: Semua' }] },
            { id: 'category', rowKey: 'category', options: [{ value: 'all', label: 'Kategori: Semua' }, { value: 'Umum', label: 'Kategori: Umum' }, { value: 'HANDPHONE', label: 'Kategori: HANDPHONE' }] },
        ],
        pageValue: '19',
    }),
    labels: {
        ...SHARED_LABELS,
        code: 'ID Pemasok',
        billingAddress: 'Alamat Pembayaran',
    },
    headingLabels: {
        generalLeft: 'Info Umum',
        generalRight: 'Info Lainnya',
        taxLeft: 'Pajak',
        taxRight: 'Alamat',
    },
    formDefaults: SUPPLIER_DEFAULTS,
    detailRecords: SUPPLIER_DETAIL_RECORDS,
    generalRightFields: [
        {
            id: 'serviceVendor',
            type: 'checkbox',
            label: 'Penjual Jasa',
            checkboxLabel: 'Ya, Penjual jasa orang pribadi (Dikenakan PPh 21)',
        },
        {
            id: 'supplierType',
            type: 'select',
            label: 'Tipe Pemasok',
            options: ['- Pilih Tipe Pemasok -'],
        },
    ],
    purchaseConfig: {
        titleLeft: 'Pembelian',
        titleRight: 'Rekening Bank',
        paymentTermsLabel: 'Syarat Pembayaran',
        discountLabel: 'Default Diskon (%)',
        descriptionLabel: 'Default Deskripsi',
        payableLabel: 'Akun Utang',
        advanceLabel: 'Akun Uang muka',
        bankAddLabel: 'Tambah rekening bank',
        accountNote:
            '[Optional] Diisikan jika anda ingin membedakan jurnal akun utang/uang muka yg ada pada Mata Uang. Untuk dapat terpilih ke dalam transaksi, pastikan pengguna memiliki hak akses ke akun-akun ini',
    },
    othersConfig: {
        title: 'Lain-lain',
        invoiceNumberLabel: 'Nomor Faktur',
        invoiceNumberCheckboxLabel: 'Ya, Pemasok memberikan nomor faktur pada tagihan',
        notesLabel: 'Catatan',
    },
});
