import { buildTodayDisplayDate } from '@/features/workspace/shared/dateDefaults';
import {
    createAttachmentDockAction,
    createDocumentDockAction,
    createMoreDockAction,
    createSaveDockAction,
} from '@/features/workspace/modules/shared/workspaceDockActions';
import { sharedDetailDockActions } from '@/features/workspace/modules/sales-document/salesDocumentConfigCore';

const todayDisplayDate = buildTodayDisplayDate();

export const purchaseInvoiceSectionTabs = [
    { id: 'details', label: 'Rincian Barang', icon: 'document' },
    { id: 'additional-info', label: 'Info lainnya', icon: 'info' },
    { id: 'additional-costs', label: 'Biaya Lainnya', icon: 'payment' },
];

const purchaseInvoiceListColumns = [
    { id: 'number', label: 'Nomor #', widthClassName: 'w-[200px]', align: 'left' },
    { id: 'billNumber', label: 'No Faktur #', widthClassName: 'w-[150px]', align: 'left' },
    { id: 'date', label: 'Tanggal', widthClassName: 'w-[120px]', align: 'left' },
    { id: 'customerShort', label: 'Pemasok', widthClassName: 'w-[200px]', align: 'left' },
    { id: 'notes', label: 'Keterangan', widthClassName: 'w-[48%]', align: 'left' },
    { id: 'status', label: 'Status', widthClassName: 'w-[150px]', align: 'left' },
    { id: 'age', label: 'Umur (hr)', widthClassName: 'w-[100px]', align: 'right' },
    { id: 'total', label: 'Total', widthClassName: 'w-[160px]', align: 'right' },
];

const purchaseInvoiceItemColumns = [
    { id: 'name', label: 'Nama Barang', widthClassName: 'w-[56%]', align: 'left' },
    { id: 'code', label: 'Kode #', widthClassName: 'w-[120px]', align: 'center' },
    { id: 'quantity', label: 'Kuantitas', widthClassName: 'w-[92px]', align: 'right' },
    { id: 'unit', label: 'Satuan', widthClassName: 'w-[82px]', align: 'center' },
    { id: 'price', label: '@Harga', widthClassName: 'w-[108px]', align: 'right' },
    { id: 'discount', label: 'Diskon', widthClassName: 'w-[82px]', align: 'right' },
    { id: 'total', label: 'Total Harga', widthClassName: 'w-[132px]', align: 'right' },
];

const purchaseInvoiceCostColumns = [
    { id: 'name', label: 'Nama Biaya', widthClassName: 'w-[58%]', align: 'left' },
    { id: 'code', label: 'Kode #', widthClassName: 'w-[120px]', align: 'center' },
    { id: 'amount', label: 'Jumlah', widthClassName: 'w-[120px]', align: 'right' },
    { id: 'notes', label: 'Keterangan', widthClassName: 'w-[22%]', align: 'left' },
];

const purchaseInvoiceTableRows = [];

export const purchaseInvoiceCreateDockActions = [
    createSaveDockAction(),
    createDocumentDockAction(),
    createAttachmentDockAction({ itemId: 'upload', itemLabel: 'Tambah lampiran' }),
    createMoreDockAction({ itemId: 'duplicate', itemLabel: 'Duplikasi faktur pembelian' }),
];

const defaultPurchaseInvoiceDraft = {
    customer: [],
    entryDate: todayDisplayDate,
    autoNumber: true,
    numberingType: 'Faktur Pembelian',
    documentNumber: '',
    currency: '',
    exchangeRate: '',
    exchangeRateLabel: '',
    exchangeRatePrefix: 'Rp',
    secondaryExchangeRate: '',
    secondaryExchangeRatePrefix: 'Pjk',
    itemSearch: '',
    items: [],
    itemCountLabel: 'Rincian Barang',
    preInvoice: false,
    bankAccounts: [],
    purchaseOrderNumber: '',
    address: '',
    notes: '',
    taxEnabled: false,
    taxIncluded: false,
    shippingDate: todayDisplayDate,
    costSearch: '',
    additionalCosts: [],
    summary: [
        ['Total', 'Rp 0'],
        ['Uang Muka', 'Rp 0'],
        ['Pembayaran', 'Rp 0'],
        ['Retur', 'Rp 0'],
        ['Utang', 'Rp 0'],
        ['Utang Pajak', 'Rp 0'],
        ['Status', '-'],
        ['Dicetak/email', 'Belum cetak/email'],
    ],
    summaryStatusTone: 'warning',
    processedBy: null,
    approvalStamp: '',
    processStamp: '',
    processStampTone: 'gray',
    showSecondaryHeaderAction: false,
    showProcessButton: false,
    showProcessButtonOnCreate: true,
    processDisabled: false,
    subtotal: '0',
    discountValue: '0',
    discountPrefix: '',
    taxLabel: '',
    taxValue: '',
    total: '0',
    itemModal: {
        title: 'Rincian Barang',
        tabs: [
            { id: 'details', label: 'Rincian Barang' },
            { id: 'info', label: 'Info lainnya' },
        ],
        values: {
            code: '',
            name: '',
            quantity: '',
            unit: [],
            price: '',
            discountPercent: '',
            discountValue: '0',
            total: '0',
            taxChecked: false,
            taxLabel: 'PPN 10 %',
            warehouse: [],
            salesPerson: [],
            department: [],
            notes: '',
        },
    },
    dockActions: purchaseInvoiceCreateDockActions,
};

const purchaseInvoiceDetailRecords = {};

export const defaultPurchaseInvoiceConfig = {
    labels: {
        customer: 'Pemasok',
        entryDate: 'Tanggal',
        documentNumber: 'No Form #',
        preInvoice: 'Tagihan Dimuka',
        paymentTerms: 'Syarat Pembayaran',
        purchaseOrderNumber: 'No Faktur #',
        address: 'Alamat',
        branch: 'Cabang',
        notes: 'Keterangan',
        tax: 'Pajak',
        shippingDate: 'Tgl Pengiriman',
        shippingMethod: 'Pengiriman',
        fob: 'FOB',
        exchangeRate: 'Kurs',
    },
    numberingOptions: ['Faktur Pembelian'],
    customerPlaceholder: 'Cari/Pilih Pemasok...',
    customerSearchLabel: 'Cari pemasok',
    table: {
        createLabel: 'Tambah Faktur Pembelian',
        refreshLabel: 'Muat ulang',
        filterButtonLabel: 'Filter lanjutan',
        searchPlaceholder: 'Cari...',
        pageValue: '56',
        columns: purchaseInvoiceListColumns,
        rows: purchaseInvoiceTableRows,
        filters: [
            { id: 'date', rowKey: 'date', options: [{ value: 'all', label: 'Tanggal: Semua' }, { value: '18/01/2017', label: 'Tanggal: 18/01/2017' }] },
            { id: 'customer', rowKey: 'customer', options: [{ value: 'all', label: 'Pemasok: Semua' }, { value: 'Applus', label: 'Pemasok: Applus' }, { value: 'CV Ganda Putra', label: 'Pemasok: CV Ganda Putra' }] },
            { id: 'status', rowKey: 'status', options: [{ value: 'all', label: 'Status: Semua' }, { value: 'Belum Lunas', label: 'Status: Belum Lunas' }, { value: 'Lunas', label: 'Status: Lunas' }] },
            { id: 'printed', rowKey: 'printedStatus', options: [{ value: 'all', label: 'Sudah dicetak: Semua' }, { value: 'all', label: 'Sudah dicetak: Semua' }] },
        ],
        downloadItems: [{ id: 'download-excel', label: 'Unduh Excel' }],
        printItems: [{ id: 'print-list', label: 'Cetak daftar faktur pembelian' }],
        settingsItems: [{ id: 'arrange-columns', label: 'Atur kolom' }],
    },
    sectionTabs: purchaseInvoiceSectionTabs,
    itemSearchPlaceholder: 'Cari/Pilih Barang & Jasa...',
    itemSectionTitle: 'Rincian Barang',
    itemTable: {
        columns: purchaseInvoiceItemColumns,
        emptyLabel: 'Belum ada data',
        minWidthClassName: 'min-w-[1080px]',
    },
    costSearchPlaceholder: 'Cari/Pilih Akun Perkiraan...',
    additionalCostsTitle: 'Biaya Lainnya',
    costTable: {
        columns: purchaseInvoiceCostColumns,
        emptyLabel: 'Belum ada data',
    },
    additionalInfoTitle: 'Info lainnya',
    taxInfoTitle: 'Info Pajak',
    shippingInfoTitle: 'Info Pengiriman',
    extraInfoTitle: 'Info Tambahan',
    orderInfoTitle: 'Informasi Faktur',
    processedByTitle: 'Diproses Oleh',
    processedByEmptyLabel: 'Belum ada transaksi lanjutan.',
    showSummarySecondarySection: false,
    showPreInvoiceOption: true,
    preInvoiceOptionLabel: 'Ya (Mendahului Terima Barang)',
    showAddressPinButton: true,
    showPaymentTerms: true,
    showPurchaseOrderNumber: true,
    showTaxInfo: true,
    showShippingInfo: true,
    showExtraInfo: true,
    showFobInShippingInfo: false,
    showFobInAdditionalInfo: true,
    additionalInfoLookupFields: [
        {
            type: 'lookup',
            label: 'Rekening Bank',
            valueKey: 'bankAccounts',
            placeholder: 'Rekening Bank',
            searchLabel: 'Cari rekening bank',
        },
    ],
    itemModal: {
        enabled: true,
    },
    itemSearchResource: 'products',
    hideAddItemButton: true,
    hideImportButton: true,
    secondaryActionLabel: '',
    showSecondaryHeaderAction: false,
    showFooter: true,
    initialSectionId: 'details',
    detailInitialSectionId: 'details',
    takeButtonLabel: 'Ambil',
    processButtonLabel: 'Proses',
    showProcessButtonOnCreate: true,
    draft: defaultPurchaseInvoiceDraft,
    detailRecords: purchaseInvoiceDetailRecords,
};
