import {
    createAttachmentDockAction,
    createDocumentDockAction,
    createMoreDockAction,
    createSaveDockAction,
} from '@/features/workspace/modules/shared/workspaceDockActions';
import {
    buildSalesDocumentRecord,
    mergeSalesDocumentConfigWithPage,
    sharedDetailDockActions,
} from '@/features/workspace/modules/sales-document/salesDocumentConfigCore';
import {
    defaultSalesOrderConfig,
    salesDeliveryItemColumns,
    salesDeliveryListColumns,
    salesDeliverySectionTabs,
    salesOrderDraft,
} from '@/features/workspace/modules/sales-document/salesOrderModuleConfig';

const salesDeliveryTableRows = [
    { id: 'DO.2017.02.00001', number: 'DO.2017.02.00001', date: '10/02/2017', customer: 'Abadi Phone Center', customerShort: 'Abadi Phone Center', shipping: '', shippingShort: '', notes: '', status: 'Difaktur', statusTone: 'processed' },
    { id: 'DO.2017.01.00001', number: 'DO.2017.01.00001', date: '17/01/2017', customer: 'Pelanggan Umum - Surabaya', customerShort: 'Pelanggan Umum - Sur...', shipping: '', shippingShort: '', notes: '', status: 'Difaktur Sebagian', statusTone: 'partial' },
    { id: 'DO.2017.01.00002', number: 'DO.2017.01.00002', date: '10/01/2017', customer: 'Pelanggan Umum - Surabaya', customerShort: 'Pelanggan Umum - Sur...', shipping: '', shippingShort: '', notes: '', status: 'Difaktur Sebagian', statusTone: 'partial' },
    { id: 'DO.2016.12.00002', number: 'DO.2016.12.00002', date: '13/12/2016', customer: 'Cinema Phone Cellular', customerShort: 'Cinema Phone Cellular', shipping: '', shippingShort: '', notes: '', status: 'Difaktur', statusTone: 'processed' },
    { id: 'DO.2016.12.00001', number: 'DO.2016.12.00001', date: '13/12/2016', customer: 'Abadi Phone Center', customerShort: 'Abadi Phone Center', shipping: '', shippingShort: '', notes: '', status: 'Difaktur', statusTone: 'processed' },
    { id: 'DO.2016.11.00002', number: 'DO.2016.11.00002', date: '20/11/2016', customer: 'PT Kapuk Kartika', customerShort: 'PT Kapuk Kartika', shipping: '', shippingShort: '', notes: '', status: 'Difaktur Sebagian', statusTone: 'partial' },
    { id: 'DO.2016.11.00001', number: 'DO.2016.11.00001', date: '14/11/2016', customer: 'Nasional Phone Jaya', customerShort: 'Nasional Phone Jaya', shipping: '', shippingShort: '', notes: '', status: 'Difaktur Sebagian', statusTone: 'partial' },
    { id: 'DO.2016.10.00001', number: 'DO.2016.10.00001', date: '15/10/2016', customer: 'PT Sinar Bumi', customerShort: 'PT Sinar Bumi', shipping: '', shippingShort: '', notes: '', status: 'Difaktur Sebagian', statusTone: 'partial' },
    { id: 'DO.2017.02.00002', number: 'DO.2017.02.00002', date: '15/10/2016', customer: 'PT Galaxy Phone', customerShort: 'PT Galaxy Phone', shipping: '', shippingShort: '', notes: '', status: 'Difaktur Sebagian', statusTone: 'partial' },
];

const salesDeliveryDraft = {
    ...salesOrderDraft,
    customer: [],
    entryDate: salesOrderDraft.entryDate,
    numberingType: 'Pengiriman Pesanan',
    documentNumber: '',
    currency: '',
    paymentTerms: [],
    purchaseOrderNumber: '',
    address: '',
    branches: ['JAKARTA'],
    notes: '',
    shippingMethod: [],
    fob: [],
    items: [],
    itemCountLabel: 'Rincian Barang',
    summary: [
        ['Status', '-'],
        ['Dicetak/email', 'Belum cetak/email'],
    ],
    processedBy: null,
    approvalStamp: '',
    processStamp: '',
    showProcessButton: false,
    processDisabled: false,
    subtotal: '0',
    discountValue: '0',
    discountPrefix: '',
    taxLabel: '',
    taxValue: '',
    total: '0',
    saveTone: 'primary',
    itemModal: {
        title: 'Rincian Barang',
        tabs: [
            { id: 'details', label: 'Rincian Barang' },
            { id: 'info', label: 'Info lainnya' },
        ],
        values: {
            code: '',
            name: '',
            quantity: '',
            unit: '',
            warehouse: '',
            invoicedLabel: 'Kts. Difaktur',
            invoicedQuantity: '',
            department: [],
            notes: '',
            quoteNumber: '',
            orderNumber: '',
        },
    },
    dockActions: [
        createSaveDockAction(),
        createDocumentDockAction(),
        createAttachmentDockAction({ itemId: 'upload', itemLabel: 'Tambah lampiran' }),
        createMoreDockAction({ itemId: 'duplicate', itemLabel: 'Duplikasi pengiriman' }),
    ],
};

const salesDeliveryDetailRecords = {
    'DO.2017.02.00001': {
        customer: ['[CSBY-0005] Abadi Phone Center'],
        entryDate: '10/02/2017',
        autoNumber: false,
        numberingType: 'Pengiriman Pesanan',
        documentNumber: 'DO.2017.02.00001',
        currency: 'IDR',
        itemSearch: '',
        items: [
            {
                id: 'DO.2017.02.00001-item-1',
                name: 'Anti Gores Iphone 5',
                code: '9900012',
                quantity: '25',
                unit: 'PCS',
            },
        ],
        itemCountLabel: '1 Barang (25)',
        paymentTerms: [],
        purchaseOrderNumber: '',
        address: 'Jl. Raya Pabean Sedati 79',
        branches: ['JAKARTA'],
        notes: '',
        taxEnabled: false,
        taxIncluded: false,
        shippingDate: '',
        shippingMethod: [],
        fob: [],
        costSearch: '',
        additionalCosts: [],
        summary: [
            ['Status', 'Difaktur'],
            ['Dicetak/email', 'Belum cetak/email'],
        ],
        processedBy: {
            number: 'SI.2017.02.00003',
            date: '10/02/2017',
        },
        approvalStamp: 'DISETUJUI',
        processStamp: '',
        showProcessButton: false,
        processDisabled: false,
        subtotal: '0',
        discountValue: '0',
        discountPrefix: '',
        taxLabel: '',
        taxValue: '',
        total: '0',
        saveTone: 'muted',
        itemModal: {
            title: 'Rincian Barang',
            tabs: [
                { id: 'details', label: 'Rincian Barang' },
                { id: 'info', label: 'Info lainnya' },
            ],
            values: {
                code: '9900012',
                name: 'Anti Gores Iphone 5',
                quantity: '25',
                unit: 'PCS',
                warehouse: 'GD. JAKARTA',
                invoicedLabel: 'Kts. Difaktur',
                invoicedQuantity: '25 PCS',
                department: [],
                notes: '',
                quoteNumber: 'SQ.2017.02.00001',
                orderNumber: 'SO.2017.02.00001',
            },
        },
        dockActions: sharedDetailDockActions,
    },
};

export const defaultSalesDeliveryConfig = {
    ...defaultSalesOrderConfig,
    labels: {
        ...defaultSalesOrderConfig.labels,
        customer: 'Kirim ke',
        documentNumber: 'No Pengiriman #',
        shippingMethod: 'Pengiriman',
    },
    numberingOptions: ['Pengiriman Pesanan'],
    table: {
        ...defaultSalesOrderConfig.table,
        createLabel: 'Tambah Pengiriman Pesanan',
        pageValue: '9',
        columns: salesDeliveryListColumns,
        rows: salesDeliveryTableRows,
        filters: [
            { id: 'date', rowKey: 'date', options: [{ value: 'all', label: 'Tanggal: Semua' }, { value: '10/02/2017', label: 'Tanggal: 10/02/2017' }] },
            { id: 'shipping', rowKey: 'shipping', options: [{ value: 'all', label: 'Pengiriman: Semua' }, { value: '', label: 'Pengiriman: Semua' }] },
            { id: 'status', rowKey: 'status', options: [{ value: 'all', label: 'Status: Semua' }, { value: 'Difaktur', label: 'Status: Difaktur' }, { value: 'Difaktur Sebagian', label: 'Status: Difaktur Sebagian' }] },
            { id: 'customer', rowKey: 'customer', options: [{ value: 'all', label: 'Kirim ke: Semua' }, { value: 'Abadi Phone Center', label: 'Kirim ke: Abadi Phone Center' }] },
        ],
        downloadItems: [],
        printItems: [{ id: 'print-list', label: 'Cetak daftar pengiriman' }],
        settingsItems: [{ id: 'arrange-columns', label: 'Atur kolom' }],
    },
    sectionTabs: salesDeliverySectionTabs,
    headerLookupField: {
        label: 'Pengiriman',
        valueKey: 'shippingMethod',
        placeholder: 'Cari/Pilih...',
        searchLabel: 'Cari pengiriman',
    },
    itemSectionTitle: 'Rincian Barang',
    itemTable: {
        columns: salesDeliveryItemColumns,
        emptyLabel: 'Belum ada data',
        minWidthClassName: 'min-w-[1040px]',
    },
    additionalInfoTitle: 'Info lainnya',
    showPaymentTerms: false,
    showTaxInfo: false,
    showShippingInfo: false,
    showExtraInfo: true,
    showAddressPinButton: true,
    additionalCostsTitle: 'Biaya Lainnya',
    orderInfoTitle: 'Informasi Pengiriman',
    processButtonLabel: 'Proses',
    showPurchaseOrderNumber: true,
    showFooter: false,
    itemModal: {
        enabled: true,
    },
    draft: salesDeliveryDraft,
    detailRecords: salesDeliveryDetailRecords,
};

export function buildSalesDeliveryConfig(pageConfig = {}) {
    return mergeSalesDocumentConfigWithPage(defaultSalesDeliveryConfig, pageConfig);
}

export function buildSalesDeliveryRecord(row = {}) {
    return buildSalesDocumentRecord(row, salesDeliveryDraft, salesDeliveryDetailRecords, {
        customerPrefix: '[CSBY-0005]',
        includeAdvanceSummary: false,
        includePrintedSummary: true,
        dockActions: sharedDetailDockActions,
        showProcessButton: false,
        processStamp: '',
    });
}
