import {
    createAttachmentDockAction,
    createDocumentDockAction,
    createMoreDockAction,
    createSaveDockAction,
} from '@/features/workspace/modules/shared/workspaceDockActions';
import {
    buildSalesDocumentRecord,
    mergeSalesDocumentConfigWithPage,
    sharedDetailDockActions,
} from '@/features/workspace/modules/sales-document/salesDocumentConfigCore';
import {
    defaultSalesOrderConfig,
    salesInvoiceAdvanceColumns,
    salesInvoiceListColumns,
    salesInvoiceSectionTabs,
    salesOrderDraft,
} from '@/features/workspace/modules/sales-document/salesOrderModuleConfig';
import { buildTodayDisplayDate } from '@/features/workspace/shared/dateDefaults';

const todayDisplayDate = buildTodayDisplayDate();

const salesInvoiceTableRows = [
    { id: 'SI.2017.02.00010', number: 'SI.2017.02.00010', date: '10/02/2017', customer: 'Abadi Phone Center', customerShort: 'Abadi Phone Center', notes: '', status: 'Belum Lunas', requiredIdType: '', age: '3362', total: '2,059,200,000', statusTone: 'pending' },
    { id: 'SI.2017.02.00007', number: 'SI.2017.02.00007', date: '10/02/2017', customer: 'Pelanggan Umum - Jakarta', customerShort: 'Pelanggan Umum - Jak...', notes: '', status: 'Lunas', requiredIdType: '', age: '0', total: '6,600,000', statusTone: 'processed' },
    { id: 'SI.2017.02.00005', number: 'SI.2017.02.00005', date: '10/02/2017', customer: 'Pelanggan Umum - Jakarta', customerShort: 'Pelanggan Umum - Jak...', notes: '', status: 'Lunas', requiredIdType: '', age: '14', total: '17,600,000', statusTone: 'processed' },
    { id: 'SI.2017.02.00004', number: 'SI.2017.02.00004', date: '10/02/2017', customer: 'PT CIRCLE PHONE', customerShort: 'PT CIRCLE PHONE', notes: '', status: 'Belum Lunas', requiredIdType: '', age: '3362', total: '16,440', statusTone: 'pending' },
    { id: 'SI.2017.02.00003', number: 'SI.2017.02.00003', date: '10/02/2017', customer: 'Abadi Phone Center', customerShort: 'Abadi Phone Center', notes: '', status: 'Lunas', requiredIdType: '', age: '0', total: '1,925,000', statusTone: 'processed' },
    { id: 'SI.2017.01.00010', number: 'SI.2017.01.00010', date: '29/01/2017', customer: 'Pelanggan Umum - Jakarta', customerShort: 'Pelanggan Umum - Jak...', notes: '', status: 'Belum Lunas', requiredIdType: '', age: '3374', total: '64,350,000', statusTone: 'pending' },
    { id: 'SI.2017.01.00002', number: 'SI.2017.01.00002', date: '17/01/2017', customer: 'Cinema Phone Cellular', customerShort: 'Cinema Phone Cellular', notes: '', status: 'Belum Lunas', requiredIdType: '', age: '3386', total: '500,000', statusTone: 'pending' },
    { id: 'SI.2017.01.00001', number: 'SI.2017.01.00001', date: '17/01/2017', customer: 'Abadi Phone Center', customerShort: 'Abadi Phone Center', notes: '', status: 'Belum Lunas', requiredIdType: '', age: '3386', total: '500,000', statusTone: 'pending' },
    { id: 'SI.2017.01.00009', number: 'SI.2017.01.00009', date: '15/01/2017', customer: 'Global Phone Jaya', customerShort: 'Global Phone Jaya', notes: '', status: 'Belum Lunas', requiredIdType: '', age: '3388', total: '137,060,000', statusTone: 'pending' },
    { id: 'SI.2017.01.00007', number: 'SI.2017.01.00007', date: '15/01/2017', customer: 'PT Emas Sentosa', customerShort: 'PT Emas Sentosa', notes: '', status: 'Belum Lunas', requiredIdType: '', age: '3388', total: '216,000,000', statusTone: 'pending' },
    { id: 'SI.2017.01.00008', number: 'SI.2017.01.00008', date: '11/01/2017', customer: 'Abadi Phone Center', customerShort: 'Abadi Phone Center', notes: '', status: 'Belum Lunas', requiredIdType: '', age: '3392', total: '95,040,000', statusTone: 'pending' },
    { id: 'SI.2017.02.00009', number: 'SI.2017.02.00009', date: '10/01/2017', customer: 'PT Galaxy Phone', customerShort: 'PT Galaxy Phone', notes: '', status: 'Belum Lunas', requiredIdType: '', age: '3393', total: '114,000', statusTone: 'pending' },
    { id: 'SI.2017.01.00005', number: 'SI.2017.01.00005', date: '10/01/2017', customer: 'Pelanggan Umum - Surabaya', customerShort: 'Pelanggan Umum - Sur...', notes: '', status: 'Belum Lunas', requiredIdType: '', age: '3393', total: '33,600,000', statusTone: 'pending' },
    { id: 'SI.2017.01.00004', number: 'SI.2017.01.00004', date: '10/01/2017', customer: 'Pelanggan Umum - Jakarta', customerShort: 'Pelanggan Umum - Jak...', notes: '', status: 'Belum Lunas', requiredIdType: '', age: '3393', total: '21,600,000', statusTone: 'pending' },
    { id: 'SI.2017.01.00003', number: 'SI.2017.01.00003', date: '10/01/2017', customer: 'PT Kassakki Indo Baja', customerShort: 'PT Kassakki Indo Baja', notes: '', status: 'Lunas', requiredIdType: '', age: '0', total: '814,000', statusTone: 'processed' },
    { id: 'SI.2017.01.00006', number: 'SI.2017.01.00006', date: '05/01/2017', customer: 'Global Phone Jaya', customerShort: 'Global Phone Jaya', notes: '', status: 'Belum Lunas', requiredIdType: '', age: '3398', total: '37,950,000', statusTone: 'pending' },
    { id: 'SI.2017.02.00006', number: 'SI.2017.02.00006', date: '20/12/2016', customer: 'Global Phone Jaya', customerShort: 'Global Phone Jaya', notes: '', status: 'Belum Lunas', requiredIdType: '', age: '3414', total: '83,700', statusTone: 'pending' },
    { id: 'SI.2016.12.00003', number: 'SI.2016.12.00003', date: '13/12/2016', customer: 'Cinema Phone Cellular', customerShort: 'Cinema Phone Cellular', notes: '', status: 'Lunas', requiredIdType: '', age: '0', total: '25,960,000', statusTone: 'processed' },
    { id: 'SI.2016.12.00001', number: 'SI.2016.12.00001', date: '13/12/2016', customer: 'Abadi Phone Center', customerShort: 'Abadi Phone Center', notes: '', status: 'Belum Lunas', requiredIdType: '', age: '3421', total: '13,750,000', statusTone: 'pending' },
];

const salesInvoiceDraft = {
    ...salesOrderDraft,
    numberingType: 'Faktur Penjualan',
    paymentTerms: [],
    shippingDate: todayDisplayDate,
    preInvoice: false,
    contacts: [],
    taxInvoiceDate: '',
    taxTransactionType: 'Faktur Pajak',
    taxDetailTransaction: '01 - Bukan Pemungut PPN (legacy)',
    taxPayerMode: 'Auto',
    taxPayerNumber: '',
    taxPayerName: '',
    taxIdTku: '',
    taxInvoiceNumber: '',
    advancePaymentSearch: '',
    advancePayments: [],
    dockActions: [
        createSaveDockAction(),
        createDocumentDockAction(),
        createAttachmentDockAction({ itemId: 'upload', itemLabel: 'Tambah lampiran' }),
        createMoreDockAction({ itemId: 'smartlink', itemLabel: 'Kelola e-payment' }),
    ],
};

const salesInvoiceDetailRecords = {
    'SI.2017.02.00010': {
        customer: ['[CSBY-0005] Abadi Phone Center'],
        entryDate: '10/02/2017',
        autoNumber: false,
        numberingType: 'Faktur Penjualan',
        documentNumber: 'SI.2017.02.00010',
        currency: 'IDR',
        itemSearch: '',
        items: [
            {
                id: 'SI.2017.02.00010-item-1',
                name: 'Iphone 6 32 GB',
                code: '6116001',
                quantity: '120',
                unit: 'PCS',
                price: '15,600,000',
                discount: '0',
                total: '1,872,000,000',
            },
        ],
        itemCountLabel: '1 Barang (120)',
        preInvoice: false,
        paymentTerms: ['C.O.D'],
        purchaseOrderNumber: '',
        address: 'Jl. Raya Pabean Sedati 79',
        branches: ['JAKARTA'],
        notes: '',
        contacts: [],
        taxEnabled: true,
        taxIncluded: false,
        taxInvoiceDate: '10/02/2017',
        taxTransactionType: 'Faktur Pajak',
        taxDetailTransaction: '01 - Bukan Pemungut PPN (legacy)',
        taxPayerMode: 'Auto',
        taxPayerNumber: 'NPWP : 75.618.618.6-168.000',
        taxPayerName: 'Abadi Phone Center',
        taxIdTku: '',
        taxInvoiceNumber: '010.900-17.00000011',
        shippingDate: '10/02/2017',
        shippingMethod: [],
        fob: [],
        costSearch: '',
        additionalCosts: [],
        advancePaymentSearch: '',
        advancePayments: [],
        summary: [
            ['Total', 'Rp 2,059,200,000'],
            ['Uang Muka', 'Rp 0'],
            ['Pembayaran', 'Rp 0'],
            ['Retur', 'Rp 0'],
            ['Piutang', 'Rp 2,059,200,000'],
            ['Status', 'Belum Lunas'],
            ['Dicetak/email', 'Belum cetak/email'],
        ],
        summaryStatusTone: 'warning',
        processedBy: [],
        approvalStamp: 'DISETUJUI',
        processStamp: 'BELUM\nLUNAS',
        processStampTone: 'gray',
        showProcessButton: true,
        processDisabled: false,
        subtotal: 'Rp 1,872,000,000',
        discountValue: '0',
        discountPrefix: 'Rp',
        taxLabel: 'PPN 10%',
        taxValue: 'Rp 187,200,000',
        total: 'Rp 2,059,200,000',
        saveTone: 'muted',
        itemModal: {
            title: 'Rincian Barang',
            tabs: [
                { id: 'details', label: 'Rincian Barang' },
                { id: 'serial', label: 'No Seri/Produksi' },
                { id: 'info', label: 'Info lainnya' },
            ],
            values: {
                code: '6116001',
                name: 'Iphone 6 32 GB',
                quantity: '120',
                unit: ['PCS'],
                price: '15,600,000',
                discountPercent: '',
                discountValue: '0',
                total: 'Rp 1,872,000,000',
                taxChecked: true,
                taxLabel: 'PPN 10 %',
                warehouse: ['GD. JAKARTA'],
                salesPerson: [],
                department: [],
                notes: '',
                serialInput: '',
                serialNumbers: ['09281381605', '09281381612', '09281381613', '09281381614', '09281381615', '09281381616'],
                serialCountLabel: '120 No Seri/Produksi',
            },
        },
        dockActions: sharedDetailDockActions,
    },
};

export const defaultSalesInvoiceConfig = {
    ...defaultSalesOrderConfig,
    labels: {
        ...defaultSalesOrderConfig.labels,
        customer: 'Pelanggan',
        documentNumber: 'No Faktur #',
        preInvoice: 'Faktur Dimuka',
        contact: 'Kontak',
    },
    numberingOptions: ['Faktur Penjualan'],
    table: {
        ...defaultSalesOrderConfig.table,
        createLabel: 'Tambah Faktur Penjualan',
        rows: salesInvoiceTableRows,
        pageValue: '54',
        columns: salesInvoiceListColumns,
        filters: [
            { id: 'date', rowKey: 'date', options: [{ value: 'all', label: 'Tanggal: Semua' }, { value: '10/02/2017', label: 'Tanggal: 10/02/2017' }] },
            { id: 'customer', rowKey: 'customer', options: [{ value: 'all', label: 'Pelanggan: Semua' }, { value: 'Abadi Phone Center', label: 'Pelanggan: Abadi Phone Center' }] },
            { id: 'status', rowKey: 'status', options: [{ value: 'all', label: 'Status: Semua' }, { value: 'Belum Lunas', label: 'Status: Belum Lunas' }, { value: 'Lunas', label: 'Status: Lunas' }] },
            { id: 'printed', rowKey: 'printedStatus', options: [{ value: 'all', label: 'Sudah dicetak: Semua' }, { value: 'all', label: 'Sudah dicetak: Semua' }] },
        ],
        printItems: [{ id: 'print-list', label: 'Cetak daftar faktur' }],
    },
    sectionTabs: salesInvoiceSectionTabs,
    additionalInfoTitle: 'Info lainnya',
    advancePaymentTitle: 'Uang Muka',
    advancePaymentSearchPlaceholder: 'Cari/Pilih...',
    advancePaymentTable: {
        columns: salesInvoiceAdvanceColumns,
        emptyLabel: 'Belum ada data',
        minWidthClassName: 'min-w-[760px]',
    },
    orderInfoTitle: 'Informasi Faktur',
    processedByTitle: 'Uang Muka Terpakai/Retur',
    processedByEmptyLabel: 'Belum ada data.',
    showSummarySecondarySection: false,
    showPreInvoiceOption: true,
    showContactField: true,
    showAddressPinButton: true,
    taxInfoMode: 'invoice',
    itemModal: {
        enabled: true,
    },
    draft: salesInvoiceDraft,
    detailRecords: salesInvoiceDetailRecords,
};

export function buildSalesInvoiceConfig(pageConfig = {}) {
    return mergeSalesDocumentConfigWithPage(defaultSalesInvoiceConfig, pageConfig);
}

export function buildSalesInvoiceRecord(row = {}) {
    return buildSalesDocumentRecord(row, salesInvoiceDraft, salesInvoiceDetailRecords, {
        customerPrefix: '[CSBY-0005]',
        includeAdvanceSummary: false,
        includePrintedSummary: true,
        dockActions: sharedDetailDockActions,
        approvalStamp: 'DISETUJUI',
        processStamp: 'BELUM\nLUNAS',
        taxLabel: 'PPN 10%',
        taxValue: 'Rp 0',
    });
}
