<?php

namespace App\Support\Presentation\Blueprints\Pages;

class ActivityLogTable
{
    public static function rows(): array
    {
        return array_merge(
            self::part1(),
            self::part2()
        );
    }

    private static function part1(): array
    {
        return [
[
                                'id' => 'activity-log-1',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Perintah Pembayaran - Default',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'print-design',
                                'transactionTypeLabel' => 'Desain Cetakan',
                                'loggedAt' => '18 Apr 2026 21:42:59',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-2',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Alokasi Bahan Proyek',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'numbering',
                                'transactionTypeLabel' => 'Penomoran',
                                'loggedAt' => '18 Apr 2026 21:42:59',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-3',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Faktur Pesanan - Default Trade Portal',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'print-design',
                                'transactionTypeLabel' => 'Desain Cetakan',
                                'loggedAt' => '18 Apr 2026 21:42:59',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-4',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Check In',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'numbering',
                                'transactionTypeLabel' => 'Penomoran',
                                'loggedAt' => '18 Apr 2026 21:42:59',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-5',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Pelunasan Pinjaman - Default',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'print-design',
                                'transactionTypeLabel' => 'Desain Cetakan',
                                'loggedAt' => '18 Apr 2026 21:42:59',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-6',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Pembayaran Angsuran - Default',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'print-design',
                                'transactionTypeLabel' => 'Desain Cetakan',
                                'loggedAt' => '18 Apr 2026 21:42:59',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-7',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Pelunasan Pinjaman',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'numbering',
                                'transactionTypeLabel' => 'Penomoran',
                                'loggedAt' => '18 Apr 2026 21:42:59',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-8',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Pembayaran Angsuran',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'numbering',
                                'transactionTypeLabel' => 'Penomoran',
                                'loggedAt' => '18 Apr 2026 21:42:59',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-9',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Pencairan Pinjaman',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'numbering',
                                'transactionTypeLabel' => 'Penomoran',
                                'loggedAt' => '18 Apr 2026 21:42:59',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-10',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Pinjaman Karyawan',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'numbering',
                                'transactionTypeLabel' => 'Penomoran',
                                'loggedAt' => '18 Apr 2026 21:42:59',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ]
        ];
    }

    private static function part2(): array
    {
        return [
[
                                'id' => 'activity-log-11',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => '-',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'preferences',
                                'transactionTypeLabel' => 'Preferensi',
                                'loggedAt' => '18 Apr 2026 21:42:59',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-12',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Distribusi Stok',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'numbering',
                                'transactionTypeLabel' => 'Penomoran',
                                'loggedAt' => '18 Apr 2026 21:42:58',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-13',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Forecast PO',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'numbering',
                                'transactionTypeLabel' => 'Penomoran',
                                'loggedAt' => '18 Apr 2026 21:42:58',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-14',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Minimum Stok Cabang',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'numbering',
                                'transactionTypeLabel' => 'Penomoran',
                                'loggedAt' => '18 Apr 2026 21:42:58',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-15',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Persiapan Bahan Baku - Default',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'print-design',
                                'transactionTypeLabel' => 'Desain Cetakan',
                                'loggedAt' => '18 Apr 2026 21:42:58',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-16',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Persiapan Bahan Baku',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'numbering',
                                'transactionTypeLabel' => 'Penomoran',
                                'loggedAt' => '18 Apr 2026 21:42:58',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-17',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Trade Portal',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'numbering',
                                'transactionTypeLabel' => 'Penomoran',
                                'loggedAt' => '18 Apr 2026 21:42:58',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-18',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Transfer Anggaran',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'numbering',
                                'transactionTypeLabel' => 'Penomoran',
                                'loggedAt' => '18 Apr 2026 21:42:58',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ],
[
                                'id' => 'activity-log-19',
                                'dateValue' => '2026-04-18',
                                'transactionDateValue' => 'empty',
                                'transactionDateLabel' => '',
                                'referenceName' => 'Uang Muka Pembelian',
                                'actionTypeValue' => 'create',
                                'actionLabel' => 'Buat',
                                'transactionTypeValue' => 'numbering',
                                'transactionTypeLabel' => 'Penomoran',
                                'loggedAt' => '18 Apr 2026 21:42:58',
                                'userValue' => 'tbnur-pos',
                                'userName' => 'TB Nur POS System',
                                'email' => 'system@tbnurpos.local',
                                'ipAddress' => '127.0.0.1',
                            ]
        ];
    }
}
