<?php

namespace App\Support\Presentation\Blueprints\Pages;

class CompanyTaxPage
{
    public static function get(): array
    {
        return [
                    'id' => 'company-tax',
                    'label' => 'Pajak',
                    'subtab' => [
                        'id' => 'company-tax-create',
                        'label' => 'Data Baru',
                    ],
                    'viewModes' => [
                        'form' => 'Form',
                        'table' => 'Tabel',
                    ],
                    'table' => [
                        'createLabel' => 'Tambah Pajak',
                        'refreshLabel' => 'Muat ulang',
                        'printLabel' => 'Cetak',
                        'actionsLabel' => 'Pengaturan daftar pajak',
                        'searchPlaceholder' => 'Cari...',
                        'pageValue' => '6',
                        'filterOptions' => [
                            ['value' => 'all', 'label' => 'Tipe Pajak: Semua'],
                            ['value' => 'vat', 'label' => 'Tipe Pajak: Pajak Pertambahan Nilai'],
                            ['value' => 'pph23', 'label' => 'Tipe Pajak: Pajak Penghasilan Ps.23'],
                            ['value' => 'pph21', 'label' => 'Tipe Pajak: Pajak Penghasilan Ps.21'],
                        ],
                        'menuItems' => [
                            ['id' => 'column-settings', 'label' => 'Atur kolom'],
                            ['id' => 'view-settings', 'label' => 'Atur tampilan'],
                        ],
                        'rows' => [
                            [
                                'id' => 'tax-vat',
                                'tabLabel' => 'Pajak Pertambahan...',
                                'typeValue' => 'vat',
                                'typeLabel' => 'Pajak Pertambahan Nilai',
                                'description' => 'Pajak Pertambahan Nilai',
                                'percentage' => '10',
                                'salesAccount' => '[215.000-01] PPN Keluaran',
                                'purchaseAccount' => '[117.000-01] PPN Masukan',
                            ],
                            [
                                'id' => 'tax-software-services',
                                'tabLabel' => 'Jasa Software...',
                                'typeValue' => 'pph23',
                                'typeLabel' => 'Pajak Penghasilan Ps.23',
                                'description' => 'Jasa Software Komputer',
                                'percentage' => '2',
                                'salesAccount' => '[215.100-02] PPh 23 Keluaran',
                                'purchaseAccount' => '[117.100-02] PPh 23 Masukan',
                            ],
                            [
                                'id' => 'tax-technical-services',
                                'tabLabel' => 'Jasa Teknik',
                                'typeValue' => 'pph23',
                                'typeLabel' => 'Pajak Penghasilan Ps.23',
                                'description' => 'Jasa Teknik',
                                'percentage' => '2',
                                'salesAccount' => '[215.100-02] PPh 23 Keluaran',
                                'purchaseAccount' => '[117.100-02] PPh 23 Masukan',
                            ],
                            [
                                'id' => 'tax-cleaning-services',
                                'tabLabel' => 'Jasa Kebersihan',
                                'typeValue' => 'pph23',
                                'typeLabel' => 'Pajak Penghasilan Ps.23',
                                'description' => 'Jasa Kebersihan',
                                'percentage' => '2',
                                'salesAccount' => '[215.100-02] PPh 23 Keluaran',
                                'purchaseAccount' => '[117.100-02] PPh 23 Masukan',
                            ],
                            [
                                'id' => 'tax-freight-services',
                                'tabLabel' => 'Jasa Freight...',
                                'typeValue' => 'pph23',
                                'typeLabel' => 'Pajak Penghasilan Ps.23',
                                'description' => 'Jasa Freight forwarding',
                                'percentage' => '2',
                                'salesAccount' => '[215.100-02] PPh 23 Keluaran',
                                'purchaseAccount' => '[117.100-02] PPh 23 Masukan',
                            ],
                            [
                                'id' => 'tax-pph21',
                                'tabLabel' => 'PPh 21',
                                'typeValue' => 'pph21',
                                'typeLabel' => 'Pajak Penghasilan Ps.21',
                                'description' => 'PPh 21',
                                'percentage' => '0',
                                'salesAccount' => '[215.200-01] Hutang PPh 21',
                                'purchaseAccount' => '[117.200-01] Piutang PPh 21',
                            ],
                        ],
                    ],
                    'form' => [
                        'sectionLabel' => 'Pajak',
                        'saveLabel' => 'Simpan',
                        'deleteLabel' => 'Hapus',
                        'accountPlaceholder' => 'Cari/Pilih Akun Perkiraan...',
                        'salesAccountSearchLabel' => 'Cari akun pajak penjualan',
                        'purchaseAccountSearchLabel' => 'Cari akun pajak pembelian',
                        'labels' => [
                            'type' => 'Tipe Pajak',
                            'description' => 'Keterangan',
                            'percentage' => 'Persentase',
                            'salesAccount' => 'Akun Pajak Penjualan',
                            'purchaseAccount' => 'Akun Pajak Pembelian',
                        ],
                        'typeOptions' => [
                            ['value' => '', 'label' => '- Pilih Tipe Pajak -'],
                            ['value' => 'vat', 'label' => 'Pajak Pertambahan Nilai'],
                            ['value' => 'pph23', 'label' => 'Pajak Penghasilan Ps.23'],
                            ['value' => 'pph21', 'label' => 'Pajak Penghasilan Ps.21'],
                        ],
                        'createDefaults' => [
                            'type' => '',
                            'description' => '',
                            'percentage' => '',
                            'salesAccount' => '',
                            'purchaseAccount' => '',
                        ],
                        'records' => [
                            [
                                'id' => 'tax-vat',
                                'type' => 'vat',
                                'description' => 'Pajak Pertambahan Nilai',
                                'percentage' => '10',
                                'salesAccount' => '[215.000-01] PPN Keluaran',
                                'purchaseAccount' => '[117.000-01] PPN Masukan',
                            ],
                            [
                                'id' => 'tax-software-services',
                                'type' => 'pph23',
                                'description' => 'Jasa Software Komputer',
                                'percentage' => '2',
                                'salesAccount' => '[215.100-02] PPh 23 Keluaran',
                                'purchaseAccount' => '[117.100-02] PPh 23 Masukan',
                            ],
                            [
                                'id' => 'tax-technical-services',
                                'type' => 'pph23',
                                'description' => 'Jasa Teknik',
                                'percentage' => '2',
                                'salesAccount' => '[215.100-02] PPh 23 Keluaran',
                                'purchaseAccount' => '[117.100-02] PPh 23 Masukan',
                            ],
                            [
                                'id' => 'tax-cleaning-services',
                                'type' => 'pph23',
                                'description' => 'Jasa Kebersihan',
                                'percentage' => '2',
                                'salesAccount' => '[215.100-02] PPh 23 Keluaran',
                                'purchaseAccount' => '[117.100-02] PPh 23 Masukan',
                            ],
                            [
                                'id' => 'tax-freight-services',
                                'type' => 'pph23',
                                'description' => 'Jasa Freight forwarding',
                                'percentage' => '2',
                                'salesAccount' => '[215.100-02] PPh 23 Keluaran',
                                'purchaseAccount' => '[117.100-02] PPh 23 Masukan',
                            ],
                            [
                                'id' => 'tax-pph21',
                                'type' => 'pph21',
                                'description' => 'PPh 21',
                                'percentage' => '0',
                                'salesAccount' => '[215.200-01] Hutang PPh 21',
                                'purchaseAccount' => '[117.200-01] Piutang PPh 21',
                            ],
                        ],
                    ],
                ];
    }
}
