<?php

namespace App\Support\Presentation\Blueprints\Pages;

class EmployeesTable
{
    public static function rows(): array
    {
        return [
            [
                                'id' => 'employee-adam',
                                'name' => 'Adam',
                                'position' => 'Junior Staf TB Nur',
                                'email' => 'onsite_jkt@tbnur.com',
                                'mobilePhone' => '081315778xxx',
                                'employeeId' => '0426201200...',
                                'taxStatus' => 'TK0',
                                'employmentStatus' => 'Pegawai Tetap',
                                'payable' => 'IDR 0',
                                'inactiveValue' => 'no',
                                'employmentStatusValue' => 'permanent',
                                'departmentValue' => 'consulting',
                                'sellerValue' => 'no',
                            ],
                            [
                                'id' => 'employee-ahmad',
                                'name' => 'Ahmad',
                                'position' => 'Supervisor Staf TB Nur',
                                'email' => 'ahmadyani@tbnur.com',
                                'mobilePhone' => '081288087xxx',
                                'employeeId' => '0426201200...',
                                'taxStatus' => 'TK0',
                                'employmentStatus' => 'Pegawai Tetap',
                                'payable' => 'IDR 0',
                                'inactiveValue' => 'no',
                                'employmentStatusValue' => 'permanent',
                                'departmentValue' => 'consulting',
                                'sellerValue' => 'no',
                            ],
                            [
                                'id' => 'employee-ari',
                                'name' => 'Ari',
                                'position' => 'Junior Staf TB Nur',
                                'email' => 'onsite_sby@tbnur.com',
                                'mobilePhone' => '08115222xxx',
                                'employeeId' => '0426201200...',
                                'taxStatus' => 'TK0',
                                'employmentStatus' => 'Pegawai Tetap',
                                'payable' => 'IDR 0',
                                'inactiveValue' => 'no',
                                'employmentStatusValue' => 'permanent',
                                'departmentValue' => 'consulting',
                                'sellerValue' => 'no',
                            ],
                            [
                                'id' => 'employee-cynthia',
                                'name' => 'Cynthia',
                                'position' => 'Accounting',
                                'email' => 'onsite_jkt@tbnur.com',
                                'mobilePhone' => '08511294xxxx',
                                'employeeId' => '0426201200...',
                                'taxStatus' => 'TK0',
                                'employmentStatus' => 'Pegawai Tetap',
                                'payable' => 'IDR 0',
                                'inactiveValue' => 'no',
                                'employmentStatusValue' => 'permanent',
                                'departmentValue' => 'accounting',
                                'sellerValue' => 'no',
                            ],
                            [
                                'id' => 'employee-darwin',
                                'name' => 'Darwin Nur',
                                'position' => 'Direktur',
                                'email' => 'onsite_jkt@tbnur.com',
                                'mobilePhone' => '081287773xxx',
                                'employeeId' => '0426201200...',
                                'taxStatus' => 'K1',
                                'employmentStatus' => 'Pegawai Tetap',
                                'payable' => 'IDR 0',
                                'inactiveValue' => 'no',
                                'employmentStatusValue' => 'permanent',
                                'departmentValue' => 'management',
                                'sellerValue' => 'no',
                            ],
                            [
                                'id' => 'employee-eko',
                                'name' => 'Eko',
                                'position' => 'Junior Staf TB Nur',
                                'email' => 'onsite_sby@tbnur.com',
                                'mobilePhone' => '085646779xxx',
                                'employeeId' => '0426201200...',
                                'taxStatus' => 'K1',
                                'employmentStatus' => 'Pegawai Tetap',
                                'payable' => 'IDR 0',
                                'inactiveValue' => 'no',
                                'employmentStatusValue' => 'permanent',
                                'departmentValue' => 'consulting',
                                'sellerValue' => 'no',
                            ],
                            [
                                'id' => 'employee-erick',
                                'name' => 'Erick',
                                'position' => 'Asst. Supervisor Staf TB Nur',
                                'email' => 'erick@tbnur.com',
                                'mobilePhone' => '081293274xxx',
                                'employeeId' => '0426201200...',
                                'taxStatus' => 'TK0',
                                'employmentStatus' => 'Pegawai Tetap',
                                'payable' => 'IDR 0',
                                'inactiveValue' => 'no',
                                'employmentStatusValue' => 'permanent',
                                'departmentValue' => 'consulting',
                                'sellerValue' => 'no',
                            ],
                            [
                                'id' => 'employee-fandy',
                                'name' => 'Fandy',
                                'position' => 'Junior Staf TB Nur',
                                'email' => 'onsite_jkt@tbnur.com',
                                'mobilePhone' => '08999294xxx',
                                'employeeId' => '0426201200...',
                                'taxStatus' => 'TK0',
                                'employmentStatus' => 'Pegawai Tetap',
                                'payable' => 'IDR 0',
                                'inactiveValue' => 'no',
                                'employmentStatusValue' => 'permanent',
                                'departmentValue' => 'consulting',
                                'sellerValue' => 'no',
                            ],
                            [
                                'id' => 'employee-jhonni',
                                'name' => 'Jhonni Haris',
                                'position' => 'Asst. Supervisor Staf TB Nur',
                                'email' => 'jhonni@tbnur.com',
                                'mobilePhone' => '081297584xxx',
                                'employeeId' => '0426201200...',
                                'taxStatus' => 'TK0',
                                'employmentStatus' => 'Pegawai Tetap',
                                'payable' => 'IDR 0',
                                'inactiveValue' => 'no',
                                'employmentStatusValue' => 'permanent',
                                'departmentValue' => 'consulting',
                                'sellerValue' => 'no',
                            ],
                            [
                                'id' => 'employee-roni',
                                'name' => 'Roni',
                                'position' => 'Junior Staf TB Nur',
                                'email' => 'onsite_jkt@tbnur.com',
                                'mobilePhone' => '081285612xxx',
                                'employeeId' => '0426201200...',
                                'taxStatus' => 'TK0',
                                'employmentStatus' => 'Pegawai Tetap',
                                'payable' => 'IDR 0',
                                'inactiveValue' => 'no',
                                'employmentStatusValue' => 'permanent',
                                'departmentValue' => 'consulting',
                                'sellerValue' => 'no',
                            ],
                            [
                                'id' => 'employee-vando',
                                'name' => 'Vando',
                                'position' => 'Asst. Manager Staf TB Nur',
                                'email' => 'vando@tbnur.com',
                                'mobilePhone' => '081317805xxx',
                                'employeeId' => '0426201200...',
                                'taxStatus' => 'TK0',
                                'employmentStatus' => 'Pegawai Tetap',
                                'payable' => 'IDR 0',
                                'inactiveValue' => 'no',
                                'employmentStatusValue' => 'permanent',
                                'departmentValue' => 'consulting',
                                'sellerValue' => 'no',
                            ],
                        ];
    }
}
