<?php

namespace App\Support\Presentation\Blueprints\Pages;

class ExpenseEntryPage
{
    public static function get(array $navigationPages): array
    {
        return array_replace($navigationPages['expense-entry'], [
            'subtab' => [
                'id' => 'expense-entry-create',
                'label' => 'Data Baru',
            ],
            'viewModes' => [
                'form' => 'Form',
                'table' => 'Tabel',
            ],
            'expenseEntry' => [
                'topActions' => [
                    [
                        'id' => 'settings',
                        'label' => 'Pengaturan',
                        'icon' => 'settings',
                        'tone' => 'outline',
                    ],
                ],
                'labels' => [
                    'liabilityAccount' => 'Hutang Beban',
                    'documentNumber' => 'No Beban #',
                    'entryDate' => 'Tanggal',
                    'dueDate' => 'Jatuh Tempo',
                    'branch' => 'Cabang',
                    'notes' => 'Catatan',
                ],
                'numberingOptions' => ['Pencatatan Beban'],
                'liabilityAccountPlaceholder' => 'Cari/Pilih Akun Perkiraan...',
                'branchPlaceholder' => 'Cari/Pilih...',
                'takeButtonLabel' => 'Ambil',
                'processButtonLabel' => 'Proses',
                'lineSearchPlaceholder' => 'Cari/Pilih Akun Perkiraan...',
                'lineSectionTitle' => 'Rincian Beban',
                'additionalInfoTitle' => 'Info lainnya',
                'summaryTitle' => 'Informasi Pencatatan Beban',
                'totalCardLabel' => 'Total',
                'sectionTabs' => [
                    [
                        'id' => 'details',
                        'label' => 'Rincian Beban',
                        'icon' => 'document',
                    ],
                    [
                        'id' => 'additional-info',
                        'label' => 'Info lainnya',
                        'icon' => 'info',
                    ],
                ],
                'dockActions' => [
                    [
                        'id' => 'save',
                        'label' => 'Simpan',
                        'icon' => 'save',
                        'tone' => 'primary',
                        'items' => [
                            ['id' => 'save-now', 'label' => 'Simpan'],
                            ['id' => 'save-new', 'label' => 'Simpan dan buat baru'],
                        ],
                    ],
                    [
                        'id' => 'document',
                        'label' => 'Form lain',
                        'icon' => 'document',
                        'tone' => 'secondary',
                        'items' => [
                            ['id' => 'view-details', 'label' => 'Lihat rincian'],
                            ['id' => 'open-summary', 'label' => 'Buka informasi pencatatan'],
                        ],
                    ],
                    [
                        'id' => 'attachment',
                        'label' => 'Lampiran',
                        'icon' => 'paperclip',
                        'tone' => 'secondary',
                        'items' => [
                            ['id' => 'add-attachment', 'label' => 'Tambah lampiran'],
                            ['id' => 'manage-attachment', 'label' => 'Kelola lampiran'],
                        ],
                    ],
                    [
                        'id' => 'more',
                        'label' => 'Lainnya',
                        'icon' => 'kebab',
                        'tone' => 'success',
                        'items' => [
                            ['id' => 'duplicate', 'label' => 'Duplikasi transaksi'],
                            ['id' => 'mark-review', 'label' => 'Tandai untuk review'],
                        ],
                    ],
                    [
                        'id' => 'delete',
                        'label' => 'Hapus',
                        'icon' => 'trash',
                        'tone' => 'danger',
                    ],
                ],
                'draft' => [
                    'liabilityAccounts' => [],
                    'entryDate' => date('d/m/Y'),
                    'autoNumber' => true,
                    'numberingType' => 'Pencatatan Beban',
                    'documentNumber' => '',
                    'dueDate' => date('d/m/Y'),
                    'branches' => ['JAKARTA'],
                    '__branchId' => 1,
                    'notes' => '',
                    'lineLookup' => '',
                    'lineItems' => [],
                    'paidAmount' => 'Rp 0',
                    'status' => 'Draft',
                    'totalValue' => '0',
                    'saveTone' => 'primary',
                ],
                'records' => [
                    'EXP.2016.12.00006' => [
                        'id' => 'EXP.2016.12.00006',
                        'documentNumber' => 'EXP.2016.12.00006',
                        'liabilityAccounts' => ['[214.200-08] BYMD - Hutang Bunga Bank Surabaya'],
                        'entryDate' => '30/12/2016',
                        'autoNumber' => false,
                        'numberingType' => 'Pencatatan Beban',
                        'dueDate' => '06/01/2017',
                        'branches' => ['JAKARTA'],
                    '__branchId' => 1,
                        'notes' => '',
                        'lineLookup' => '',
                        'lineItems' => [
                            [
                                'id' => 'expense-entry-line-1',
                                'account' => '711.000-03',
                                'accountName' => 'Bunga Pinjaman',
                                'amount' => '52,500,000',
                            ],
                        ],
                        'paidAmount' => 'Rp 0',
                        'status' => 'Sedang diproses',
                        'totalValue' => 'Rp 52,500,000',
                        'saveTone' => 'muted',
                    ],
                    'EXP.2016.12.00005' => [
                        'id' => 'EXP.2016.12.00005',
                        'documentNumber' => 'EXP.2016.12.00005',
                        'liabilityAccounts' => ['[214.200-02] BYMD - Hutang Beban Iklan'],
                        'entryDate' => '30/12/2016',
                        'autoNumber' => false,
                        'numberingType' => 'Pencatatan Beban',
                        'dueDate' => '06/01/2017',
                        'branches' => ['JAKARTA'],
                    '__branchId' => 1,
                        'notes' => 'Pembebanan biaya promosi akhir tahun.',
                        'lineLookup' => '',
                        'lineItems' => [
                            [
                                'id' => 'expense-entry-line-2',
                                'account' => '712.100-01',
                                'accountName' => 'Biaya Iklan dan Promosi',
                                'amount' => '86,250,000',
                            ],
                        ],
                        'paidAmount' => 'Rp 0',
                        'status' => 'Sedang diproses',
                        'totalValue' => 'Rp 86,250,000',
                        'saveTone' => 'muted',
                    ],
                    'EXP.2016.11.00002' => [
                        'id' => 'EXP.2016.11.00002',
                        'documentNumber' => 'EXP.2016.11.00002',
                        'liabilityAccounts' => ['[214.200-05] BYMD - Hutang Beban Konsultan'],
                        'entryDate' => '30/11/2016',
                        'autoNumber' => false,
                        'numberingType' => 'Pencatatan Beban',
                        'dueDate' => '08/12/2016',
                        'branches' => ['JAKARTA'],
                    '__branchId' => 1,
                        'notes' => '',
                        'lineLookup' => '',
                        'lineItems' => [
                            [
                                'id' => 'expense-entry-line-3',
                                'account' => '713.300-01',
                                'accountName' => 'Jasa Profesional',
                                'amount' => '52,500,000',
                            ],
                        ],
                        'paidAmount' => 'Rp 52,500,000',
                        'status' => 'Terbayar',
                        'totalValue' => 'Rp 52,500,000',
                        'saveTone' => 'muted',
                    ],
                    'EXP.2016.11.00001' => [
                        'id' => 'EXP.2016.11.00001',
                        'documentNumber' => 'EXP.2016.11.00001',
                        'liabilityAccounts' => ['[214.200-03] BYMD - Hutang Beban Operasional'],
                        'entryDate' => '30/11/2016',
                        'autoNumber' => false,
                        'numberingType' => 'Pencatatan Beban',
                        'dueDate' => '09/12/2016',
                        'branches' => ['JAKARTA'],
                    '__branchId' => 1,
                        'notes' => '',
                        'lineLookup' => '',
                        'lineItems' => [
                            [
                                'id' => 'expense-entry-line-4',
                                'account' => '714.200-01',
                                'accountName' => 'Beban Operasional Kantor',
                                'amount' => '86,250,000',
                            ],
                        ],
                        'paidAmount' => 'Rp 86,250,000',
                        'status' => 'Terbayar',
                        'totalValue' => 'Rp 86,250,000',
                        'saveTone' => 'muted',
                    ],
                    'EXP.2016.10.00002' => [
                        'id' => 'EXP.2016.10.00002',
                        'documentNumber' => 'EXP.2016.10.00002',
                        'liabilityAccounts' => ['[214.200-04] BYMD - Hutang Beban Utilitas'],
                        'entryDate' => '31/10/2016',
                        'autoNumber' => false,
                        'numberingType' => 'Pencatatan Beban',
                        'dueDate' => '11/11/2016',
                        'branches' => ['JAKARTA'],
                    '__branchId' => 1,
                        'notes' => '',
                        'lineLookup' => '',
                        'lineItems' => [
                            [
                                'id' => 'expense-entry-line-5',
                                'account' => '715.100-01',
                                'accountName' => 'Beban Listrik dan Air',
                                'amount' => '86,250,000',
                            ],
                        ],
                        'paidAmount' => 'Rp 86,250,000',
                        'status' => 'Terbayar',
                        'totalValue' => 'Rp 86,250,000',
                        'saveTone' => 'muted',
                    ],
                    'EXP.2016.10.00001' => [
                        'id' => 'EXP.2016.10.00001',
                        'documentNumber' => 'EXP.2016.10.00001',
                        'liabilityAccounts' => ['[214.200-01] BYMD - Hutang Beban Sewa'],
                        'entryDate' => '31/10/2016',
                        'autoNumber' => false,
                        'numberingType' => 'Pencatatan Beban',
                        'dueDate' => '10/11/2016',
                        'branches' => ['JAKARTA'],
                    '__branchId' => 1,
                        'notes' => '',
                        'lineLookup' => '',
                        'lineItems' => [
                            [
                                'id' => 'expense-entry-line-6',
                                'account' => '716.100-01',
                                'accountName' => 'Beban Sewa Gedung',
                                'amount' => '52,500,000',
                            ],
                        ],
                        'paidAmount' => 'Rp 52,500,000',
                        'status' => 'Terbayar',
                        'totalValue' => 'Rp 52,500,000',
                        'saveTone' => 'muted',
                    ],
                ],
                'lineTable' => [
                    'columns' => [
                        [
                            'id' => 'spacer',
                            'label' => '',
                            'kind' => 'spacer',
                            'widthClassName' => 'w-[36px]',
                            'align' => 'center',
                        ],
                        [
                            'id' => 'account',
                            'label' => 'Akun',
                            'widthClassName' => 'w-[15%]',
                            'align' => 'left',
                        ],
                        [
                            'id' => 'accountName',
                            'label' => 'Nama Akun',
                            'widthClassName' => 'w-[70%]',
                            'align' => 'left',
                        ],
                        [
                            'id' => 'amount',
                            'label' => 'Nilai',
                            'widthClassName' => 'w-[15%]',
                            'align' => 'right',
                        ],
                    ],
                    'emptyLabel' => 'Belum ada data',
                ],
                'summaryRows' => [
                    'paidAmountLabel' => 'Dibayar',
                    'statusLabel' => 'Status',
                ],
                'table' => [
                    'createLabel' => 'Tambah Pencatatan Beban',
                    'refreshLabel' => 'Muat ulang',
                    'downloadLabel' => 'Unduh',
                    'printLabel' => 'Cetak',
                    'settingsLabel' => 'Pengaturan tabel',
                    'filterButtonLabel' => 'Filter lanjutan',
                    'searchPlaceholder' => 'Cari...',
                    'pageValue' => '6',
                    'filters' => [
                        [
                            'id' => 'date',
                            'rowKey' => 'dateFilter',
                            'options' => [
                                ['value' => 'all', 'label' => 'Tanggal: Semua'],
                                ['value' => '2016', 'label' => 'Tanggal: 2016'],
                            ],
                        ],
                        [
                            'id' => 'status',
                            'rowKey' => 'statusFilter',
                            'options' => [
                                ['value' => 'all', 'label' => 'Status: Semua'],
                                ['value' => 'processing', 'label' => 'Status: Sedang diproses'],
                                ['value' => 'paid', 'label' => 'Status: Terbayar'],
                            ],
                        ],
                    ],
                    'settingsMenu' => [
                        ['id' => 'arrange-columns', 'label' => 'Atur kolom'],
                        ['id' => 'export-expense', 'label' => 'Ekspor pencatatan beban'],
                    ],
                    'columns' => [
                        ['id' => 'documentNumber', 'label' => 'No. Beban', 'widthClassName' => 'w-[16%]', 'align' => 'left'],
                        ['id' => 'entryDate', 'label' => 'Tanggal', 'widthClassName' => 'w-[10%]', 'align' => 'left'],
                        ['id' => 'dueDate', 'label' => 'Jatuh Tempo', 'widthClassName' => 'w-[12%]', 'align' => 'left'],
                        ['id' => 'total', 'label' => 'Total', 'widthClassName' => 'w-[12%]', 'align' => 'right'],
                        ['id' => 'paid', 'label' => 'Dibayar', 'widthClassName' => 'w-[10%]', 'align' => 'right'],
                        ['id' => 'status', 'label' => 'Status', 'widthClassName' => 'w-[12%]', 'align' => 'left'],
                        ['id' => 'note', 'label' => 'Keterangan', 'align' => 'left'],
                    ],
                    'rows' => [
                        [
                            'id' => 'EXP.2016.12.00006',
                            'documentNumber' => 'EXP.2016.12.00006',
                            'entryDate' => '30/12/2016',
                            'dueDate' => '06/01/2017',
                            'total' => '52,500,000',
                            'paid' => '0',
                            'status' => 'Sedang diproses',
                            'note' => '',
                            'dateFilter' => '2016',
                            'statusFilter' => 'processing',
                        ],
                        [
                            'id' => 'EXP.2016.12.00005',
                            'documentNumber' => 'EXP.2016.12.00005',
                            'entryDate' => '30/12/2016',
                            'dueDate' => '06/01/2017',
                            'total' => '86,250,000',
                            'paid' => '0',
                            'status' => 'Sedang diproses',
                            'note' => '',
                            'dateFilter' => '2016',
                            'statusFilter' => 'processing',
                        ],
                        [
                            'id' => 'EXP.2016.11.00002',
                            'documentNumber' => 'EXP.2016.11.00002',
                            'entryDate' => '30/11/2016',
                            'dueDate' => '08/12/2016',
                            'total' => '52,500,000',
                            'paid' => '52,500,000',
                            'status' => 'Terbayar',
                            'note' => '',
                            'dateFilter' => '2016',
                            'statusFilter' => 'paid',
                        ],
                        [
                            'id' => 'EXP.2016.11.00001',
                            'documentNumber' => 'EXP.2016.11.00001',
                            'entryDate' => '30/11/2016',
                            'dueDate' => '09/12/2016',
                            'total' => '86,250,000',
                            'paid' => '86,250,000',
                            'status' => 'Terbayar',
                            'note' => '',
                            'dateFilter' => '2016',
                            'statusFilter' => 'paid',
                        ],
                        [
                            'id' => 'EXP.2016.10.00002',
                            'documentNumber' => 'EXP.2016.10.00002',
                            'entryDate' => '31/10/2016',
                            'dueDate' => '11/11/2016',
                            'total' => '86,250,000',
                            'paid' => '86,250,000',
                            'status' => 'Terbayar',
                            'note' => '',
                            'dateFilter' => '2016',
                            'statusFilter' => 'paid',
                        ],
                        [
                            'id' => 'EXP.2016.10.00001',
                            'documentNumber' => 'EXP.2016.10.00001',
                            'entryDate' => '31/10/2016',
                            'dueDate' => '10/11/2016',
                            'total' => '52,500,000',
                            'paid' => '52,500,000',
                            'status' => 'Terbayar',
                            'note' => '',
                            'dateFilter' => '2016',
                            'statusFilter' => 'paid',
                        ],
                    ],
                    'emptyLabel' => 'Belum ada data',
                ],
            ],
        ]);
    }
}
