<?php

namespace App\Support\Presentation\Blueprints\Pages;

class GoodsReceiptPage
{
    public static function get(array $navigationPages): array
    {
        return array_replace($navigationPages['goods-receipt'], [
            'subtab' => [
                'id' => 'goods-receipt-create',
                'label' => 'Data Baru',
            ],
            'viewModes' => [
                'form' => 'Form',
                'table' => 'Tabel',
            ],
            'goodsReceipt' => [
                'topActions' => self::salesTransactionTopActions(),
                'customerPlaceholder' => 'Cari/Pilih Pemasok...',
                'customerSearchLabel' => 'Cari pemasok',
                'labels' => [
                    'customer' => 'Terima dari',
                    'entryDate' => 'Tanggal',
                    'documentNumber' => 'No Form #',
                    'paymentTerms' => 'Syarat Pembayaran',
                    'purchaseOrderNumber' => 'No Terima #',
                    'address' => 'Alamat',
                    'branch' => 'Cabang',
                    'notes' => 'Keterangan',
                    'shippingDate' => 'Tgl Kirim',
                    'shippingMethod' => 'Pengiriman',
                    'fob' => 'FOB',
                ],
                'numberingOptions' => ['Penerimaan Barang'],
                'secondaryActionLabel' => 'Faktur',
                'showPaymentTerms' => false,
                'showPurchaseOrderNumber' => false,
                'showTaxInfo' => false,
                'showShippingInfo' => true,
                'showExtraInfo' => false,
                'showFobInShippingInfo' => true,
                'showFooter' => false,
                'headerTextField' => [
                    'label' => 'No Terima #',
                    'valueKey' => 'receiptNumber',
                    'required' => true,
                ],
                'itemModal' => [
                    'enabled' => true,
                ],
                'table' => [
                    'createLabel' => 'Tambah Penerimaan Barang',
                    'refreshLabel' => 'Muat ulang',
                    'filterButtonLabel' => 'Filter lanjutan',
                    'searchPlaceholder' => 'Cari...',
                    'pageValue' => '6',
                    'columns' => [
                        ['id' => 'number', 'label' => 'Nomor #', 'widthClassName' => 'w-[200px]', 'align' => 'left'],
                        ['id' => 'receiptNumber', 'label' => 'No Terima #', 'widthClassName' => 'w-[180px]', 'align' => 'left'],
                        ['id' => 'date', 'label' => 'Tanggal', 'widthClassName' => 'w-[120px]', 'align' => 'left'],
                        ['id' => 'customer', 'label' => 'Pemasok', 'widthClassName' => 'w-[190px]', 'align' => 'left'],
                        ['id' => 'notes', 'label' => 'Keterangan', 'widthClassName' => 'w-[44%]', 'align' => 'left'],
                        ['id' => 'status', 'label' => 'Status', 'widthClassName' => 'w-[170px]', 'align' => 'left'],
                    ],
                    'rows' => [
                        ['id' => 'RI.2017.01.00002', 'number' => 'RI.2017.01.00002', 'receiptNumber' => 'SJGP-34217', 'date' => '10/01/2017', 'customer' => 'CV Ganda Putra', 'notes' => '', 'status' => 'Difaktur'],
                        ['id' => 'RI.2017.01.00001', 'number' => 'RI.2017.01.00001', 'receiptNumber' => 'SJAPL-409317', 'date' => '05/01/2017', 'customer' => 'Applus', 'notes' => '', 'status' => 'Difaktur Sebagian'],
                        ['id' => 'RI.2016.10.00004', 'number' => 'RI.2016.10.00004', 'receiptNumber' => 'TMM SJ 852456', 'date' => '20/10/2016', 'customer' => 'Toko Mega Mendung', 'notes' => '', 'status' => 'Difaktur'],
                        ['id' => 'RI.2016.10.00003', 'number' => 'RI.2016.10.00003', 'receiptNumber' => 'TSS RI 7895', 'date' => '11/10/2016', 'customer' => 'Toko Samudra Sparepart', 'notes' => 'stock barang di Toko Samudra Sparepart kosong jadi dikirim hanya sebagian saja.', 'status' => 'Difaktur Sebagian'],
                        ['id' => 'RI.2016.10.00002', 'number' => 'RI.2016.10.00002', 'receiptNumber' => 'SAM 20161007015', 'date' => '07/10/2016', 'customer' => 'SAMSANG', 'notes' => '', 'status' => 'Difaktur'],
                        ['id' => 'RI.2016.10.00001', 'number' => 'RI.2016.10.00001', 'receiptNumber' => 'RI 061016001', 'date' => '06/10/2016', 'customer' => 'PT Selaras Inti', 'notes' => '', 'status' => 'Difaktur'],
                    ],
                    'filters' => [
                        ['id' => 'date', 'rowKey' => 'date', 'options' => [['value' => 'all', 'label' => 'Tanggal: Semua'], ['value' => '10/01/2017', 'label' => 'Tanggal: 10/01/2017']]],
                        ['id' => 'status', 'rowKey' => 'status', 'options' => [['value' => 'all', 'label' => 'Status: Semua'], ['value' => 'Difaktur', 'label' => 'Status: Difaktur'], ['value' => 'Difaktur Sebagian', 'label' => 'Status: Difaktur Sebagian']]],
                        ['id' => 'customer', 'rowKey' => 'customer', 'options' => [['value' => 'all', 'label' => 'Terima dari: Semua'], ['value' => 'CV Ganda Putra', 'label' => 'Terima dari: CV Ganda Putra'], ['value' => 'Applus', 'label' => 'Terima dari: Applus']]],
                    ],
                    'downloadItems' => [],
                    'printItems' => [['id' => 'print-list', 'label' => 'Cetak daftar penerimaan barang']],
                    'settingsItems' => [['id' => 'arrange-columns', 'label' => 'Atur kolom']],
                ],
                'itemTable' => [
                    'columns' => [
                        ['id' => 'spacer', 'label' => '', 'kind' => 'spacer', 'widthClassName' => 'w-[38px]', 'align' => 'center'],
                        ['id' => 'name', 'label' => 'Nama Barang', 'widthClassName' => 'w-[70%]', 'align' => 'left'],
                        ['id' => 'code', 'label' => 'Kode #', 'widthClassName' => 'w-[130px]', 'align' => 'center'],
                        ['id' => 'quantity', 'label' => 'Kuantitas', 'widthClassName' => 'w-[110px]', 'align' => 'right'],
                        ['id' => 'unit', 'label' => 'Satuan', 'widthClassName' => 'w-[92px]', 'align' => 'center'],
                    ],
                    'emptyLabel' => 'Belum ada data',
                    'minWidthClassName' => 'min-w-[880px]',
                ],
                'sectionTabs' => [
                    ['id' => 'details', 'label' => 'Rincian Barang', 'icon' => 'document'],
                    ['id' => 'additional-info', 'label' => 'Info lainnya', 'icon' => 'info'],
                ],
                'draft' => [
                    'customer' => [],
                    'entryDate' => '28/04/2026',
                    'autoNumber' => true,
                    'numberingType' => 'Penerimaan Barang',
                    'documentNumber' => '',
                    'currency' => '',
                    'receiptNumber' => '',
                    'itemSearch' => '',
                    'items' => [
                        ['id' => 'goods-receipt-draft-item-1', 'name' => 'Adaptor Fast Charging 20W', 'code' => 'AC2001', 'quantity' => '24', 'unit' => 'PCS'],
                        ['id' => 'goods-receipt-draft-item-2', 'name' => 'Type-C Cable Premium', 'code' => 'TC3004', 'quantity' => '16', 'unit' => 'PCS'],
                    ],
                    'itemCountLabel' => '2 Barang (40)',
                    'address' => '',
                    'branches' => ['JAKARTA'],
                    'notes' => '',
                    'shippingDate' => '28/04/2026',
                    'shippingMethod' => [],
                    'fob' => [],
                    'showSecondaryHeaderAction' => true,
                    'showProcessButton' => false,
                    'processDisabled' => false,
                    'subtotal' => '0',
                    'discountValue' => '0',
                    'discountPrefix' => '',
                    'taxLabel' => '',
                    'taxValue' => '',
                    'total' => '0',
                    'itemModal' => [
                        'title' => 'Rincian Barang',
                        'tabs' => [
                            ['id' => 'details', 'label' => 'Rincian Barang'],
                            ['id' => 'info', 'label' => 'Info lainnya'],
                        ],
                        'values' => [
                            'code' => 'AC2001',
                            'name' => 'Adaptor Fast Charging 20W',
                            'quantity' => '24',
                            'unit' => ['PCS'],
                            'warehouse' => ['GD. JAKARTA'],
                            'department' => [],
                            'notes' => 'Contoh item penerimaan barang.',
                        ],
                    ],
                ],
                'detailRecords' => [
                    'RI.2017.01.00002' => [
                        'customer' => ['[VJKT-0008] CV Ganda Putra'],
                        'entryDate' => '10/01/2017',
                        'autoNumber' => false,
                        'numberingType' => 'Penerimaan Barang',
                        'documentNumber' => 'RI.2017.01.00002',
                        'currency' => 'IDR',
                        'receiptNumber' => 'SJGP-34217',
                        'itemSearch' => '',
                        'items' => [
                            ['id' => 'RI.2017.01.00002-item-1', 'name' => 'Xiaomi Mi4s', 'code' => '1300003', 'quantity' => '154', 'unit' => 'PCS'],
                            ['id' => 'RI.2017.01.00002-item-2', 'name' => 'Xiaomi Mi5', 'code' => '1300002', 'quantity' => '165', 'unit' => 'PCS'],
                            ['id' => 'RI.2017.01.00002-item-3', 'name' => 'Xiaomi Note Pro', 'code' => '1300005', 'quantity' => '106', 'unit' => 'PCS'],
                            ['id' => 'RI.2017.01.00002-item-4', 'name' => 'Xiaomi Redmi 3', 'code' => '1300001', 'quantity' => '108', 'unit' => 'PCS'],
                            ['id' => 'RI.2017.01.00002-item-5', 'name' => 'Xiaomi Redmi Note 3', 'code' => '1300004', 'quantity' => '100', 'unit' => 'PCS'],
                        ],
                        'itemCountLabel' => '5 Barang (633)',
                        'address' => '',
                        'branches' => ['JAKARTA'],
                        'notes' => '',
                        'shippingDate' => '10/01/2017',
                        'shippingMethod' => [],
                        'fob' => [],
                        'showSecondaryHeaderAction' => false,
                        'showProcessButton' => false,
                        'processDisabled' => false,
                        'subtotal' => '0',
                        'discountValue' => '0',
                        'discountPrefix' => '',
                        'taxLabel' => '',
                        'taxValue' => '',
                        'total' => '0',
                        'itemModal' => [
                            'title' => 'Rincian Barang',
                            'tabs' => [
                                ['id' => 'details', 'label' => 'Rincian Barang'],
                                ['id' => 'info', 'label' => 'Info lainnya'],
                            ],
                            'values' => [
                                'code' => '1300003',
                                'name' => 'Xiaomi Mi4s',
                                'quantity' => '154',
                                'unit' => ['PCS'],
                                'warehouse' => ['GD. JAKARTA'],
                                'department' => [],
                                'notes' => 'Batch penerimaan awal dari pemasok utama.',
                            ],
                        ],
                    ],
                ],
            ],
        ]);
    }
}
