<?php

namespace App\Support\Presentation\Blueprints\Pages;

class PurchaseOrderPage
{
    public static function get(array $navigationPages): array
    {
        return array_replace($navigationPages['purchase-order'], [
            'subtab' => [
                'id' => 'purchase-order-create',
                'label' => 'Data Baru',
            ],
            'viewModes' => [
                'form' => 'Form',
                'table' => 'Tabel',
            ],
            'purchaseOrder' => [
                'topActions' => \App\Support\Presentation\PosBlueprint::salesTransactionTopActions(),
                'customerPlaceholder' => 'Cari/Pilih Pemasok...',
                'customerSearchLabel' => 'Cari pemasok',
                'labels' => [
                    'customer' => 'Pemasok',
                    'entryDate' => 'Tanggal',
                    'documentNumber' => 'Nomor #',
                    'paymentTerms' => 'Syarat Pembayaran',
                    'purchaseOrderNumber' => 'No. PO',
                    'address' => 'Alamat Kirim',
                    'branch' => 'Cabang',
                    'notes' => 'Keterangan',
                    'tax' => 'Pajak',
                    'shippingDate' => 'Tgl Pengiriman',
                    'shippingMethod' => 'Pengiriman',
                    'fob' => 'FOB',
                    'exchangeRate' => 'Kurs',
                ],
                'numberingOptions' => ['Pesanan Pembelian'],
                'showAddressPinButton' => true,
                'showPurchaseOrderNumber' => false,
                'itemModal' => [
                    'enabled' => true,
                ],
                'table' => [
                    'createLabel' => 'Tambah Pesanan Pembelian',
                    'refreshLabel' => 'Muat ulang',
                    'filterButtonLabel' => 'Filter lanjutan',
                    'searchPlaceholder' => 'Cari...',
                    'pageValue' => '11',
                    'columns' => [
                        ['id' => 'number', 'label' => 'Nomor #', 'widthClassName' => 'w-[200px]', 'align' => 'left'],
                        ['id' => 'date', 'label' => 'Tanggal', 'widthClassName' => 'w-[120px]', 'align' => 'left'],
                        ['id' => 'customerShort', 'label' => 'Pemasok', 'widthClassName' => 'w-[200px]', 'align' => 'left'],
                        ['id' => 'notes', 'label' => 'Keterangan', 'widthClassName' => 'w-[48%]', 'align' => 'left'],
                        ['id' => 'status', 'label' => 'Status', 'widthClassName' => 'w-[170px]', 'align' => 'left'],
                        ['id' => 'total', 'label' => 'Total', 'widthClassName' => 'w-[150px]', 'align' => 'right'],
                    ],
                    'rows' => [
                        ['id' => 'PO.2017.01.00002', 'number' => 'PO.2017.01.00002', 'date' => '12/01/2017', 'customer' => 'Applus', 'customerShort' => 'Applus', 'notes' => '', 'status' => 'Terproses', 'total' => '214,569', 'printedStatus' => 'all'],
                        ['id' => 'PO.2017.01.00003', 'number' => 'PO.2017.01.00003', 'date' => '08/01/2017', 'customer' => 'CV Ganda Putra', 'customerShort' => 'CV Ganda Putra', 'notes' => '', 'status' => 'Terproses', 'total' => '2,259,860,000', 'printedStatus' => 'all'],
                        ['id' => 'PO.2017.01.00001', 'number' => 'PO.2017.01.00001', 'date' => '01/01/2017', 'customer' => 'Applus', 'customerShort' => 'Applus', 'notes' => '', 'status' => 'Terproses', 'total' => '177,632', 'printedStatus' => 'all'],
                        ['id' => 'PO.2016.11.00001', 'number' => 'PO.2016.11.00001', 'date' => '15/11/2016', 'customer' => 'Toko Mega Mendung', 'customerShort' => 'Toko Mega Mendung', 'notes' => '', 'status' => 'Terproses', 'total' => '4,165,417,500', 'printedStatus' => 'all'],
                        ['id' => 'PO.2016.10.00007', 'number' => 'PO.2016.10.00007', 'date' => '19/10/2016', 'customer' => 'Applus', 'customerShort' => 'Applus', 'notes' => '', 'status' => 'Terproses', 'total' => '19,452,500', 'printedStatus' => 'all'],
                        ['id' => 'PO.2016.10.00006', 'number' => 'PO.2016.10.00006', 'date' => '17/10/2016', 'customer' => 'Toko Mega Mendung', 'customerShort' => 'Toko Mega Mendung', 'notes' => '', 'status' => 'Terproses', 'total' => '8,360,000', 'printedStatus' => 'all'],
                        ['id' => 'PO.2016.10.00005', 'number' => 'PO.2016.10.00005', 'date' => '12/10/2016', 'customer' => 'Toko Berkat Cell', 'customerShort' => 'Toko Berkat Cell', 'notes' => '', 'status' => 'Menunggu diproses', 'total' => '2,612,500', 'printedStatus' => 'all'],
                        ['id' => 'PO.2016.10.00004', 'number' => 'PO.2016.10.00004', 'date' => '11/10/2016', 'customer' => 'Toko Samudra Sparepart', 'customerShort' => 'Toko Samudra Sparepart', 'notes' => 'Karena ada permintaan perbaikan HP untuk speaker dan permintaan penjualan dimohon segera di proses.', 'status' => 'Sebagian diproses', 'total' => '16,720,000', 'printedStatus' => 'all'],
                        ['id' => 'PO.2016.10.00003', 'number' => 'PO.2016.10.00003', 'date' => '10/10/2016', 'customer' => 'Beautiful Cellular', 'customerShort' => 'Beautiful Cellular', 'notes' => '', 'status' => 'Ditutup', 'total' => '3,814,250', 'printedStatus' => 'all'],
                        ['id' => 'PO.2016.10.00002', 'number' => 'PO.2016.10.00002', 'date' => '05/10/2016', 'customer' => 'SAMSANG', 'customerShort' => 'SAMSANG', 'notes' => '', 'status' => 'Terproses', 'total' => '3,548', 'printedStatus' => 'all'],
                        ['id' => 'PO.2016.10.00001', 'number' => 'PO.2016.10.00001', 'date' => '04/10/2016', 'customer' => 'PT Selaras Inti', 'customerShort' => 'PT Selaras Inti', 'notes' => 'Dibutuhkan segera karena banyak pesanan untuk Item yang Di PO kan', 'status' => 'Terproses', 'total' => '55,123,750', 'printedStatus' => 'all'],
                    ],
                    'filters' => [
                        ['id' => 'date', 'rowKey' => 'date', 'options' => [['value' => 'all', 'label' => 'Tanggal: Semua'], ['value' => '12/01/2017', 'label' => 'Tanggal: 12/01/2017']]],
                        ['id' => 'customer', 'rowKey' => 'customer', 'options' => [['value' => 'all', 'label' => 'Pemasok: Semua'], ['value' => 'Applus', 'label' => 'Pemasok: Applus'], ['value' => 'Toko Mega Mendung', 'label' => 'Pemasok: Toko Mega Mendung']]],
                        ['id' => 'status', 'rowKey' => 'status', 'options' => [['value' => 'all', 'label' => 'Status: Semua'], ['value' => 'Terproses', 'label' => 'Status: Terproses'], ['value' => 'Menunggu diproses', 'label' => 'Status: Menunggu diproses'], ['value' => 'Sebagian diproses', 'label' => 'Status: Sebagian diproses'], ['value' => 'Ditutup', 'label' => 'Status: Ditutup']]],
                    ],
                    'downloadItems' => [['id' => 'download-excel', 'label' => 'Unduh Excel']],
                    'printItems' => [['id' => 'print-list', 'label' => 'Cetak daftar pesanan pembelian']],
                    'settingsItems' => [['id' => 'arrange-columns', 'label' => 'Atur kolom']],
                ],
                'costTable' => [
                    'columns' => [
                        ['id' => 'spacer', 'label' => '', 'kind' => 'spacer', 'widthClassName' => 'w-[38px]', 'align' => 'center'],
                        ['id' => 'name', 'label' => 'Nama Biaya', 'widthClassName' => 'w-[58%]', 'align' => 'left'],
                        ['id' => 'code', 'label' => 'Kode #', 'widthClassName' => 'w-[120px]', 'align' => 'center'],
                        ['id' => 'amount', 'label' => 'Jumlah', 'widthClassName' => 'w-[120px]', 'align' => 'right'],
                        ['id' => 'notes', 'label' => 'Keterangan', 'widthClassName' => 'w-[22%]', 'align' => 'left'],
                    ],
                    'emptyLabel' => 'Belum ada data',
                ],
                'draft' => [
                    'customer' => [],
                    'entryDate' => '28/04/2026',
                    'autoNumber' => true,
                    'numberingType' => 'Pesanan Pembelian',
                    'documentNumber' => '',
                    'currency' => '',
                    'exchangeRate' => '',
                    'exchangeRateLabel' => '',
                    'exchangeRatePrefix' => 'Rp',
                    'itemSearch' => '',
                    'items' => [
                        ['id' => 'purchase-order-draft-item-1', 'name' => 'Adaptor Fast Charging 20W', 'code' => 'AC2001', 'quantity' => '50', 'unit' => 'PCS', 'price' => '65,000', 'discount' => '0', 'total' => '3,250,000'],
                    ],
                    'itemCountLabel' => '1 Barang (50)',
                    'paymentTerms' => [],
                    'purchaseOrderNumber' => '',
                    'address' => '',
                    'branches' => ['JAKARTA'],
                    '__branchId' => 1,
                    'notes' => '',
                    'taxEnabled' => false,
                    'taxIncluded' => false,
                    'shippingDate' => '28/04/2026',
                    'shippingMethod' => [],
                    'fob' => [],
                    'costSearch' => '',
                    'additionalCosts' => [
                        ['id' => 'purchase-order-draft-cost-1', 'name' => 'Biaya Pengiriman', 'code' => 'ONGKIR', 'amount' => '150,000', 'notes' => 'Estimasi pengiriman awal'],
                    ],
                    'summary' => [
                        ['Total', 'Rp 3,400,000'],
                        ['Status', 'Menunggu diproses'],
                        ['Dicetak/email', 'Belum cetak/email'],
                    ],
                    'processedBy' => null,
                    'approvalStamp' => '',
                    'processStamp' => '',
                    'showProcessButton' => false,
                    'processDisabled' => false,
                    'subtotal' => 'Rp 3,250,000',
                    'discountValue' => '0',
                    'discountPrefix' => 'Rp',
                    'taxLabel' => '',
                    'taxValue' => '',
                    'total' => 'Rp 3,400,000',
                    'itemModal' => [
                        'title' => 'Rincian Barang',
                        'tabs' => [
                            ['id' => 'details', 'label' => 'Rincian Barang'],
                            ['id' => 'info', 'label' => 'Info lainnya'],
                        ],
                        'values' => [
                            'code' => 'AC2001',
                            'name' => 'Adaptor Fast Charging 20W',
                            'quantity' => '50',
                            'unit' => ['PCS'],
                            'price' => '65,000',
                            'discountPercent' => '',
                            'discountValue' => '0',
                            'total' => 'Rp 3,250,000',
                            'taxChecked' => false,
                            'taxLabel' => 'PPN 10 %',
                            'warehouse' => ['GD. JAKARTA'],
                            'salesPerson' => [],
                            'department' => [],
                            'notes' => 'Pembelian untuk stok cabang utama.',
                        ],
                    ],
                ],
                'detailRecords' => [
                    'PO.2017.01.00002' => [
                        'customer' => ['[VJKT-0002] Applus'],
                        'entryDate' => '12/01/2017',
                        'autoNumber' => false,
                        'numberingType' => 'Pesanan Pembelian',
                        'documentNumber' => 'PO.2017.01.00002',
                        'currency' => 'USD',
                        'exchangeRate' => '12,560',
                        'exchangeRateLabel' => '1 USD=XXX IDR',
                        'exchangeRatePrefix' => 'Rp',
                        'itemSearch' => '',
                        'items' => [
                            ['id' => 'PO.2017.01.00002-item-1', 'name' => 'Iphone 6 S Plus 32 GB', 'code' => '6316001', 'quantity' => '243', 'unit' => 'PCS', 'price' => '883', 'discount' => '0', 'total' => '214,569'],
                        ],
                        'itemCountLabel' => '1 Barang (243)',
                        'paymentTerms' => ['Net 30 Hari'],
                        'purchaseOrderNumber' => '',
                        'address' => '',
                        'branches' => ['JAKARTA'],
                    '__branchId' => 1,
                        'notes' => '',
                        'taxEnabled' => false,
                        'taxIncluded' => false,
                        'shippingDate' => '12/01/2017',
                        'shippingMethod' => ['Ekspedisi Internal'],
                        'fob' => ['Gudang Supplier'],
                        'costSearch' => '',
                        'additionalCosts' => [
                            ['id' => 'PO.2017.01.00002-cost-1', 'name' => 'Biaya Asuransi', 'code' => 'ASR-01', 'amount' => '850', 'notes' => 'Proteksi pengiriman impor'],
                        ],
                        'summary' => [
                            ['Total', '$ 214,569'],
                            ['Status', 'Terproses'],
                            ['Dicetak/email', 'Belum cetak/email'],
                        ],
                        'processedBy' => [
                            ['number' => 'PB.2017.01.00004', 'date' => '15/01/2017'],
                        ],
                        'approvalStamp' => '',
                        'processStamp' => 'TERPROSES',
                        'showProcessButton' => true,
                        'processDisabled' => true,
                        'subtotal' => '$ 214,569',
                        'discountValue' => '0',
                        'discountPrefix' => '$',
                        'taxLabel' => '',
                        'taxValue' => '',
                        'total' => '$ 214,569',
                        'itemModal' => [
                            'title' => 'Rincian Barang',
                            'tabs' => [
                                ['id' => 'details', 'label' => 'Rincian Barang'],
                                ['id' => 'info', 'label' => 'Info lainnya'],
                            ],
                            'values' => [
                                'code' => '6316001',
                                'name' => 'Iphone 6 S Plus 32 GB',
                                'quantity' => '243',
                                'unit' => ['PCS'],
                                'price' => '883',
                                'discountPercent' => '',
                                'discountValue' => '0',
                                'total' => '$ 214,569',
                                'taxChecked' => false,
                                'taxLabel' => 'PPN 10 %',
                                'warehouse' => ['GD. IMPORT'],
                                'salesPerson' => [],
                                'department' => [],
                                'notes' => 'Pembelian impor untuk restock awal tahun.',
                            ],
                        ],
                    ],
                ],
            ],
        ]);
    }
}
